import { saveMealTemplate, type MealTemplate } from "../lib/meal-templates-firestore"

// Easy Indian breakfast templates
const easyIndianBreakfastTemplates: MealTemplate[] = [
  {
    name: "Poha with Peanuts and Vegetables",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "weight-gain"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
    medicalConditionsUnsafe: ["nut-allergy"],
    allergens: ["peanuts"],
    calories: 250,
    protein: 8,
    carbs: 40,
    fat: 7,
    ingredients: [
      {
        name: "Flattened rice (poha)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 180,
          protein: 4,
          carbs: 36,
          fat: 1,
        },
      },
      {
        name: "Peanuts",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 35,
          protein: 2,
          carbs: 1,
          fat: 3,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Green peas",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 15,
          protein: 1,
          carbs: 3,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mustard seeds, curry leaves, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Rinse poha, drain, and set aside. Heat oil, add mustard seeds, curry leaves, and turmeric. Add onions, peas, and peanuts. Mix in poha, salt, and lemon juice. Cook for 5 minutes.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "Central India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Bread Upma with Vegetables",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "pcod"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 220,
    protein: 7,
    carbs: 35,
    fat: 6,
    ingredients: [
      {
        name: "Whole wheat bread slices",
        quantity: "4 slices",
        nutritionalInfo: {
          calories: 160,
          protein: 6,
          carbs: 30,
          fat: 2,
        },
      },
      {
        name: "Mixed vegetables (carrots, beans, peas)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 25,
          protein: 1,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mustard seeds, curry leaves, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Cut bread into small cubes. Heat oil, add mustard seeds, curry leaves, and turmeric. Add onions and vegetables, sauté until soft. Add bread cubes and salt, mix well. Cook for 5 minutes.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Besan Chilla with Mint Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 180,
    protein: 10,
    carbs: 20,
    fat: 7,
    ingredients: [
      {
        name: "Gram flour (besan)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 8,
          carbs: 18,
          fat: 2,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Tomato, finely chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Green chili, finely chopped",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mint chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0.5,
        },
      },
    ],
    preparation:
      "Mix besan with water to make a smooth batter. Add chopped vegetables, salt, and spices. Heat a non-stick pan, pour a ladleful of batter, spread it thin. Cook until golden brown on both sides. Serve with mint chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: true,
    isHighProtein: true,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Vermicelli Upma with Vegetables",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "pcod"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 230,
    protein: 6,
    carbs: 40,
    fat: 5,
    ingredients: [
      {
        name: "Vermicelli",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 160,
          protein: 5,
          carbs: 35,
          fat: 1,
        },
      },
      {
        name: "Mixed vegetables (carrots, beans, peas)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 25,
          protein: 1,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mustard seeds, curry leaves, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Dry roast vermicelli until light brown. Heat oil, add mustard seeds, curry leaves, and turmeric. Add onions and vegetables, sauté until soft. Add roasted vermicelli, water, and salt. Cook until vermicelli is soft and water is absorbed.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Vegetable Sandwich with Mint Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "pcod"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 250,
    protein: 8,
    carbs: 40,
    fat: 6,
    ingredients: [
      {
        name: "Whole wheat bread slices",
        quantity: "4 slices",
        nutritionalInfo: {
          calories: 160,
          protein: 6,
          carbs: 30,
          fat: 2,
        },
      },
      {
        name: "Cucumber, sliced",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Tomato, sliced",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Onion, sliced",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Mint chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0.5,
        },
      },
      {
        name: "Butter",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 35,
          protein: 0,
          carbs: 0,
          fat: 4,
        },
      },
    ],
    preparation:
      "Apply butter on bread slices. Spread mint chutney on one slice. Layer with cucumber, tomato, and onion slices. Cover with another bread slice. Cut diagonally and serve.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Sprouts Salad with Lemon Dressing",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol", "pcod"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 150,
    protein: 9,
    carbs: 25,
    fat: 2,
    ingredients: [
      {
        name: "Mixed sprouts (moong, chana)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 8,
          carbs: 22,
          fat: 1,
        },
      },
      {
        name: "Cucumber, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Tomato, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Lemon juice",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 3,
          protein: 0.1,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Chaat masala",
        quantity: "1/2 tsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.1,
          carbs: 0.4,
          fat: 0.1,
        },
      },
    ],
    preparation:
      "Mix all sprouts and vegetables in a bowl. Add lemon juice, chaat masala, and salt. Toss well and serve immediately.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 5,
  },
  {
    name: "Daliya (Broken Wheat) Porridge",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 200,
    protein: 7,
    carbs: 35,
    fat: 3,
    ingredients: [
      {
        name: "Broken wheat (daliya)",
        quantity: "1/3 cup",
        nutritionalInfo: {
          calories: 150,
          protein: 6,
          carbs: 32,
          fat: 1,
        },
      },
      {
        name: "Mixed vegetables (carrots, beans, peas)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 15,
          protein: 0.7,
          carbs: 3,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1/2 tsp",
        nutritionalInfo: {
          calories: 20,
          protein: 0,
          carbs: 0,
          fat: 2.2,
        },
      },
      {
        name: "Cumin seeds, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0.1,
          carbs: 0.5,
          fat: 0.3,
        },
      },
    ],
    preparation:
      "Heat oil, add cumin seeds and turmeric. Add onions and vegetables, sauté until soft. Add broken wheat and water. Cook until soft and water is absorbed. Add salt to taste.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Moong Dal Cheela with Curd",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: ["lactose-intolerance"],
    allergens: ["dairy"],
    calories: 220,
    protein: 12,
    carbs: 30,
    fat: 5,
    ingredients: [
      {
        name: "Yellow moong dal (soaked for 4 hours)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 9,
          carbs: 22,
          fat: 1,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Green chili, finely chopped",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Curd",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 2.5,
          carbs: 2.5,
          fat: 1.5,
        },
      },
    ],
    preparation:
      "Grind soaked moong dal with water to make a smooth batter. Add chopped vegetables, salt, and spices. Heat a non-stick pan, pour a ladleful of batter, spread it thin. Cook until golden brown on both sides. Serve with curd.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 15,
  },
  // Additional Indian breakfast items
  {
    name: "Ragi Dosa with Coconut Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 200,
    protein: 6,
    carbs: 35,
    fat: 4,
    ingredients: [
      {
        name: "Ragi flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1.5,
        },
      },
      {
        name: "Rice flour",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 0.7,
          carbs: 9,
          fat: 0.1,
        },
      },
      {
        name: "Cumin seeds",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 8,
          protein: 0.4,
          carbs: 1,
          fat: 0.5,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Coconut chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 45,
          protein: 1,
          carbs: 2,
          fat: 4,
        },
      },
    ],
    preparation:
      "Mix ragi flour, rice flour, cumin seeds, and salt with water to make a thin batter. Heat a non-stick pan, pour a ladleful of batter, spread it thin. Cook until crisp. Serve with coconut chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Paneer Paratha with Curd",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-gain", "muscle-building"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["lactose-intolerance", "high-cholesterol"],
    allergens: ["dairy", "gluten"],
    calories: 350,
    protein: 15,
    carbs: 40,
    fat: 15,
    ingredients: [
      {
        name: "Whole wheat flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 4,
          carbs: 25,
          fat: 1,
        },
      },
      {
        name: "Paneer (cottage cheese), grated",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 180,
          protein: 10,
          carbs: 3,
          fat: 14,
        },
      },
      {
        name: "Green chilies, finely chopped",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.2,
          fat: 0,
        },
      },
      {
        name: "Coriander leaves, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.2,
          carbs: 0.4,
          fat: 0,
        },
      },
      {
        name: "Ghee",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      },
      {
        name: "Curd",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 2.5,
          carbs: 2.5,
          fat: 1.5,
        },
      },
    ],
    preparation:
      "Mix grated paneer with chopped green chilies, coriander leaves, and salt. Make small balls of wheat dough, stuff with paneer mixture, roll into parathas. Cook on a hot griddle with ghee until golden brown on both sides. Serve with curd.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 25,
  },
  {
    name: "Masala Chai with Biscuits",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["maintenance"],
    medicalConditionsSafe: [],
    medicalConditionsUnsafe: ["diabetes", "hypertension"],
    allergens: ["dairy", "gluten"],
    calories: 180,
    protein: 4,
    carbs: 30,
    fat: 5,
    ingredients: [
      {
        name: "Milk",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 3.5,
          carbs: 12,
          fat: 4.5,
        },
      },
      {
        name: "Tea leaves",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.1,
          carbs: 0.4,
          fat: 0,
        },
      },
      {
        name: "Sugar",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 16,
          protein: 0,
          carbs: 4,
          fat: 0,
        },
      },
      {
        name: "Cardamom, cinnamon, ginger",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0.1,
          carbs: 1,
          fat: 0.1,
        },
      },
      {
        name: "Biscuits",
        quantity: "2 pieces",
        nutritionalInfo: {
          calories: 80,
          protein: 1,
          carbs: 14,
          fat: 3,
        },
      },
    ],
    preparation:
      "Boil water with tea leaves, add milk and bring to a boil. Add sugar and spices, simmer for 2-3 minutes. Strain and serve hot with biscuits.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: false,
    isLowSugar: false,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 10,
  },
  // Indian snack items
  {
    name: "Bhel Puri",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes"],
    allergens: ["gluten"],
    calories: 220,
    protein: 5,
    carbs: 40,
    fat: 6,
    ingredients: [
      {
        name: "Puffed rice (murmura)",
        quantity: "2 cups",
        nutritionalInfo: {
          calories: 140,
          protein: 3,
          carbs: 30,
          fat: 0.5,
        },
      },
      {
        name: "Sev (crispy noodles)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 1,
          carbs: 5,
          fat: 2.5,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Tomato, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Tamarind chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 30,
          protein: 0.2,
          carbs: 7,
          fat: 0.1,
        },
      },
      {
        name: "Mint chutney",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0.1,
        },
      },
    ],
    preparation:
      "Mix puffed rice, sev, chopped onions, tomatoes, and coriander leaves. Add tamarind and mint chutneys, chat masala, and salt. Toss well and serve immediately.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: false,
    isLowSugar: false,
    region: "West India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Dhokla",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 180,
    protein: 6,
    carbs: 30,
    fat: 4,
    ingredients: [
      {
        name: "Gram flour (besan)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 5,
          carbs: 22,
          fat: 2,
        },
      },
      {
        name: "Yogurt",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 1.5,
          carbs: 2,
          fat: 1.5,
        },
      },
      {
        name: "Green chili-ginger paste",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0.1,
        },
      },
      {
        name: "Mustard seeds, curry leaves for tempering",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 0.5,
          fat: 0.2,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
    ],
    preparation:
      "Mix gram flour, yogurt, water, salt, and green chili-ginger paste. Add fruit salt and mix well. Steam for 15 minutes. Prepare tempering with mustard seeds and curry leaves. Pour over dhokla, cut into pieces and serve.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "West India",
    difficulty: "medium",
    prepTime: 30,
  },
  {
    name: "Roasted Makhana (Foxnuts)",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease", "high-cholesterol", "hypertension"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 150,
    protein: 4,
    carbs: 15,
    fat: 9,
    ingredients: [
      {
        name: "Makhana (foxnuts)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 100,
          protein: 4,
          carbs: 15,
          fat: 0.5,
        },
      },
      {
        name: "Ghee or olive oil",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      },
      {
        name: "Rock salt",
        quantity: "1/4 tsp",
        nutritionalInfo: {
          calories: 0,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
      },
      {
        name: "Black pepper",
        quantity: "1/4 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.3,
          fat: 0,
        },
      },
    ],
    preparation:
      "Heat ghee or oil in a pan. Add makhana and roast on low flame until crisp. Add rock salt and black pepper. Mix well and let it cool. Store in an airtight container.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: true,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 10,
  },
]

// Function to populate meal templates
async function populateIndianMealTemplates() {
  try {
    console.log(`Starting to populate ${easyIndianBreakfastTemplates.length} Indian breakfast templates...`)

    for (const template of easyIndianBreakfastTemplates) {
      // Add to Firestore
      const id = await saveMealTemplate(template)
      console.log(`Added template: ${template.name} with ID: ${id}`)
    }

    console.log("Successfully populated Indian meal templates!")
  } catch (error) {
    console.error("Error populating Indian meal templates:", error)
  }
}

// Run the function
populateIndianMealTemplates()
