import { db, createTimestamp } from "../firebase/db"
import { CATEGORIES, REGIONS } from "../constants"
import type { DetailedFoodItem, Recipe } from "../types"
import { generateKeywords } from "../utils"

const indianFoods: DetailedFoodItem[] = [
  // GRAINS, LEGUMES, AND PULSES
  {
    id: "brown-rice",
    name: "Brown Rice",
    category: CATEGORIES.GRAINS,
    description: "Whole grain rice with a nutty flavor and chewy texture",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 111,
      protein: 2.6,
      carbohydrates: 23.0,
      fat: 0.9,
      fiber: 1.8,
      sugar: 0.2,
      sodium: 5,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 0.1,
      k: 0.4,
      b1: 0.16,
      b2: 0.02,
      b3: 1.6,
      b5: 0.8,
      b6: 0.3,
      b7: 6.3,
      b9: 8,
      b12: 0,
    },
    minerals: {
      calcium: 5,
      iron: 0.2,
      magnesium: 39,
      phosphorus: 96,
      potassium: 86,
      sodium: 5,
      zinc: 0.7,
      copper: 0.1,
      manganese: 0.6,
      selenium: 11.5,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 64,
      isoleucine: 117,
      leucine: 203,
      lysine: 102,
      methionine: 49,
      phenylalanine: 131,
      threonine: 89,
      tryptophan: 29,
      valine: 149,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.3,
      polyunsaturated: 0.3,
      omega3: 0.0,
      omega6: 0.3,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "chickpea-garbanzo-bean",
    name: "Chickpea (Garbanzo Bean)",
    category: CATEGORIES.GRAINS,
    description: "Versatile legume used in many Indian dishes like chana masala",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 164,
      protein: 8.9,
      carbohydrates: 27.4,
      fat: 2.6,
      fiber: 7.6,
      sugar: 4.8,
      sodium: 24,
    },
    vitamins: {
      a: 1,
      c: 0.5,
      d: 0,
      e: 0.5,
      k: 0.5,
      b1: 0.15,
      b2: 0.06,
      b3: 0.5,
      b5: 0.3,
      b6: 0.2,
      b7: 7.6,
      b9: 172,
      b12: 0,
    },
    minerals: {
      calcium: 49,
      iron: 2.9,
      magnesium: 48,
      phosphorus: 168,
      potassium: 291,
      sodium: 24,
      zinc: 1.5,
      copper: 0.3,
      manganese: 1.1,
      selenium: 1.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 240,
      isoleucine: 370,
      leucine: 640,
      lysine: 570,
      methionine: 120,
      phenylalanine: 390,
      threonine: 280,
      tryptophan: 80,
      valine: 380,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.6,
      polyunsaturated: 1.1,
      omega3: 0.1,
      omega6: 1.0,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "red-lentils-masoor-dal",
    name: "Red Lentils (Masoor Dal)",
    category: CATEGORIES.GRAINS,
    description: "Quick-cooking lentils used in many Indian dal recipes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 116,
      protein: 9.0,
      carbohydrates: 20.1,
      fat: 0.4,
      fiber: 11.0,
      sugar: 1.8,
      sodium: 3,
    },
    vitamins: {
      a: 1,
      c: 2.1,
      d: 0,
      e: 0.2,
      k: 6.0,
      b1: 0.2,
      b2: 0.2,
      b3: 1.1,
      b5: 1.3,
      b6: 0.3,
      b7: 4.4,
      b9: 181,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 3.3,
      magnesium: 36,
      phosphorus: 180,
      potassium: 369,
      sodium: 3,
      zinc: 1.3,
      copper: 0.2,
      manganese: 0.5,
      selenium: 0.6,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 240,
      isoleucine: 410,
      leucine: 710,
      lysine: 540,
      methionine: 100,
      phenylalanine: 440,
      threonine: 300,
      tryptophan: 90,
      valine: 430,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.0,
      omega6: 0.2,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "kidney-beans-rajma",
    name: "Kidney Beans (Rajma)",
    category: CATEGORIES.GRAINS,
    description: "Red kidney beans used in the popular North Indian dish, rajma",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 127,
      protein: 8.7,
      carbohydrates: 22.8,
      fat: 0.5,
      fiber: 6.4,
      sugar: 0.3,
      sodium: 6,
    },
    vitamins: {
      a: 11,
      c: 0.0,
      d: 0,
      e: 0.0,
      k: 6.6,
      b1: 0.2,
      b2: 0.1,
      b3: 0.5,
      b5: 0.2,
      b6: 0.3,
      b7: 11.0,
      b9: 130,
      b12: 0,
    },
    minerals: {
      calcium: 36,
      iron: 1.6,
      magnesium: 43,
      phosphorus: 143,
      potassium: 405,
      sodium: 6,
      zinc: 1.0,
      copper: 0.2,
      manganese: 0.5,
      selenium: 0.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 240,
      isoleucine: 380,
      leucine: 670,
      lysine: 580,
      methionine: 110,
      phenylalanine: 420,
      threonine: 310,
      tryptophan: 90,
      valine: 410,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.0,
      omega6: 0.2,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "pearl-millet-bajra",
    name: "Pearl Millet (Bajra)",
    category: CATEGORIES.GRAINS,
    description: "Gluten-free grain used in roti and other dishes, common in Rajasthan",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.WEST,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 110,
      protein: 3.4,
      carbohydrates: 21.5,
      fat: 0.9,
      fiber: 1.3,
      sugar: 0.7,
      sodium: 5,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 0.0,
      k: 0.0,
      b1: 0.4,
      b2: 0.2,
      b3: 2.4,
      b5: 0.6,
      b6: 0.4,
      b7: 0.0,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 8,
      iron: 0.8,
      magnesium: 82,
      phosphorus: 132,
      potassium: 121,
      sodium: 5,
      zinc: 1.1,
      copper: 0.3,
      manganese: 0.5,
      selenium: 2.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 99,
      isoleucine: 180,
      leucine: 370,
      lysine: 170,
      methionine: 70,
      phenylalanine: 220,
      threonine: 150,
      tryptophan: 48,
      valine: 240,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.2,
      polyunsaturated: 0.3,
      omega3: 0.0,
      omega6: 0.3,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "sorghum-jowar",
    name: "Sorghum (Jowar)",
    category: CATEGORIES.GRAINS,
    description: "Gluten-free grain used in roti and other dishes, common in Maharashtra",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.WEST,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 339,
      protein: 10.6,
      carbohydrates: 72.1,
      fat: 3.1,
      fiber: 6.3,
      sugar: 2.5,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 0.0,
      k: 0.0,
      b1: 0.4,
      b2: 0.1,
      b3: 2.9,
      b5: 0.8,
      b6: 0.6,
      b7: 0.0,
      b9: 39,
      b12: 0,
    },
    minerals: {
      calcium: 13,
      iron: 4.1,
      magnesium: 147,
      phosphorus: 289,
      potassium: 363,
      sodium: 2,
      zinc: 2.2,
      copper: 0.5,
      manganese: 1.6,
      selenium: 8.4,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 240,
      isoleucine: 410,
      leucine: 1170,
      lysine: 300,
      methionine: 180,
      phenylalanine: 540,
      threonine: 310,
      tryptophan: 110,
      valine: 470,
    },
    fattyAcids: {
      saturated: 0.5,
      monounsaturated: 1.0,
      polyunsaturated: 1.4,
      omega3: 0.1,
      omega6: 1.3,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "finger-millet-ragi",
    name: "Finger Millet (Ragi)",
    category: CATEGORIES.GRAINS,
    description: "Nutritious millet used in various dishes, common in South India",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 336,
      protein: 7.3,
      carbohydrates: 72.0,
      fat: 1.5,
      fiber: 11.5,
      sugar: 0.6,
      sodium: 20,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 1.1,
      k: 1.5,
      b1: 0.4,
      b2: 0.2,
      b3: 1.1,
      b5: 0.5,
      b6: 0.3,
      b7: 0.0,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 344,
      iron: 3.9,
      magnesium: 114,
      phosphorus: 283,
      potassium: 408,
      sodium: 20,
      zinc: 2.3,
      copper: 0.8,
      manganese: 1.5,
      selenium: 10.8,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 132,
      isoleucine: 240,
      leucine: 370,
      lysine: 310,
      methionine: 90,
      phenylalanine: 240,
      threonine: 240,
      tryptophan: 78,
      valine: 280,
    },
    fattyAcids: {
      saturated: 3.0,
      monounsaturated: 1.4,
      polyunsaturated: 3.6,
      omega3: 1.4,
      omega6: 2.2,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "cinnamon-dalchini",
    name: "Cinnamon (Dalchini)",
    category: CATEGORIES.SPICES,
    description: "Sweet and woody spice used in both sweet and savory dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup ground",
    },
    nutrients: {
      calories: 247,
      protein: 3.9,
      carbohydrates: 80.6,
      fat: 1.2,
      fiber: 53.1,
      sugar: 2.2,
      sodium: 10,
    },
    vitamins: {
      a: 52,
      c: 3.8,
      d: 0,
      e: 2.3,
      k: 31.2,
      b1: 0.08,
      b2: 0.04,
      b3: 1.3,
      b5: 0.4,
      b6: 0.16,
      b7: 0.5,
      b9: 6,
      b12: 0,
    },
    minerals: {
      calcium: 1002,
      iron: 8.3,
      magnesium: 60,
      phosphorus: 64,
      potassium: 431,
      sodium: 10,
      zinc: 1.8,
      copper: 0.3,
      manganese: 17.5,
      selenium: 3.1,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 86,
      isoleucine: 156,
      leucine: 240,
      lysine: 201,
      methionine: 59,
      phenylalanine: 156,
      threonine: 156,
      tryptophan: 51,
      valine: 182,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.2,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "black-pepper-kali-mirch",
    name: "Black Pepper (Kali Mirch)",
    category: CATEGORIES.SPICES,
    description: "Pungent spice used in many Indian dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup ground",
    },
    nutrients: {
      calories: 255,
      protein: 10.4,
      carbohydrates: 63.9,
      fat: 3.3,
      fiber: 25.3,
      sugar: 0.6,
      sodium: 20,
    },
    vitamins: {
      a: 27,
      c: 0.0,
      d: 0,
      e: 1.0,
      k: 163.7,
      b1: 0.11,
      b2: 0.24,
      b3: 1.1,
      b5: 1.4,
      b6: 0.29,
      b7: 0.5,
      b9: 17,
      b12: 0,
    },
    minerals: {
      calcium: 437,
      iron: 28.9,
      magnesium: 194,
      phosphorus: 173,
      potassium: 1329,
      sodium: 20,
      zinc: 1.4,
      copper: 1.3,
      manganese: 12.8,
      selenium: 4.9,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 229,
      isoleucine: 416,
      leucine: 641,
      lysine: 537,
      methionine: 156,
      phenylalanine: 416,
      threonine: 416,
      tryptophan: 135,
      valine: 485,
    },
    fattyAcids: {
      saturated: 1.1,
      monounsaturated: 0.7,
      polyunsaturated: 1.0,
      omega3: 0.2,
      omega6: 0.8,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "red-chilli-powder",
    name: "Red Chilli Powder",
    category: CATEGORIES.SPICES,
    description: "Ground dried red chillies used to add heat and color to dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 282,
      protein: 13.5,
      carbohydrates: 54.8,
      fat: 14.3,
      fiber: 34.8,
      sugar: 10.3,
      sodium: 30,
    },
    vitamins: {
      a: 41610,
      c: 0.0,
      d: 0,
      e: 29.8,
      k: 80.3,
      b1: 0.33,
      b2: 0.92,
      b3: 8.7,
      b5: 2.0,
      b6: 2.45,
      b7: 0.5,
      b9: 49,
      b12: 0,
    },
    minerals: {
      calcium: 148,
      iron: 7.8,
      magnesium: 152,
      phosphorus: 293,
      potassium: 2014,
      sodium: 30,
      zinc: 2.5,
      copper: 0.4,
      manganese: 2.0,
      selenium: 8.8,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 297,
      isoleucine: 540,
      leucine: 832,
      lysine: 697,
      methionine: 203,
      phenylalanine: 540,
      threonine: 540,
      tryptophan: 176,
      valine: 630,
    },
    fattyAcids: {
      saturated: 2.1,
      monounsaturated: 2.7,
      polyunsaturated: 6.7,
      omega3: 0.3,
      omega6: 6.4,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "garam-masala",
    name: "Garam Masala",
    category: CATEGORIES.SPICES,
    description: "Blend of ground spices used in many Indian dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 375,
      protein: 13.7,
      carbohydrates: 58.3,
      fat: 14.1,
      fiber: 29.3,
      sugar: 1.5,
      sodium: 56,
    },
    vitamins: {
      a: 684,
      c: 7.1,
      d: 0,
      e: 2.8,
      k: 35.0,
      b1: 0.33,
      b2: 0.32,
      b3: 2.8,
      b5: 0.8,
      b6: 0.6,
      b7: 0.5,
      b9: 22,
      b12: 0,
    },
    minerals: {
      calcium: 458,
      iron: 29.2,
      magnesium: 252,
      phosphorus: 252,
      potassium: 1329,
      sodium: 56,
      zinc: 4.1,
      copper: 0.7,
      manganese: 12.5,
      selenium: 12.3,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 301,
      isoleucine: 548,
      leucine: 844,
      lysine: 707,
      methionine: 206,
      phenylalanine: 548,
      threonine: 548,
      tryptophan: 178,
      valine: 639,
    },
    fattyAcids: {
      saturated: 3.9,
      monounsaturated: 6.2,
      polyunsaturated: 2.5,
      omega3: 0.5,
      omega6: 2.0,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "asafoetida-hing",
    name: "Asafoetida (Hing)",
    category: CATEGORIES.SPICES,
    description: "Strong-smelling spice used in small quantities in many Indian dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 310,
      protein: 4.0,
      carbohydrates: 67.8,
      fat: 1.1,
      fiber: 4.4,
      sugar: 0.0,
      sodium: 68,
    },
    vitamins: {
      a: 0,
      c: 7.0,
      d: 0,
      e: 0.0,
      k: 0.0,
      b1: 0.2,
      b2: 0.3,
      b3: 1.4,
      b5: 0.4,
      b6: 0.5,
      b7: 0.5,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 683,
      iron: 28.1,
      magnesium: 60,
      phosphorus: 110,
      potassium: 1288,
      sodium: 68,
      zinc: 3.4,
      copper: 0.3,
      manganese: 1.0,
      selenium: 0.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 88,
      isoleucine: 160,
      leucine: 246,
      lysine: 206,
      methionine: 60,
      phenylalanine: 160,
      threonine: 160,
      tryptophan: 52,
      valine: 186,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.3,
      polyunsaturated: 0.4,
      omega3: 0.1,
      omega6: 0.3,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },

  // DAIRY PRODUCTS
  {
    id: "milk-cow-full-fat",
    name: "Milk (Cow, Full Fat)",
    category: CATEGORIES.DAIRY,
    description: "Full-fat cow's milk used in many Indian dishes and beverages",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "ml",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 67,
      protein: 3.3,
      carbohydrates: 4.8,
      fat: 4.1,
      fiber: 0.0,
      sugar: 5.1,
      sodium: 43,
    },
    vitamins: {
      a: 126,
      c: 0.0,
      d: 1.3,
      e: 0.1,
      k: 0.3,
      b1: 0.04,
      b2: 0.18,
      b3: 0.1,
      b5: 0.3,
      b6: 0.04,
      b7: 2.0,
      b9: 5,
      b12: 0.4,
    },
    minerals: {
      calcium: 120,
      iron: 0.0,
      magnesium: 12,
      phosphorus: 93,
      potassium: 152,
      sodium: 43,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 89,
      isoleucine: 189,
      leucine: 322,
      lysine: 261,
      methionine: 83,
      phenylalanine: 159,
      threonine: 149,
      tryptophan: 46,
      valine: 220,
    },
    fattyAcids: {
      saturated: 2.5,
      monounsaturated: 1.1,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0.1,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "curd-yogurt-plain",
    name: "Curd (Yogurt, Plain)",
    category: CATEGORIES.DAIRY,
    description: "Fermented milk product used in many Indian dishes and as a side",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 61,
      protein: 3.5,
      carbohydrates: 4.7,
      fat: 3.3,
      fiber: 0.0,
      sugar: 4.7,
      sodium: 46,
    },
    vitamins: {
      a: 99,
      c: 0.5,
      d: 0.1,
      e: 0.0,
      k: 0.2,
      b1: 0.03,
      b2: 0.14,
      b3: 0.1,
      b5: 0.4,
      b6: 0.03,
      b7: 2.0,
      b9: 7,
      b12: 0.4,
    },
    minerals: {
      calcium: 121,
      iron: 0.1,
      magnesium: 12,
      phosphorus: 90,
      potassium: 155,
      sodium: 46,
      zinc: 0.6,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.3,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 94,
      isoleucine: 200,
      leucine: 340,
      lysine: 276,
      methionine: 88,
      phenylalanine: 168,
      threonine: 157,
      tryptophan: 49,
      valine: 233,
    },
    fattyAcids: {
      saturated: 2.1,
      monounsaturated: 0.9,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0.1,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "paneer",
    name: "Paneer",
    category: CATEGORIES.DAIRY,
    description: "Fresh cheese common in South Asian cuisine, especially in North India",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cubes",
    },
    nutrients: {
      calories: 265,
      protein: 18.3,
      carbohydrates: 3.6,
      fat: 20.8,
      fiber: 0.0,
      sugar: 1.0,
      sodium: 5,
    },
    vitamins: {
      a: 500,
      c: 0.0,
      d: 0.3,
      e: 0.3,
      k: 1.0,
      b1: 0.03,
      b2: 0.21,
      b3: 0.1,
      b5: 0.5,
      b6: 0.08,
      b7: 2.0,
      b9: 17,
      b12: 1.1,
    },
    minerals: {
      calcium: 510,
      iron: 0.7,
      magnesium: 28,
      phosphorus: 490,
      potassium: 130,
      sodium: 5,
      zinc: 2.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 15.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 494,
      isoleucine: 1050,
      leucine: 1790,
      lysine: 1450,
      methionine: 460,
      phenylalanine: 880,
      threonine: 830,
      tryptophan: 260,
      valine: 1220,
    },
    fattyAcids: {
      saturated: 13.2,
      monounsaturated: 6.0,
      polyunsaturated: 0.6,
      omega3: 0.2,
      omega6: 0.4,
      trans: 0.5,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "ghee",
    name: "Ghee (Clarified Butter)",
    category: CATEGORIES.DAIRY,
    description: "Clarified butter used in Indian cooking and religious rituals",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 900,
      protein: 0.0,
      carbohydrates: 0.0,
      fat: 100.0,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 0,
    },
    vitamins: {
      a: 3069,
      c: 0.0,
      d: 1.2,
      e: 2.8,
      k: 8.6,
      b1: 0.0,
      b2: 0.0,
      b3: 0.0,
      b5: 0.0,
      b6: 0.0,
      b7: 0.0,
      b9: 0,
      b12: 0.0,
    },
    minerals: {
      calcium: 4,
      iron: 0.0,
      magnesium: 0,
      phosphorus: 0,
      potassium: 0,
      sodium: 0,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,
    },
    fattyAcids: {
      saturated: 65.0,
      monounsaturated: 28.7,
      polyunsaturated: 3.7,
      omega3: 1.4,
      omega6: 2.3,
      trans: 2.6,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "buttermilk-chaas",
    name: "Buttermilk (Chaas)",
    category: CATEGORIES.DAIRY,
    description: "Fermented milk drink popular in India, especially during summer",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.WEST,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "ml",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 32,
      protein: 3.3,
      carbohydrates: 4.8,
      fat: 0.1,
      fiber: 0.0,
      sugar: 4.8,
      sodium: 105,
    },
    vitamins: {
      a: 2,
      c: 0.4,
      d: 0.0,
      e: 0.0,
      k: 0.0,
      b1: 0.03,
      b2: 0.15,
      b3: 0.1,
      b5: 0.3,
      b6: 0.03,
      b7: 1.5,
      b9: 5,
      b12: 0.2,
    },
    minerals: {
      calcium: 116,
      iron: 0.1,
      magnesium: 11,
      phosphorus: 89,
      potassium: 151,
      sodium: 105,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 2.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 89,
      isoleucine: 189,
      leucine: 322,
      lysine: 261,
      methionine: 83,
      phenylalanine: 159,
      threonine: 149,
      tryptophan: 46,
      valine: 220,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },

  // FRUITS
  {
    id: "mango-raw",
    name: "Mango (Raw)",
    category: CATEGORIES.FRUITS,
    description: "National fruit of India, used in various dishes, chutneys, and pickles",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 small mango",
    },
    nutrients: {
      calories: 60,
      protein: 0.8,
      carbohydrates: 15.0,
      fat: 0.4,
      fiber: 1.6,
      sugar: 13.7,
      sodium: 2,
    },
    vitamins: {
      a: 765,
      c: 36.4,
      d: 0,
      e: 0.9,
      k: 4.2,
      b1: 0.03,
      b2: 0.04,
      b3: 0.7,
      b5: 0.2,
      b6: 0.12,
      b7: 1.3,
      b9: 43,
      b12: 0,
    },
    minerals: {
      calcium: 11,
      iron: 0.2,
      magnesium: 10,
      phosphorus: 14,
      potassium: 168,
      sodium: 2,
      zinc: 0.1,
      copper: 0.1,
      manganese: 0.1,
      selenium: 0.6,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 18,
      isoleucine: 32,
      leucine: 49,
      lysine: 41,
      methionine: 12,
      phenylalanine: 32,
      threonine: 32,
      tryptophan: 10,
      valine: 37,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "banana-raw",
    name: "Banana (Raw)",
    category: CATEGORIES.FRUITS,
    description: "Common fruit in Indian diet, often offered in temples",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium banana",
    },
    nutrients: {
      calories: 89,
      protein: 1.1,
      carbohydrates: 22.8,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12.2,
      sodium: 1,
    },
    vitamins: {
      a: 64,
      c: 8.7,
      d: 0,
      e: 0.1,
      k: 0.5,
      b1: 0.03,
      b2: 0.07,
      b3: 0.7,
      b5: 0.3,
      b6: 0.37,
      b7: 0.1,
      b9: 20,
      b12: 0,
    },
    minerals: {
      calcium: 5,
      iron: 0.3,
      magnesium: 27,
      phosphorus: 22,
      potassium: 358,
      sodium: 1,
      zinc: 0.2,
      copper: 0.1,
      manganese: 0.3,
      selenium: 1.0,
      fluoride: 2.2,
    },
    aminoAcids: {
      histidine: 24,
      isoleucine: 44,
      leucine: 68,
      lysine: 57,
      methionine: 17,
      phenylalanine: 44,
      threonine: 44,
      tryptophan: 14,
      valine: 51,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "apple-raw",
    name: "Apple (Raw)",
    category: CATEGORIES.FRUITS,
    description: "Common fruit in Indian diet, especially in northern regions",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 small apple",
    },
    nutrients: {
      calories: 52,
      protein: 0.3,
      carbohydrates: 13.8,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10.4,
      sodium: 1,
    },
    vitamins: {
      a: 3,
      c: 4.6,
      d: 0,
      e: 0.2,
      k: 2.2,
      b1: 0.02,
      b2: 0.03,
      b3: 0.1,
      b5: 0.1,
      b6: 0.04,
      b7: 0.1,
      b9: 3,
      b12: 0,
    },
    minerals: {
      calcium: 6,
      iron: 0.1,
      magnesium: 5,
      phosphorus: 11,
      potassium: 107,
      sodium: 1,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 3.3,
    },
    aminoAcids: {
      histidine: 7,
      isoleucine: 12,
      leucine: 18,
      lysine: 15,
      methionine: 4,
      phenylalanine: 12,
      threonine: 12,
      tryptophan: 4,
      valine: 14,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "orange-raw",
    name: "Orange (Raw)",
    category: CATEGORIES.FRUITS,
    description: "Citrus fruit commonly consumed in India",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 small orange",
    },
    nutrients: {
      calories: 47,
      protein: 0.9,
      carbohydrates: 11.8,
      fat: 0.1,
      fiber: 2.4,
      sugar: 9.4,
      sodium: 0,
    },
    vitamins: {
      a: 225,
      c: 53.2,
      d: 0,
      e: 0.2,
      k: 0.0,
      b1: 0.09,
      b2: 0.04,
      b3: 0.4,
      b5: 0.3,
      b6: 0.06,
      b7: 0.1,
      b9: 30,
      b12: 0,
    },
    minerals: {
      calcium: 40,
      iron: 0.1,
      magnesium: 10,
      phosphorus: 14,
      potassium: 181,
      sodium: 0,
      zinc: 0.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.5,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 20,
      isoleucine: 36,
      leucine: 55,
      lysine: 46,
      methionine: 13,
      phenylalanine: 36,
      threonine: 36,
      tryptophan: 12,
      valine: 42,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "guava-raw",
    name: "Guava (Raw)",
    category: CATEGORIES.FRUITS,
    description: "Tropical fruit rich in vitamin C, common in Indian diet",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium guava",
    },
    nutrients: {
      calories: 68,
      protein: 2.6,
      carbohydrates: 14.3,
      fat: 1.0,
      fiber: 5.4,
      sugar: 8.9,
      sodium: 2,
    },
    vitamins: {
      a: 624,
      c: 228.3,
      d: 0,
      e: 0.7,
      k: 2.6,
      b1: 0.07,
      b2: 0.04,
      b3: 1.1,
      b5: 0.5,
      b6: 0.11,
      b7: 1.2,
      b9: 49,
      b12: 0,
    },
    minerals: {
      calcium: 18,
      iron: 0.3,
      magnesium: 22,
      phosphorus: 40,
      potassium: 417,
      sodium: 2,
      zinc: 0.2,
      copper: 0.2,
      manganese: 0.2,
      selenium: 0.6,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 57,
      isoleucine: 104,
      leucine: 160,
      lysine: 134,
      methionine: 39,
      phenylalanine: 104,
      threonine: 104,
      tryptophan: 34,
      valine: 121,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.1,
      polyunsaturated: 0.4,
      omega3: 0.1,
      omega6: 0.3,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "papaya-raw",
    name: "Papaya (Raw)",
    category: CATEGORIES.FRUITS,
    description: "Tropical fruit with digestive properties, common in Indian diet",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup cubes",
    },
    nutrients: {
      calories: 43,
      protein: 0.5,
      carbohydrates: 10.8,
      fat: 0.3,
      fiber: 1.7,
      sugar: 7.8,
      sodium: 8,
    },
    vitamins: {
      a: 950,
      c: 60.9,
      d: 0,
      e: 0.7,
      k: 2.6,
      b1: 0.03,
      b2: 0.03,
      b3: 0.3,
      b5: 0.2,
      b6: 0.02,
      b7: 3.8,
      b9: 37,
      b12: 0,
    },
    minerals: {
      calcium: 20,
      iron: 0.3,
      magnesium: 21,
      phosphorus: 10,
      potassium: 182,
      sodium: 8,
      zinc: 0.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.6,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 11,
      isoleucine: 20,
      leucine: 31,
      lysine: 26,
      methionine: 8,
      phenylalanine: 20,
      threonine: 20,
      tryptophan: 6,
      valine: 23,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },

  // NUTS AND SEEDS
  {
    id: "almonds-raw",
    name: "Almonds (Raw)",
    category: CATEGORIES.NUTS,
    description: "Nutritious nuts used in many Indian sweets and dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3/4 cup",
    },
    nutrients: {
      calories: 579,
      protein: 21.2,
      carbohydrates: 21.7,
      fat: 49.9,
      fiber: 12.5,
      sugar: 4.4,
      sodium: 1,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 25.6,
      k: 0.0,
      b1: 0.21,
      b2: 1.14,
      b3: 3.6,
      b5: 0.5,
      b6: 0.14,
      b7: 0.1,
      b9: 50,
      b12: 0,
    },
    minerals: {
      calcium: 269,
      iron: 3.7,
      magnesium: 270,
      phosphorus: 481,
      potassium: 733,
      sodium: 1,
      zinc: 3.1,
      copper: 1.0,
      manganese: 2.3,
      selenium: 4.1,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 648,
      isoleucine: 883,
      leucine: 1627,
      lysine: 661,
      methionine: 195,
      phenylalanine: 1132,
      threonine: 709,
      tryptophan: 214,
      valine: 1103,
    },
    fattyAcids: {
      saturated: 3.8,
      monounsaturated: 31.6,
      polyunsaturated: 12.3,
      omega3: 0.0,
      omega6: 12.3,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "cashews-raw",
    name: "Cashews (Raw)",
    category: CATEGORIES.NUTS,
    description: "Creamy nuts used in many Indian dishes, especially in curries",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.WEST,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3/4 cup",
    },
    nutrients: {
      calories: 553,
      protein: 18.2,
      carbohydrates: 30.2,
      fat: 43.9,
      fiber: 3.3,
      sugar: 5.9,
      sodium: 12,
    },
    vitamins: {
      a: 0,
      c: 0.5,
      d: 0,
      e: 0.9,
      k: 34.1,
      b1: 0.42,
      b2: 0.06,
      b3: 1.1,
      b5: 0.9,
      b6: 0.42,
      b7: 20.0,
      b9: 25,
      b12: 0,
    },
    minerals: {
      calcium: 37,
      iron: 6.7,
      magnesium: 292,
      phosphorus: 593,
      potassium: 660,
      sodium: 12,
      zinc: 5.8,
      copper: 2.2,
      manganese: 1.7,
      selenium: 19.9,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 455,
      isoleucine: 819,
      leucine: 1470,
      lysine: 910,
      methionine: 364,
      phenylalanine: 910,
      threonine: 637,
      tryptophan: 291,
      valine: 1092,
    },
    fattyAcids: {
      saturated: 8.4,
      monounsaturated: 23.8,
      polyunsaturated: 7.8,
      omega3: 0.2,
      omega6: 7.6,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "peanuts-raw",
    name: "Peanuts (Raw)",
    category: CATEGORIES.NUTS,
    description: "Legumes used as nuts in many Indian dishes and snacks",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3/4 cup",
    },
    nutrients: {
      calories: 567,
      protein: 25.8,
      carbohydrates: 16.1,
      fat: 49.2,
      fiber: 8.5,
      sugar: 4.7,
      sodium: 18,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 8.3,
      k: 0.0,
      b1: 0.64,
      b2: 0.14,
      b3: 12.1,
      b5: 1.8,
      b6: 0.35,
      b7: 34.0,
      b9: 240,
      b12: 0,
    },
    minerals: {
      calcium: 92,
      iron: 4.6,
      magnesium: 168,
      phosphorus: 376,
      potassium: 705,
      sodium: 18,
      zinc: 3.3,
      copper: 1.1,
      manganese: 1.9,
      selenium: 7.2,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 644,
      isoleucine: 896,
      leucine: 1672,
      lysine: 930,
      methionine: 310,
      phenylalanine: 1342,
      threonine: 877,
      tryptophan: 258,
      valine: 1085,
    },
    fattyAcids: {
      saturated: 6.8,
      monounsaturated: 24.4,
      polyunsaturated: 15.6,
      omega3: 0.0,
      omega6: 15.6,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "sesame-seeds-til",
    name: "Sesame Seeds (Til)",
    category: CATEGORIES.NUTS,
    description: "Small seeds used in many Indian dishes and sweets",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3/4 cup",
    },
    nutrients: {
      calories: 573,
      protein: 17.7,
      carbohydrates: 23.4,
      fat: 49.7,
      fiber: 11.8,
      sugar: 0.3,
      sodium: 11,
    },
    vitamins: {
      a: 9,
      c: 0.0,
      d: 0,
      e: 0.3,
      k: 0.0,
      b1: 0.79,
      b2: 0.25,
      b3: 4.5,
      b5: 0.1,
      b6: 0.79,
      b7: 0.1,
      b9: 97,
      b12: 0,
    },
    minerals: {
      calcium: 975,
      iron: 14.6,
      magnesium: 351,
      phosphorus: 629,
      potassium: 468,
      sodium: 11,
      zinc: 7.8,
      copper: 4.1,
      manganese: 2.5,
      selenium: 34.4,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 507,
      isoleucine: 830,
      leucine: 1416,
      lysine: 592,
      methionine: 670,
      phenylalanine: 936,
      threonine: 754,
      tryptophan: 388,
      valine: 1062,
    },
    fattyAcids: {
      saturated: 7.0,
      monounsaturated: 18.8,
      polyunsaturated: 21.8,
      omega3: 0.4,
      omega6: 21.4,
      trans: 0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },

  // OILS AND FATS
  {
    id: "mustard-oil",
    name: "Mustard Oil",
    category: CATEGORIES.OILS,
    description: "Pungent oil used in cooking, especially in Eastern and Northern India",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.EAST,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 884,
      protein: 0.0,
      carbohydrates: 0.0,
      fat: 100.0,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 0,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 17.5,
      k: 5.4,
      b1: 0.0,
      b2: 0.0,
      b3: 0.0,
      b5: 0.0,
      b6: 0.0,
      b7: 0.0,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 0,
      iron: 0.0,
      magnesium: 0,
      phosphorus: 0,
      potassium: 0,
      sodium: 0,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,
    },
    fattyAcids: {
      saturated: 11.6,
      monounsaturated: 59.2,
      polyunsaturated: 21.2,
      omega3: 5.9,
      omega6: 15.3,
      trans: 0.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "coconut-oil",
    name: "Coconut Oil",
    category: CATEGORIES.OILS,
    description: "Oil extracted from coconut, commonly used in South Indian cooking",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 892,
      protein: 0.0,
      carbohydrates: 0.0,
      fat: 100.0,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 0,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 0.1,
      k: 0.6,
      b1: 0.0,
      b2: 0.0,
      b3: 0.0,
      b5: 0.0,
      b6: 0.0,
      b7: 0.0,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 0,
      iron: 0.0,
      magnesium: 0,
      phosphorus: 0,
      potassium: 0,
      sodium: 0,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,
    },
    fattyAcids: {
      saturated: 86.5,
      monounsaturated: 6.0,
      polyunsaturated: 1.8,
      omega3: 0.0,
      omega6: 1.8,
      trans: 0.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "groundnut-oil",
    name: "Groundnut Oil (Peanut Oil)",
    category: CATEGORIES.OILS,
    description: "Oil extracted from peanuts, commonly used in South Indian cooking",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.SOUTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 884,
      protein: 0.0,
      carbohydrates: 0.0,
      fat: 100.0,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 0,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 15.7,
      k: 0.7,
      b1: 0.0,
      b2: 0.0,
      b3: 0.0,
      b5: 0.0,
      b6: 0.0,
      b7: 0.0,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 0,
      iron: 0.0,
      magnesium: 0,
      phosphorus: 0,
      potassium: 0,
      sodium: 0,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,
    },
    fattyAcids: {
      saturated: 16.9,
      monounsaturated: 46.2,
      polyunsaturated: 32.0,
      omega3: 0.0,
      omega6: 32.0,
      trans: 0.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },

  // SWEETS AND DESSERTS
  {
    id: "jalebi",
    name: "Jalebi",
    category: CATEGORIES.SWEETS,
    description: "Deep-fried sweet soaked in sugar syrup, popular across India",
    isVegetarian: true,
    isVegan: false,
    containsGluten: true,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "4 pieces",
    },
    nutrients: {
      calories: 329,
      protein: 3.0,
      carbohydrates: 65.0,
      fat: 7.2,
      fiber: 0.0,
      sugar: 50.0,
      sodium: 10,
    },
    vitamins: {
      a: 0,
      c: 0.0,
      d: 0,
      e: 0.0,
      k: 0.0,
      b1: 0.05,
      b2: 0.03,
      b3: 0.3,
      b5: 0.1,
      b6: 0.0,
      b7: 0.0,
      b9: 5,
      b12: 0,
    },
    minerals: {
      calcium: 20,
      iron: 0.5,
      magnesium: 5,
      phosphorus: 30,
      potassium: 40,
      sodium: 10,
      zinc: 0.2,
      copper: 0.0,
      manganese: 0.1,
      selenium: 2.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 66,
      isoleucine: 120,
      leucine: 185,
      lysine: 155,
      methionine: 45,
      phenylalanine: 120,
      threonine: 120,
      tryptophan: 39,
      valine: 140,
    },
    fattyAcids: {
      saturated: 3.5,
      monounsaturated: 2.0,
      polyunsaturated: 1.0,
      omega3: 0.0,
      omega6: 1.0,
      trans: 0.5,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    category: CATEGORIES.SWEETS,
    description: "Deep-fried milk solids soaked in sugar syrup, popular across India",
    isVegetarian: true,
    isVegan: false,
    containsGluten: true,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "2 pieces",
    },
    nutrients: {
      calories: 329,
      protein: 5.0,
      carbohydrates: 58.0,
      fat: 10.0,
      fiber: 0.0,
      sugar: 40.0,
      sodium: 50,
    },
    vitamins: {
      a: 50,
      c: 0.0,
      d: 0.1,
      e: 0.1,
      k: 0.1,
      b1: 0.03,
      b2: 0.15,
      b3: 0.1,
      b5: 0.3,
      b6: 0.03,
      b7: 1.0,
      b9: 5,
      b12: 0.2,
    },
    minerals: {
      calcium: 120,
      iron: 0.2,
      magnesium: 10,
      phosphorus: 80,
      potassium: 150,
      sodium: 50,
      zinc: 0.5,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 110,
      isoleucine: 200,
      leucine: 340,
      lysine: 275,
      methionine: 88,
      phenylalanine: 168,
      threonine: 157,
      tryptophan: 49,
      valine: 233,
    },
    fattyAcids: {
      saturated: 6.0,
      monounsaturated: 2.5,
      polyunsaturated: 0.5,
      omega3: 0.1,
      omega6: 0.4,
      trans: 1.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "rasgulla",
    name: "Rasgulla",
    category: CATEGORIES.SWEETS,
    description: "Spongy milk balls soaked in sugar syrup, popular in Eastern India",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.EAST,
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "2 pieces",
    },
    nutrients: {
      calories: 186,
      protein: 4.0,
      carbohydrates: 38.0,
      fat: 1.0,
      fiber: 0.0,
      sugar: 35.0,
      sodium: 30,
    },
    vitamins: {
      a: 40,
      c: 0.0,
      d: 0.1,
      e: 0.0,
      k: 0.0,
      b1: 0.03,
      b2: 0.15,
      b3: 0.1,
      b5: 0.3,
      b6: 0.03,
      b7: 1.0,
      b9: 5,
      b12: 0.2,
    },
    minerals: {
      calcium: 100,
      iron: 0.1,
      magnesium: 10,
      phosphorus: 80,
      potassium: 130,
      sodium: 30,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 88,
      isoleucine: 160,
      leucine: 272,
      lysine: 220,
      methionine: 70,
      phenylalanine: 134,
      threonine: 126,
      tryptophan: 39,
      valine: 186,
    },
    fattyAcids: {
      saturated: 0.6,
      monounsaturated: 0.3,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0.1,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
]

// Generate keywords for each food item
indianFoods.forEach((food) => {
  food.keywords = generateKeywords(food)
})

// Create a large array of Indian recipes
const indianRecipes: Recipe[] = [
  {
    id: "dal-tadka",
    name: "Dal Tadka",
    category: CATEGORIES.MAIN_COURSE,
    description: "Yellow lentils tempered with spices, a staple in North Indian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    ingredients: [
      {
        name: "Toor Dal (Split Pigeon Peas)",
        amount: 1,
        unit: "cup",
      },
      {
        name: "Turmeric Powder",
        amount: 0.5,
        unit: "tsp",
      },
      {
        name: "Salt",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Ghee",
        amount: 2,
        unit: "tbsp",
      },
      {
        name: "Cumin Seeds",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Asafoetida",
        amount: 0.25,
        unit: "tsp",
      },
      {
        name: "Dried Red Chillies",
        amount: 2,
        unit: "whole",
      },
      {
        name: "Garlic",
        amount: 4,
        unit: "cloves",
        notes: "finely chopped",
      },
      {
        name: "Ginger",
        amount: 1,
        unit: "inch",
        notes: "finely chopped",
      },
      {
        name: "Green Chillies",
        amount: 2,
        unit: "whole",
        notes: "slit",
      },
      {
        name: "Onion",
        amount: 1,
        unit: "medium",
        notes: "finely chopped",
      },
      {
        name: "Tomato",
        amount: 1,
        unit: "medium",
        notes: "finely chopped",
      },
      {
        name: "Red Chilli Powder",
        amount: 0.5,
        unit: "tsp",
      },
      {
        name: "Coriander Powder",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Garam Masala",
        amount: 0.5,
        unit: "tsp",
      },
      {
        name: "Lemon Juice",
        amount: 1,
        unit: "tbsp",
      },
      {
        name: "Coriander Leaves",
        amount: 2,
        unit: "tbsp",
        notes: "chopped",
      },
    ],
    instructions: [
      "Wash the toor dal thoroughly and soak for 30 minutes.",
      "In a pressure cooker, add the soaked dal, 3 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles or until the dal is soft and cooked.",
      "Once the pressure releases, mash the dal lightly with a ladle and keep aside.",
      "Heat ghee in a pan. Add cumin seeds and let them splutter.",
      "Add asafoetida and dried red chillies. Sauté for a few seconds.",
      "Add chopped garlic, ginger, and green chillies. Sauté until the raw smell disappears.",
      "Add chopped onions and sauté until they turn translucent.",
      "Add chopped tomatoes, red chilli powder, coriander powder, and salt. Cook until the tomatoes are soft and the oil starts to separate.",
      "Pour this tempering over the cooked dal and mix well.",
      "Add garam masala and lemon juice. Mix well and simmer for 2-3 minutes.",
      "Garnish with chopped coriander leaves and serve hot with rice or roti.",
    ],
    nutrients: {
      calories: 220,
      protein: 12.0,
      carbohydrates: 30.0,
      fat: 7.0,
      fiber: 8.0,
      sugar: 3.0,
      sodium: 600,
    },
    vitamins: {
      a: 200,
      c: 15.0,
      d: 0,
      e: 1.0,
      k: 10.0,
      b1: 0.3,
      b2: 0.1,
      b3: 2.0,
      b5: 0.7,
      b6: 0.3,
      b7: 5.0,
      b9: 80,
      b12: 0,
    },
    minerals: {
      calcium: 60,
      iron: 4.0,
      magnesium: 80,
      phosphorus: 200,
      potassium: 500,
      sodium: 600,
      zinc: 2.0,
      copper: 0.5,
      manganese: 0.8,
      selenium: 5.0,
      fluoride: 5.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken (Murgh Makhani)",
    category: CATEGORIES.MAIN_COURSE,
    description: "Creamy tomato-based curry with tender chicken pieces, popular in North India",
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    ingredients: [
      {
        name: "Chicken",
        amount: 500,
        unit: "g",
        notes: "boneless, cut into pieces",
      },
      {
        name: "Yogurt",
        amount: 0.5,
        unit: "cup",
      },
      {
        name: "Lemon Juice",
        amount: 1,
        unit: "tbsp",
      },
      {
        name: "Ginger Paste",
        amount: 1,
        unit: "tbsp",
      },
      {
        name: "Garlic Paste",
        amount: 1,
        unit: "tbsp",
      },
      {
        name: "Red Chilli Powder",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Garam Masala",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Salt",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Butter",
        amount: 2,
        unit: "tbsp",
      },
      {
        name: "Oil",
        amount: 1,
        unit: "tbsp",
      },
      {
        name: "Onion",
        amount: 1,
        unit: "large",
        notes: "finely chopped",
      },
      {
        name: "Tomatoes",
        amount: 3,
        unit: "medium",
        notes: "pureed",
      },
      {
        name: "Cashew Nuts",
        amount: 15,
        unit: "whole",
        notes: "soaked and ground to paste",
      },
      {
        name: "Cream",
        amount: 0.25,
        unit: "cup",
      },
      {
        name: "Kasuri Methi (Dried Fenugreek Leaves)",
        amount: 1,
        unit: "tbsp",
        notes: "crushed",
      },
      {
        name: "Honey",
        amount: 1,
        unit: "tsp",
      },
    ],
    instructions: [
      "In a bowl, mix yogurt, lemon juice, ginger paste, garlic paste, red chilli powder, garam masala, and salt.",
      "Add chicken pieces to the marinade and refrigerate for at least 2 hours, preferably overnight.",
      "Heat butter and oil in a pan. Add chopped onions and sauté until golden brown.",
      "Add tomato puree and cook until the oil separates.",
      "Add cashew paste and cook for another 2-3 minutes.",
      "Add the marinated chicken pieces and cook on high heat for 5 minutes.",
      "Reduce heat, cover, and simmer for 15-20 minutes until the chicken is cooked through.",
      "Add cream, kasuri methi, and honey. Mix well and simmer for another 5 minutes.",
      "Adjust salt and spices according to taste.",
      "Serve hot with naan or rice.",
    ],
    nutrients: {
      calories: 450,
      protein: 30.0,
      carbohydrates: 15.0,
      fat: 32.0,
      fiber: 2.0,
      sugar: 8.0,
      sodium: 800,
    },
    vitamins: {
      a: 500,
      c: 20.0,
      d: 0.1,
      e: 2.0,
      k: 15.0,
      b1: 0.2,
      b2: 0.3,
      b3: 10.0,
      b5: 1.5,
      b6: 0.8,
      b7: 10.0,
      b9: 40,
      b12: 0.5,
    },
    minerals: {
      calcium: 100,
      iron: 3.0,
      magnesium: 50,
      phosphorus: 250,
      potassium: 600,
      sodium: 800,
      zinc: 2.5,
      copper: 0.3,
      manganese: 0.5,
      selenium: 20.0,
      fluoride: 5.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    category: CATEGORIES.MAIN_COURSE,
    description: "Cottage cheese cubes in a creamy spinach gravy, popular in North India",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: REGIONS.NORTH,
    cuisine: "Indian",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    ingredients: [
      {
        name: "Spinach (Palak)",
        amount: 500,
        unit: "g",
      },
      {
        name: "Paneer",
        amount: 250,
        unit: "g",
        notes: "cut into cubes",
      },
      {
        name: "Onion",
        amount: 1,
        unit: "medium",
        notes: "finely chopped",
      },
      {
        name: "Tomato",
        amount: 1,
        unit: "medium",
        notes: "finely chopped",
      },
      {
        name: "Ginger",
        amount: 1,
        unit: "inch",
        notes: "finely chopped",
      },
      {
        name: "Garlic",
        amount: 4,
        unit: "cloves",
        notes: "finely chopped",
      },
      {
        name: "Green Chillies",
        amount: 2,
        unit: "whole",
        notes: "slit",
      },
      {
        name: "Cumin Seeds",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Turmeric Powder",
        amount: 0.5,
        unit: "tsp",
      },
      {
        name: "Red Chilli Powder",
        amount: 0.5,
        unit: "tsp",
      },
      {
        name: "Coriander Powder",
        amount: 1,
        unit: "tsp",
      },
      {
        name: "Garam Masala",
        amount: 0.5,
        unit: "tsp",
      },
      {
        name: "Cream",
        amount: 2,
        unit: "tbsp",
      },
      {
        name: "Butter",
        amount: 2,
        unit: "tbsp",
      },
      {
        name: "Oil",
        amount: 1,
        unit: "tbsp",
      },
      {
        name: "Salt",
        amount: 1,
        unit: "tsp",
      },
    ],
    instructions: [
      "Blanch the spinach in boiling water for 2-3 minutes. Drain and immediately transfer to cold water.",
      "Blend the blanched spinach into a smooth puree and keep aside.",
      "Heat oil and butter in a pan. Add cumin seeds and let them splutter.",
      "Add chopped onions and sauté until golden brown.",
      "Add chopped ginger, garlic, and green chillies. Sauté until the raw smell disappears.",
      "Add chopped tomatoes and cook until they are soft and the oil starts to separate.",
      "Add turmeric powder, red chilli powder, coriander powder, and salt. Mix well and cook for 1-2 minutes.",
      "Add the spinach puree and mix well. Cook for 5 minutes on medium heat.",
      "Add paneer cubes and garam masala. Mix gently and cook for another 5 minutes.",
      "Add cream and mix well. Simmer for 2-3 minutes.",
      "Serve hot with roti or naan.",
    ],
    nutrients: {
      calories: 300,
      protein: 15.0,
      carbohydrates: 10.0,
      fat: 22.0,
      fiber: 4.0,
      sugar: 3.0,
      sodium: 600,
    },
    vitamins: {
      a: 5000,
      c: 30.0,
      d: 0.1,
      e: 2.0,
      k: 200.0,
      b1: 0.2,
      b2: 0.3,
      b3: 1.0,
      b5: 0.7,
      b6: 0.3,
      b7: 5.0,
      b9: 100,
      b12: 0.3,
    },
    minerals: {
      calcium: 300,
      iron: 4.0,
      magnesium: 80,
      phosphorus: 200,
      potassium: 500,
      sodium: 600,
      zinc: 1.5,
      copper: 0.3,
      manganese: 1.0,
      selenium: 5.0,
      fluoride: 5.0,
    },
    keywords: [],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
]

// Generate keywords for each recipe
indianRecipes.forEach((recipe) => {
  recipe.keywords = generateKeywords(recipe)
})

// Function to upload food items to Firestore
async function uploadFoodsToFirestore(foods: DetailedFoodItem[]) {
  console.log(`Starting upload of ${foods.length} food items to Firestore...`)

  const batchSize = 500
  const batches = Math.ceil(foods.length / batchSize)

  for (let i = 0; i < batches; i++) {
    const start = i * batchSize
    const end = Math.min(start + batchSize, foods.length)
    const batch = foods.slice(start, end)

    console.log(`Processing batch ${i + 1}/${batches} (${batch.length} items)...`)

    const promises = batch.map(async (food) => {
      try {
        const docRef = db.collection("ifct_foods").doc(food.id)
        await docRef.set(food)
        return { success: true, id: food.id }
      } catch (error) {
        console.error(`Error uploading food item ${food.id}:`, error)
        return { success: false, id: food.id, error }
      }
    })

    const results = await Promise.all(promises)
    const successful = results.filter((r) => r.success).length
    const failed = results.filter((r) => !r.success).length

    console.log(`Batch ${i + 1} completed: ${successful} successful, ${failed} failed`)
  }

  console.log(`Finished uploading food items to Firestore.`)
}

// Function to upload recipes to Firestore
async function uploadRecipesToFirestore(recipes: Recipe[]) {
  console.log(`Starting upload of ${recipes.length} recipes to Firestore...`)

  const batchSize = 500
  const batches = Math.ceil(recipes.length / batchSize)

  for (let i = 0; i < batches; i++) {
    const start = i * batchSize
    const end = Math.min(start + batchSize, recipes.length)
    const batch = recipes.slice(start, end)

    console.log(`Processing batch ${i + 1}/${batches} (${batch.length} items)...`)

    const promises = batch.map(async (recipe) => {
      try {
        const docRef = db.collection("recipes").doc(recipe.id)
        await docRef.set(recipe)
        return { success: true, id: recipe.id }
      } catch (error) {
        console.error(`Error uploading recipe ${recipe.id}:`, error)
        return { success: false, id: recipe.id, error }
      }
    })

    const results = await Promise.all(promises)
    const successful = results.filter((r) => r.success).length
    const failed = results.filter((r) => !r.success).length

    console.log(`Batch ${i + 1} completed: ${successful} successful, ${failed} failed`)
  }

  console.log(`Finished uploading recipes to Firestore.`)
}

// Main function to run the script
async function main() {
  try {
    console.log("Starting Indian food database population script...")

    // Upload food items
    await uploadFoodsToFirestore(indianFoods)

    // Upload recipes
    await uploadRecipesToFirestore(indianRecipes)

    console.log("Script completed successfully!")
  } catch (error) {
    console.error("Error running script:", error)
  }
}

// Run the script
main()
