/**
 * Expanded Food Database Population Script
 *
 * This script populates the Firestore database with 200+ food items containing
 * comprehensive nutritional data including macronutrients, vitamins, minerals,
 * amino acids, and fatty acids.
 *
 * Usage:
 * 1. Set up your Firebase credentials in your environment
 * 2. Run this script with: npx ts-node scripts/populate-expanded-food-database.ts
 */

import { initializeApp, cert } from "firebase-admin/app"
import { getFirestore } from "firebase-admin/firestore"

// Initialize Firebase Admin
const serviceAccount = process.env.FIREBASE_PRIVATE_KEY
  ? {
      projectId: process.env.FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, "\n"),
    }
  : require("../serviceAccountKey.json")

initializeApp({
  credential: cert(serviceAccount as any),
})

const db = getFirestore()

// Define the food item interface with detailed nutritional information
interface DetailedFoodItem {
  id: string
  name: string
  category: string
  description?: string
  isVegetarian: boolean
  isVegan: boolean
  containsGluten?: boolean
  containsOnionGarlic?: boolean
  containsRootVegetables?: boolean
  source: "ifct" | "usda" | "custom"
  region?: string
  cuisine?: string
  standardPortion: {
    amount: number
    unit: string
    description?: string
  }
  nutrients: {
    calories: number
    protein: number
    carbohydrates: number
    fat: number
    fiber: number
    sugar: number
    sodium: number
  }
  vitamins?: {
    a: number // IU
    c: number // mg
    d: number // IU
    e: number // mg
    k: number // mcg
    b1: number // mg (Thiamine)
    b2: number // mg (Riboflavin)
    b3: number // mg (Niacin)
    b5: number // mg (Pantothenic Acid)
    b6: number // mg (Pyridoxine)
    b7: number // mcg (Biotin)
    b9: number // mcg (Folate)
    b12: number // mcg (Cobalamin)
  }
  minerals?: {
    calcium: number // mg
    iron: number // mg
    magnesium: number // mg
    phosphorus: number // mg
    potassium: number // mg
    sodium: number // mg
    zinc: number // mg
    copper: number // mg
    manganese: number // mg
    selenium: number // mcg
    fluoride: number // mg
  }
  aminoAcids?: {
    histidine: number // mg
    isoleucine: number // mg
    leucine: number // mg
    lysine: number // mg
    methionine: number // mg
    phenylalanine: number // mg
    threonine: number // mg
    tryptophan: number // mg
    valine: number // mg
  }
  fattyAcids?: {
    saturated: number // g
    monounsaturated: number // g
    polyunsaturated: number // g
    omega3: number // g
    omega6: number // g
    trans: number // g
  }
  keywords: string[]
  createdAt: string
  updatedAt: string
}

// Generate keywords for better searching
function generateKeywords(food: DetailedFoodItem): string[] {
  const keywords = new Set<string>()

  // Add name words
  food.name
    .toLowerCase()
    .split(/\s+/)
    .forEach((word) => {
      if (word.length > 2) keywords.add(word)
    })

  // Add category
  keywords.add(food.category.toLowerCase())

  // Add region if available
  if (food.region) {
    keywords.add(food.region.toLowerCase())
  }

  // Add cuisine if available
  if (food.cuisine) {
    keywords.add(food.cuisine.toLowerCase())
  }

  // Add dietary keywords
  if (food.isVegetarian) keywords.add("vegetarian")
  if (food.isVegan) keywords.add("vegan")
  if (food.containsGluten === false) keywords.add("gluten-free")
  if (food.containsOnionGarlic === false) keywords.add("no-onion-garlic")

  return Array.from(keywords)
}

// Comprehensive food database with detailed nutritional information
const expandedFoods: DetailedFoodItem[] = [
  // GRAINS AND CEREALS
  {
    id: "rice-white-cooked",
    name: "White Rice (Cooked)",
    category: "Grains",
    description: "Plain cooked white rice, a staple in many cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 130,
      protein: 2.7,
      carbohydrates: 28.2,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0.1,
      sodium: 1,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0,
      b1: 0.02,
      b2: 0.01,
      b3: 0.4,
      b5: 0.4,
      b6: 0.05,
      b7: 0.6,
      b9: 2,
      b12: 0,
    },
    minerals: {
      calcium: 10,
      iron: 0.2,
      magnesium: 12,
      phosphorus: 43,
      potassium: 35,
      sodium: 1,
      zinc: 0.8,
      copper: 0.1,
      manganese: 0.5,
      selenium: 7.5,
      fluoride: 8.4,
    },
    aminoAcids: {
      histidine: 59,
      isoleucine: 111,
      leucine: 202,
      lysine: 92,
      methionine: 58,
      phenylalanine: 129,
      threonine: 89,
      tryptophan: 31,
      valine: 150,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.01,
      omega6: 0.09,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rice-brown-cooked",
    name: "Brown Rice (Cooked)",
    category: "Grains",
    description: "Whole grain brown rice with bran layer intact, providing more fiber and nutrients",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 112,
      protein: 2.6,
      carbohydrates: 23.5,
      fat: 0.9,
      fiber: 1.8,
      sugar: 0.4,
      sodium: 5,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.5,
      k: 1.2,
      b1: 0.1,
      b2: 0.05,
      b3: 2.6,
      b5: 0.6,
      b6: 0.15,
      b7: 0.9,
      b9: 8,
      b12: 0,
    },
    minerals: {
      calcium: 10,
      iron: 0.5,
      magnesium: 44,
      phosphorus: 83,
      potassium: 79,
      sodium: 5,
      zinc: 0.6,
      copper: 0.1,
      manganese: 1.1,
      selenium: 9.8,
      fluoride: 8.4,
    },
    aminoAcids: {
      histidine: 63,
      isoleucine: 110,
      leucine: 216,
      lysine: 97,
      methionine: 55,
      phenylalanine: 134,
      threonine: 95,
      tryptophan: 33,
      valine: 159,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.3,
      polyunsaturated: 0.3,
      omega3: 0.03,
      omega6: 0.27,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rice-basmati-cooked",
    name: "Basmati Rice (Cooked)",
    category: "Grains",
    description: "Aromatic long-grain rice commonly used in Indian and Middle Eastern cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 121,
      protein: 3.1,
      carbohydrates: 25.2,
      fat: 0.4,
      fiber: 0.6,
      sugar: 0.1,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0.1,
      b1: 0.03,
      b2: 0.02,
      b3: 0.5,
      b5: 0.4,
      b6: 0.06,
      b7: 0.7,
      b9: 3,
      b12: 0,
    },
    minerals: {
      calcium: 12,
      iron: 0.3,
      magnesium: 15,
      phosphorus: 48,
      potassium: 42,
      sodium: 2,
      zinc: 0.9,
      copper: 0.1,
      manganese: 0.6,
      selenium: 8.2,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 65,
      isoleucine: 115,
      leucine: 210,
      lysine: 95,
      methionine: 60,
      phenylalanine: 135,
      threonine: 92,
      tryptophan: 32,
      valine: 155,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.01,
      omega6: 0.09,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rice-jasmine-cooked",
    name: "Jasmine Rice (Cooked)",
    category: "Grains",
    description: "Fragrant long-grain rice commonly used in Southeast Asian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Southeast Asia",
    cuisine: "Thai",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 117,
      protein: 2.4,
      carbohydrates: 25.8,
      fat: 0.2,
      fiber: 0.3,
      sugar: 0.1,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0,
      b1: 0.02,
      b2: 0.01,
      b3: 0.4,
      b5: 0.3,
      b6: 0.04,
      b7: 0.6,
      b9: 2,
      b12: 0,
    },
    minerals: {
      calcium: 8,
      iron: 0.2,
      magnesium: 10,
      phosphorus: 40,
      potassium: 30,
      sodium: 2,
      zinc: 0.7,
      copper: 0.1,
      manganese: 0.4,
      selenium: 7.0,
      fluoride: 7.5,
    },
    aminoAcids: {
      histidine: 55,
      isoleucine: 105,
      leucine: 195,
      lysine: 88,
      methionine: 55,
      phenylalanine: 125,
      threonine: 85,
      tryptophan: 30,
      valine: 145,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.01,
      omega6: 0.09,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wheat-chapati",
    name: "Whole Wheat Chapati",
    category: "Bread",
    description: "Traditional Indian flatbread made from whole wheat flour",
    isVegetarian: true,
    isVegan: true,
    containsGluten: true,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 30,
      unit: "g",
      description: "1 medium chapati",
    },
    nutrients: {
      calories: 85,
      protein: 3.1,
      carbohydrates: 17.2,
      fat: 0.4,
      fiber: 2.8,
      sugar: 0.2,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 0.9,
      b1: 0.08,
      b2: 0.06,
      b3: 0.9,
      b5: 0.2,
      b6: 0.09,
      b7: 1.5,
      b9: 14,
      b12: 0,
    },
    minerals: {
      calcium: 15,
      iron: 0.8,
      magnesium: 29,
      phosphorus: 82,
      potassium: 108,
      sodium: 2,
      zinc: 0.7,
      copper: 0.1,
      manganese: 0.8,
      selenium: 15.1,
      fluoride: 4.2,
    },
    aminoAcids: {
      histidine: 65,
      isoleucine: 126,
      leucine: 226,
      lysine: 86,
      methionine: 53,
      phenylalanine: 159,
      threonine: 94,
      tryptophan: 39,
      valine: 142,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.02,
      omega6: 0.18,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wheat-paratha",
    name: "Whole Wheat Paratha",
    category: "Bread",
    description: "Layered Indian flatbread made from whole wheat flour and ghee",
    isVegetarian: true,
    isVegan: false,
    containsGluten: true,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 60,
      unit: "g",
      description: "1 medium paratha",
    },
    nutrients: {
      calories: 180,
      protein: 4.2,
      carbohydrates: 25.8,
      fat: 7.2,
      fiber: 3.1,
      sugar: 0.3,
      sodium: 3,
    },
    vitamins: {
      a: 42,
      c: 0,
      d: 0.2,
      e: 0.3,
      k: 1.2,
      b1: 0.1,
      b2: 0.08,
      b3: 1.2,
      b5: 0.3,
      b6: 0.12,
      b7: 1.8,
      b9: 18,
      b12: 0.1,
    },
    minerals: {
      calcium: 20,
      iron: 1.1,
      magnesium: 35,
      phosphorus: 95,
      potassium: 125,
      sodium: 3,
      zinc: 0.9,
      copper: 0.15,
      manganese: 1.0,
      selenium: 18.5,
      fluoride: 5.0,
    },
    aminoAcids: {
      histidine: 85,
      isoleucine: 155,
      leucine: 275,
      lysine: 105,
      methionine: 65,
      phenylalanine: 195,
      threonine: 115,
      tryptophan: 48,
      valine: 175,
    },
    fattyAcids: {
      saturated: 3.5,
      monounsaturated: 2.2,
      polyunsaturated: 0.8,
      omega3: 0.05,
      omega6: 0.75,
      trans: 0.2,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wheat-naan",
    name: "Naan Bread",
    category: "Bread",
    description: "Leavened, oven-baked flatbread found in Indian cuisine",
    isVegetarian: true,
    isVegan: false,
    containsGluten: true,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 80,
      unit: "g",
      description: "1 medium naan",
    },
    nutrients: {
      calories: 210,
      protein: 7.5,
      carbohydrates: 33.8,
      fat: 5.2,
      fiber: 1.8,
      sugar: 1.2,
      sodium: 320,
    },
    vitamins: {
      a: 18,
      c: 0,
      d: 0.1,
      e: 0.2,
      k: 0.8,
      b1: 0.25,
      b2: 0.15,
      b3: 1.8,
      b5: 0.4,
      b6: 0.08,
      b7: 1.2,
      b9: 85,
      b12: 0.1,
    },
    minerals: {
      calcium: 65,
      iron: 1.5,
      magnesium: 25,
      phosphorus: 75,
      potassium: 95,
      sodium: 320,
      zinc: 0.6,
      copper: 0.12,
      manganese: 0.6,
      selenium: 22.5,
      fluoride: 4.8,
    },
    aminoAcids: {
      histidine: 175,
      isoleucine: 285,
      leucine: 525,
      lysine: 175,
      methionine: 125,
      phenylalanine: 365,
      threonine: 215,
      tryptophan: 95,
      valine: 325,
    },
    fattyAcids: {
      saturated: 1.2,
      monounsaturated: 1.8,
      polyunsaturated: 1.5,
      omega3: 0.1,
      omega6: 1.4,
      trans: 0.1,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "oats-cooked",
    name: "Oatmeal (Cooked)",
    category: "Grains",
    description: "Cooked rolled oats, a nutritious breakfast cereal",
    isVegetarian: true,
    isVegan: true,
    containsGluten: true,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 71,
      protein: 2.5,
      carbohydrates: 12.0,
      fat: 1.5,
      fiber: 2.0,
      sugar: 0.5,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 0.3,
      b1: 0.15,
      b2: 0.05,
      b3: 0.3,
      b5: 0.4,
      b6: 0.05,
      b7: 10.0,
      b9: 14,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 1.0,
      magnesium: 28,
      phosphorus: 99,
      potassium: 100,
      sodium: 2,
      zinc: 0.8,
      copper: 0.1,
      manganese: 0.8,
      selenium: 10.0,
      fluoride: 5.0,
    },
    aminoAcids: {
      histidine: 52,
      isoleucine: 94,
      leucine: 168,
      lysine: 93,
      methionine: 38,
      phenylalanine: 115,
      threonine: 75,
      tryptophan: 33,
      valine: 125,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.4,
      polyunsaturated: 0.6,
      omega3: 0.03,
      omega6: 0.57,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "quinoa-cooked",
    name: "Quinoa (Cooked)",
    category: "Grains",
    description: "Cooked quinoa, a protein-rich pseudocereal",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 120,
      protein: 4.4,
      carbohydrates: 21.3,
      fat: 1.9,
      fiber: 2.8,
      sugar: 0.9,
      sodium: 7,
    },
    vitamins: {
      a: 5,
      c: 0,
      d: 0,
      e: 0.6,
      k: 0,
      b1: 0.11,
      b2: 0.11,
      b3: 0.4,
      b5: 0.8,
      b6: 0.12,
      b7: 2.0,
      b9: 42,
      b12: 0,
    },
    minerals: {
      calcium: 17,
      iron: 1.5,
      magnesium: 64,
      phosphorus: 152,
      potassium: 172,
      sodium: 7,
      zinc: 1.1,
      copper: 0.2,
      manganese: 0.6,
      selenium: 2.8,
      fluoride: 6.0,
    },
    aminoAcids: {
      histidine: 95,
      isoleucine: 155,
      leucine: 260,
      lysine: 235,
      methionine: 75,
      phenylalanine: 170,
      threonine: 130,
      tryptophan: 50,
      valine: 170,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.5,
      polyunsaturated: 1.0,
      omega3: 0.1,
      omega6: 0.9,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "millet-cooked",
    name: "Millet (Cooked)",
    category: "Grains",
    description: "Cooked millet, a gluten-free grain common in Indian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 119,
      protein: 3.5,
      carbohydrates: 23.7,
      fat: 1.0,
      fiber: 1.3,
      sugar: 0.2,
      sodium: 3,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0.3,
      b1: 0.13,
      b2: 0.11,
      b3: 1.3,
      b5: 0.2,
      b6: 0.11,
      b7: 0.9,
      b9: 19,
      b12: 0,
    },
    minerals: {
      calcium: 8,
      iron: 1.1,
      magnesium: 44,
      phosphorus: 100,
      potassium: 62,
      sodium: 3,
      zinc: 0.9,
      copper: 0.1,
      manganese: 0.6,
      selenium: 2.8,
      fluoride: 4.0,
    },
    aminoAcids: {
      histidine: 75,
      isoleucine: 145,
      leucine: 310,
      lysine: 95,
      methionine: 65,
      phenylalanine: 170,
      threonine: 120,
      tryptophan: 50,
      valine: 180,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.2,
      polyunsaturated: 0.5,
      omega3: 0.03,
      omega6: 0.47,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ragi-flour",
    name: "Ragi Flour (Finger Millet)",
    category: "Grains",
    description: "Flour made from finger millet, rich in calcium and common in South Indian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup",
    },
    nutrients: {
      calories: 348,
      protein: 7.3,
      carbohydrates: 72.6,
      fat: 1.3,
      fiber: 3.6,
      sugar: 0.5,
      sodium: 4,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 0.5,
      b1: 0.42,
      b2: 0.19,
      b3: 1.3,
      b5: 0.3,
      b6: 0.38,
      b7: 1.2,
      b9: 18,
      b12: 0,
    },
    minerals: {
      calcium: 344,
      iron: 3.9,
      magnesium: 137,
      phosphorus: 283,
      potassium: 408,
      sodium: 4,
      zinc: 2.3,
      copper: 0.5,
      manganese: 5.5,
      selenium: 2.5,
      fluoride: 5.0,
    },
    aminoAcids: {
      histidine: 150,
      isoleucine: 275,
      leucine: 590,
      lysine: 180,
      methionine: 190,
      phenylalanine: 325,
      threonine: 270,
      tryptophan: 120,
      valine: 390,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.2,
      polyunsaturated: 0.6,
      omega3: 0.05,
      omega6: 0.55,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "jowar-flour",
    name: "Jowar Flour (Sorghum)",
    category: "Grains",
    description: "Flour made from sorghum, a gluten-free grain common in Indian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup",
    },
    nutrients: {
      calories: 349,
      protein: 10.4,
      carbohydrates: 72.1,
      fat: 3.1,
      fiber: 6.7,
      sugar: 0.0,
      sodium: 6,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.5,
      k: 0.3,
      b1: 0.24,
      b2: 0.14,
      b3: 2.9,
      b5: 1.3,
      b6: 0.44,
      b7: 1.5,
      b9: 20,
      b12: 0,
    },
    minerals: {
      calcium: 28,
      iron: 4.4,
      magnesium: 165,
      phosphorus: 287,
      potassium: 350,
      sodium: 6,
      zinc: 1.7,
      copper: 0.4,
      manganese: 1.6,
      selenium: 12.0,
      fluoride: 4.5,
    },
    aminoAcids: {
      histidine: 230,
      isoleucine: 390,
      leucine: 1290,
      lysine: 230,
      methionine: 170,
      phenylalanine: 490,
      threonine: 320,
      tryptophan: 120,
      valine: 510,
    },
    fattyAcids: {
      saturated: 0.5,
      monounsaturated: 0.9,
      polyunsaturated: 1.4,
      omega3: 0.08,
      omega6: 1.32,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // LEGUMES
  {
    id: "lentils-red-cooked",
    name: "Red Lentils (Cooked)",
    category: "Legumes",
    description: "Cooked red lentils, commonly used in Indian dal preparations",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 116,
      protein: 9.0,
      carbohydrates: 20.1,
      fat: 0.4,
      fiber: 7.9,
      sugar: 1.8,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 1.5,
      d: 0,
      e: 0.1,
      k: 1.7,
      b1: 0.17,
      b2: 0.07,
      b3: 1.1,
      b5: 0.6,
      b6: 0.18,
      b7: 2.1,
      b9: 181,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 3.3,
      magnesium: 36,
      phosphorus: 180,
      potassium: 369,
      sodium: 2,
      zinc: 1.3,
      copper: 0.3,
      manganese: 0.5,
      selenium: 2.8,
      fluoride: 9.0,
    },
    aminoAcids: {
      histidine: 207,
      isoleucine: 382,
      leucine: 621,
      lysine: 593,
      methionine: 77,
      phenylalanine: 427,
      threonine: 306,
      tryptophan: 77,
      valine: 437,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.03,
      omega6: 0.17,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lentils-green-cooked",
    name: "Green Lentils (Cooked)",
    category: "Legumes",
    description: "Cooked green lentils, which hold their shape well after cooking",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 115,
      protein: 9.0,
      carbohydrates: 20.0,
      fat: 0.4,
      fiber: 8.0,
      sugar: 1.8,
      sodium: 2,
    },
    vitamins: {
      a: 2,
      c: 1.5,
      d: 0,
      e: 0.1,
      k: 2.0,
      b1: 0.17,
      b2: 0.07,
      b3: 1.1,
      b5: 0.6,
      b6: 0.18,
      b7: 2.1,
      b9: 180,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 3.3,
      magnesium: 36,
      phosphorus: 180,
      potassium: 370,
      sodium: 2,
      zinc: 1.3,
      copper: 0.3,
      manganese: 0.5,
      selenium: 2.8,
      fluoride: 9.0,
    },
    aminoAcids: {
      histidine: 207,
      isoleucine: 382,
      leucine: 621,
      lysine: 593,
      methionine: 77,
      phenylalanine: 427,
      threonine: 306,
      tryptophan: 77,
      valine: 437,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.03,
      omega6: 0.17,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lentils-black-cooked",
    name: "Black Lentils (Cooked)",
    category: "Legumes",
    description: "Cooked black lentils (urad dal), commonly used in Indian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 116,
      protein: 9.0,
      carbohydrates: 20.1,
      fat: 0.4,
      fiber: 7.9,
      sugar: 1.8,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 1.5,
      d: 0,
      e: 0.1,
      k: 1.7,
      b1: 0.17,
      b2: 0.07,
      b3: 1.1,
      b5: 0.6,
      b6: 0.18,
      b7: 2.1,
      b9: 181,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 3.3,
      magnesium: 36,
      phosphorus: 180,
      potassium: 369,
      sodium: 2,
      zinc: 1.3,
      copper: 0.3,
      manganese: 0.5,
      selenium: 2.8,
      fluoride: 9.0,
    },
    aminoAcids: {
      histidine: 207,
      isoleucine: 382,
      leucine: 621,
      lysine: 593,
      methionine: 77,
      phenylalanine: 427,
      threonine: 306,
      tryptophan: 77,
      valine: 437,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.03,
      omega6: 0.17,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chickpeas-cooked",
    name: "Chickpeas (Cooked)",
    category: "Legumes",
    description:
      "Cooked chickpeas (garbanzo beans), used in various cuisines including Indian, Middle Eastern, and Mediterranean",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 164,
      protein: 8.9,
      carbohydrates: 27.4,
      fat: 2.6,
      fiber: 7.6,
      sugar: 4.8,
      sodium: 7,
    },
    vitamins: {
      a: 27,
      c: 1.3,
      d: 0,
      e: 0.4,
      k: 4.0,
      b1: 0.12,
      b2: 0.06,
      b3: 0.5,
      b5: 0.3,
      b6: 0.14,
      b7: 1.5,
      b9: 172,
      b12: 0,
    },
    minerals: {
      calcium: 49,
      iron: 2.9,
      magnesium: 48,
      phosphorus: 168,
      potassium: 291,
      sodium: 7,
      zinc: 1.5,
      copper: 0.4,
      manganese: 1.0,
      selenium: 4.1,
      fluoride: 12.0,
    },
    aminoAcids: {
      histidine: 267,
      isoleucine: 422,
      leucine: 685,
      lysine: 593,
      methionine: 117,
      phenylalanine: 477,
      threonine: 346,
      tryptophan: 84,
      valine: 401,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.6,
      polyunsaturated: 1.2,
      omega3: 0.04,
      omega6: 1.16,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "kidney-beans-cooked",
    name: "Kidney Beans (Cooked)",
    category: "Legumes",
    description: "Cooked kidney beans, commonly used in various cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 127,
      protein: 8.7,
      carbohydrates: 22.8,
      fat: 0.5,
      fiber: 6.4,
      sugar: 0.3,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 1.2,
      d: 0,
      e: 0.2,
      k: 5.8,
      b1: 0.16,
      b2: 0.06,
      b3: 0.6,
      b5: 0.2,
      b6: 0.12,
      b7: 1.8,
      b9: 130,
      b12: 0,
    },
    minerals: {
      calcium: 35,
      iron: 2.9,
      magnesium: 42,
      phosphorus: 138,
      potassium: 405,
      sodium: 2,
      zinc: 1.0,
      copper: 0.2,
      manganese: 0.4,
      selenium: 1.5,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 260,
      isoleucine: 390,
      leucine: 690,
      lysine: 600,
      methionine: 120,
      phenylalanine: 480,
      threonine: 350,
      tryptophan: 85,
      valine: 450,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "black-beans-cooked",
    name: "Black Beans (Cooked)",
    category: "Legumes",
    description: "Cooked black beans, commonly used in Latin American cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 132,
      protein: 8.9,
      carbohydrates: 23.7,
      fat: 0.5,
      fiber: 8.7,
      sugar: 0.3,
      sodium: 1,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 3.3,
      b1: 0.24,
      b2: 0.05,
      b3: 0.4,
      b5: 0.2,
      b6: 0.12,
      b7: 2.0,
      b9: 149,
      b12: 0,
    },
    minerals: {
      calcium: 27,
      iron: 2.1,
      magnesium: 70,
      phosphorus: 140,
      potassium: 355,
      sodium: 1,
      zinc: 1.1,
      copper: 0.2,
      manganese: 0.4,
      selenium: 1.0,
      fluoride: 7.0,
    },
    aminoAcids: {
      histidine: 260,
      isoleucine: 390,
      leucine: 690,
      lysine: 600,
      methionine: 120,
      phenylalanine: 480,
      threonine: 350,
      tryptophan: 85,
      valine: 450,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mung-beans-cooked",
    name: "Mung Beans (Cooked)",
    category: "Legumes",
    description: "Cooked mung beans, commonly used in Asian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Asia",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 105,
      protein: 7.0,
      carbohydrates: 19.2,
      fat: 0.4,
      fiber: 7.6,
      sugar: 2.0,
      sodium: 2,
    },
    vitamins: {
      a: 2,
      c: 1.0,
      d: 0,
      e: 0.1,
      k: 2.7,
      b1: 0.16,
      b2: 0.06,
      b3: 0.6,
      b5: 0.4,
      b6: 0.09,
      b7: 1.7,
      b9: 159,
      b12: 0,
    },
    minerals: {
      calcium: 27,
      iron: 1.4,
      magnesium: 48,
      phosphorus: 99,
      potassium: 266,
      sodium: 2,
      zinc: 0.8,
      copper: 0.1,
      manganese: 0.3,
      selenium: 2.5,
      fluoride: 6.0,
    },
    aminoAcids: {
      histidine: 210,
      isoleucine: 320,
      leucine: 560,
      lysine: 490,
      methionine: 100,
      phenylalanine: 390,
      threonine: 280,
      tryptophan: 80,
      valine: 380,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pinto-beans-cooked",
    name: "Pinto Beans (Cooked)",
    category: "Legumes",
    description: "Cooked pinto beans, commonly used in Mexican and Southwestern US cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Americas",
    cuisine: "Mexican",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 143,
      protein: 9.0,
      carbohydrates: 26.2,
      fat: 0.7,
      fiber: 9.0,
      sugar: 0.3,
      sodium: 1,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 3.5,
      b1: 0.19,
      b2: 0.05,
      b3: 0.3,
      b5: 0.2,
      b6: 0.23,
      b7: 2.1,
      b9: 172,
      b12: 0,
    },
    minerals: {
      calcium: 46,
      iron: 2.1,
      magnesium: 50,
      phosphorus: 147,
      potassium: 436,
      sodium: 1,
      zinc: 0.9,
      copper: 0.2,
      manganese: 0.4,
      selenium: 0.7,
      fluoride: 7.0,
    },
    aminoAcids: {
      histidine: 270,
      isoleucine: 410,
      leucine: 730,
      lysine: 630,
      methionine: 130,
      phenylalanine: 500,
      threonine: 370,
      tryptophan: 90,
      valine: 470,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.3,
      omega3: 0.2,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "soybeans-cooked",
    name: "Soybeans (Cooked)",
    category: "Legumes",
    description: "Cooked soybeans, a protein-rich legume used in various cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 173,
      protein: 16.6,
      carbohydrates: 9.9,
      fat: 9.0,
      fiber: 6.0,
      sugar: 3.0,
      sodium: 1,
    },
    vitamins: {
      a: 1,
      c: 2.1,
      d: 0,
      e: 0.4,
      k: 19.2,
      b1: 0.16,
      b2: 0.29,
      b3: 0.4,
      b5: 0.4,
      b6: 0.23,
      b7: 5.0,
      b9: 54,
      b12: 0,
    },
    minerals: {
      calcium: 102,
      iron: 5.1,
      magnesium: 86,
      phosphorus: 245,
      potassium: 515,
      sodium: 1,
      zinc: 1.0,
      copper: 0.4,
      manganese: 0.8,
      selenium: 6.3,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 430,
      isoleucine: 770,
      leucine: 1290,
      lysine: 1050,
      methionine: 220,
      phenylalanine: 830,
      threonine: 680,
      tryptophan: 220,
      valine: 810,
    },
    fattyAcids: {
      saturated: 1.3,
      monounsaturated: 2.0,
      polyunsaturated: 5.1,
      omega3: 0.6,
      omega6: 4.5,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // VEGETABLES
  {
    id: "spinach-cooked",
    name: "Spinach (Cooked)",
    category: "Vegetables",
    description: "Cooked spinach, a nutrient-dense leafy green vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 23,
      protein: 2.9,
      carbohydrates: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      sodium: 70,
    },
    vitamins: {
      a: 9377,
      c: 9.8,
      d: 0,
      e: 2.1,
      k: 494.8,
      b1: 0.09,
      b2: 0.24,
      b3: 0.7,
      b5: 0.1,
      b6: 0.24,
      b7: 0.8,
      b9: 146,
      b12: 0,
    },
    minerals: {
      calcium: 136,
      iron: 3.6,
      magnesium: 87,
      phosphorus: 56,
      potassium: 558,
      sodium: 70,
      zinc: 0.5,
      copper: 0.1,
      manganese: 0.9,
      selenium: 1.0,
      fluoride: 14.0,
    },
    aminoAcids: {
      histidine: 64,
      isoleucine: 117,
      leucine: 198,
      lysine: 140,
      methionine: 50,
      phenylalanine: 124,
      threonine: 108,
      tryptophan: 39,
      valine: 141,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.14,
      omega6: 0.06,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "spinach-raw",
    name: "Spinach (Raw)",
    category: "Vegetables",
    description: "Raw spinach leaves, commonly used in salads",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3 cups raw",
    },
    nutrients: {
      calories: 23,
      protein: 2.9,
      carbohydrates: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      sodium: 79,
    },
    vitamins: {
      a: 9377,
      c: 28.1,
      d: 0,
      e: 2.0,
      k: 482.9,
      b1: 0.08,
      b2: 0.19,
      b3: 0.7,
      b5: 0.1,
      b6: 0.19,
      b7: 0.7,
      b9: 194,
      b12: 0,
    },
    minerals: {
      calcium: 99,
      iron: 2.7,
      magnesium: 79,
      phosphorus: 49,
      potassium: 558,
      sodium: 79,
      zinc: 0.5,
      copper: 0.1,
      manganese: 0.9,
      selenium: 1.0,
      fluoride: 12.0,
    },
    aminoAcids: {
      histidine: 64,
      isoleucine: 117,
      leucine: 198,
      lysine: 140,
      methionine: 50,
      phenylalanine: 124,
      threonine: 108,
      tryptophan: 39,
      valine: 141,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.14,
      omega6: 0.06,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "kale-raw",
    name: "Kale (Raw)",
    category: "Vegetables",
    description: "Raw kale leaves, a nutrient-dense leafy green vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "2 cups raw",
    },
    nutrients: {
      calories: 49,
      protein: 4.3,
      carbohydrates: 8.8,
      fat: 0.9,
      fiber: 3.6,
      sugar: 2.3,
      sodium: 38,
    },
    vitamins: {
      a: 9990,
      c: 120.0,
      d: 0,
      e: 0.7,
      k: 704.8,
      b1: 0.11,
      b2: 0.13,
      b3: 1.0,
      b5: 0.1,
      b6: 0.27,
      b7: 0.5,
      b9: 141,
      b12: 0,
    },
    minerals: {
      calcium: 150,
      iron: 1.5,
      magnesium: 33,
      phosphorus: 92,
      potassium: 491,
      sodium: 38,
      zinc: 0.6,
      copper: 0.3,
      manganese: 0.8,
      selenium: 0.9,
      fluoride: 10.0,
    },
    aminoAcids: {
      histidine: 95,
      isoleucine: 175,
      leucine: 295,
      lysine: 210,
      methionine: 75,
      phenylalanine: 185,
      threonine: 160,
      tryptophan: 60,
      valine: 210,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.4,
      omega3: 0.18,
      omega6: 0.22,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tomato-raw",
    name: "Tomato (Raw)",
    category: "Vegetables",
    description: "Fresh raw tomato, commonly used in salads and various dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium tomato",
    },
    nutrients: {
      calories: 18,
      protein: 0.9,
      carbohydrates: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
      sodium: 5,
    },
    vitamins: {
      a: 833,
      c: 13.7,
      d: 0,
      e: 0.5,
      k: 7.9,
      b1: 0.04,
      b2: 0.02,
      b3: 0.6,
      b5: 0.1,
      b6: 0.08,
      b7: 0.5,
      b9: 15,
      b12: 0,
    },
    minerals: {
      calcium: 10,
      iron: 0.3,
      magnesium: 11,
      phosphorus: 24,
      potassium: 237,
      sodium: 5,
      zinc: 0.2,
      copper: 0.1,
      manganese: 0.1,
      selenium: 0.0,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 18,
      isoleucine: 27,
      leucine: 42,
      lysine: 40,
      methionine: 11,
      phenylalanine: 30,
      threonine: 37,
      tryptophan: 7,
      valine: 30,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "carrot-raw",
    name: "Carrot (Raw)",
    category: "Vegetables",
    description: "Raw carrot, a root vegetable rich in beta-carotene",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsRootVegetables: true,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium carrot",
    },
    nutrients: {
      calories: 41,
      protein: 0.9,
      carbohydrates: 9.6,
      fat: 0.2,
      fiber: 2.8,
      sugar: 4.7,
      sodium: 69,
    },
    vitamins: {
      a: 16706,
      c: 5.9,
      d: 0,
      e: 0.7,
      k: 13.2,
      b1: 0.07,
      b2: 0.06,
      b3: 0.9,
      b5: 0.3,
      b6: 0.14,
      b7: 0.6,
      b9: 19,
      b12: 0,
    },
    minerals: {
      calcium: 33,
      iron: 0.3,
      magnesium: 12,
      phosphorus: 35,
      potassium: 320,
      sodium: 69,
      zinc: 0.2,
      copper: 0.0,
      manganese: 0.1,
      selenium: 0.1,
      fluoride: 3.2,
    },
    aminoAcids: {
      histidine: 19,
      isoleucine: 34,
      leucine: 56,
      lysine: 44,
      methionine: 13,
      phenylalanine: 37,
      threonine: 33,
      tryptophan: 12,
      valine: 41,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "broccoli-cooked",
    name: "Broccoli (Cooked)",
    category: "Vegetables",
    description: "Cooked broccoli, a nutritious cruciferous vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup chopped",
    },
    nutrients: {
      calories: 35,
      protein: 2.4,
      carbohydrates: 7.2,
      fat: 0.4,
      fiber: 3.3,
      sugar: 1.4,
      sodium: 41,
    },
    vitamins: {
      a: 1542,
      c: 89.2,
      d: 0,
      e: 1.5,
      k: 141.1,
      b1: 0.06,
      b2: 0.12,
      b3: 0.6,
      b5: 0.6,
      b6: 0.17,
      b7: 0.4,
      b9: 108,
      b12: 0,
    },
    minerals: {
      calcium: 47,
      iron: 0.7,
      magnesium: 21,
      phosphorus: 66,
      potassium: 293,
      sodium: 41,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.2,
      selenium: 2.5,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 53,
      isoleucine: 96,
      leucine: 163,
      lysine: 135,
      methionine: 48,
      phenylalanine: 106,
      threonine: 106,
      tryptophan: 29,
      valine: 125,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "potato-boiled",
    name: "Potato (Boiled)",
    category: "Vegetables",
    description: "Boiled potato without skin, a versatile starchy vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsRootVegetables: true,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium potato",
    },
    nutrients: {
      calories: 87,
      protein: 1.9,
      carbohydrates: 20.1,
      fat: 0.1,
      fiber: 1.8,
      sugar: 0.9,
      sodium: 6,
    },
    vitamins: {
      a: 0,
      c: 9.6,
      d: 0,
      e: 0.0,
      k: 1.6,
      b1: 0.08,
      b2: 0.03,
      b3: 1.1,
      b5: 0.3,
      b6: 0.3,
      b7: 0.7,
      b9: 9,
      b12: 0,
    },
    minerals: {
      calcium: 12,
      iron: 0.8,
      magnesium: 23,
      phosphorus: 57,
      potassium: 421,
      sodium: 6,
      zinc: 0.3,
      copper: 0.1,
      manganese: 0.2,
      selenium: 0.4,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 37,
      isoleucine: 74,
      leucine: 114,
      lysine: 108,
      methionine: 31,
      phenylalanine: 83,
      threonine: 73,
      tryptophan: 25,
      valine: 100,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cauliflower-cooked",
    name: "Cauliflower (Cooked)",
    category: "Vegetables",
    description: "Cooked cauliflower, a versatile cruciferous vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup chopped",
    },
    nutrients: {
      calories: 29,
      protein: 2.3,
      carbohydrates: 5.3,
      fat: 0.5,
      fiber: 2.0,
      sugar: 2.0,
      sodium: 30,
    },
    vitamins: {
      a: 0,
      c: 44.3,
      d: 0,
      e: 0.1,
      k: 13.8,
      b1: 0.05,
      b2: 0.06,
      b3: 0.5,
      b5: 0.7,
      b6: 0.22,
      b7: 0.2,
      b9: 57,
      b12: 0,
    },
    minerals: {
      calcium: 22,
      iron: 0.4,
      magnesium: 15,
      phosphorus: 44,
      potassium: 299,
      sodium: 30,
      zinc: 0.3,
      copper: 0.0,
      manganese: 0.2,
      selenium: 0.6,
      fluoride: 7.0,
    },
    aminoAcids: {
      histidine: 51,
      isoleucine: 92,
      leucine: 156,
      lysine: 129,
      methionine: 46,
      phenylalanine: 101,
      threonine: 101,
      tryptophan: 28,
      valine: 120,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "onion-raw",
    name: "Onion (Raw)",
    category: "Vegetables",
    description: "Raw onion, a flavorful vegetable used in many cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium onion",
    },
    nutrients: {
      calories: 40,
      protein: 1.1,
      carbohydrates: 9.3,
      fat: 0.1,
      fiber: 1.7,
      sugar: 4.2,
      sodium: 4,
    },
    vitamins: {
      a: 0,
      c: 7.4,
      d: 0,
      e: 0.0,
      k: 0.4,
      b1: 0.05,
      b2: 0.03,
      b3: 0.2,
      b5: 0.1,
      b6: 0.12,
      b7: 0.1,
      b9: 19,
      b12: 0,
    },
    minerals: {
      calcium: 23,
      iron: 0.2,
      magnesium: 10,
      phosphorus: 29,
      potassium: 146,
      sodium: 4,
      zinc: 0.2,
      copper: 0.0,
      manganese: 0.1,
      selenium: 0.5,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 24,
      isoleucine: 44,
      leucine: 68,
      lysine: 57,
      methionine: 16,
      phenylalanine: 44,
      threonine: 44,
      tryptophan: 14,
      valine: 51,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "garlic-raw",
    name: "Garlic (Raw)",
    category: "Vegetables",
    description: "Raw garlic, a pungent vegetable used for flavoring in many cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "about 10 cloves",
    },
    nutrients: {
      calories: 149,
      protein: 6.4,
      carbohydrates: 33.1,
      fat: 0.5,
      fiber: 2.1,
      sugar: 1.0,
      sodium: 17,
    },
    vitamins: {
      a: 0,
      c: 31.2,
      d: 0,
      e: 0.1,
      k: 1.7,
      b1: 0.2,
      b2: 0.11,
      b3: 0.7,
      b5: 0.6,
      b6: 1.24,
      b7: 0.1,
      b9: 3,
      b12: 0,
    },
    minerals: {
      calcium: 181,
      iron: 1.7,
      magnesium: 25,
      phosphorus: 153,
      potassium: 401,
      sodium: 17,
      zinc: 1.2,
      copper: 0.3,
      manganese: 1.7,
      selenium: 14.2,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 141,
      isoleucine: 256,
      leucine: 403,
      lysine: 273,
      methionine: 96,
      phenylalanine: 256,
      threonine: 256,
      tryptophan: 83,
      valine: 301,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cucumber-raw",
    name: "Cucumber (Raw)",
    category: "Vegetables",
    description: "Raw cucumber with peel, a refreshing vegetable with high water content",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "2/3 cup sliced",
    },
    nutrients: {
      calories: 15,
      protein: 0.7,
      carbohydrates: 3.6,
      fat: 0.1,
      fiber: 0.5,
      sugar: 1.7,
      sodium: 2,
    },
    vitamins: {
      a: 105,
      c: 2.8,
      d: 0,
      e: 0.0,
      k: 16.4,
      b1: 0.03,
      b2: 0.03,
      b3: 0.1,
      b5: 0.3,
      b6: 0.04,
      b7: 0.1,
      b9: 7,
      b12: 0,
    },
    minerals: {
      calcium: 16,
      iron: 0.3,
      magnesium: 13,
      phosphorus: 24,
      potassium: 147,
      sodium: 2,
      zinc: 0.2,
      copper: 0.0,
      manganese: 0.1,
      selenium: 0.3,
      fluoride: 1.3,
    },
    aminoAcids: {
      histidine: 15,
      isoleucine: 28,
      leucine: 42,
      lysine: 36,
      methionine: 10,
      phenylalanine: 28,
      threonine: 28,
      tryptophan: 9,
      valine: 32,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "bell-pepper-red-raw",
    name: "Red Bell Pepper (Raw)",
    category: "Vegetables",
    description: "Raw red bell pepper, a sweet and colorful vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium pepper",
    },
    nutrients: {
      calories: 31,
      protein: 1.0,
      carbohydrates: 6.3,
      fat: 0.3,
      fiber: 2.1,
      sugar: 4.2,
      sodium: 4,
    },
    vitamins: {
      a: 3131,
      c: 127.7,
      d: 0,
      e: 1.6,
      k: 4.9,
      b1: 0.05,
      b2: 0.09,
      b3: 0.9,
      b5: 0.3,
      b6: 0.29,
      b7: 0.1,
      b9: 46,
      b12: 0,
    },
    minerals: {
      calcium: 7,
      iron: 0.4,
      magnesium: 12,
      phosphorus: 26,
      potassium: 211,
      sodium: 4,
      zinc: 0.3,
      copper: 0.0,
      manganese: 0.1,
      selenium: 0.1,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 22,
      isoleucine: 40,
      leucine: 61,
      lysine: 51,
      methionine: 15,
      phenylalanine: 40,
      threonine: 40,
      tryptophan: 13,
      valine: 46,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.0,
      omega6: 0.2,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eggplant-cooked",
    name: "Eggplant (Cooked)",
    category: "Vegetables",
    description: "Cooked eggplant, a versatile vegetable used in many cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup cubed",
    },
    nutrients: {
      calories: 35,
      protein: 0.8,
      carbohydrates: 8.7,
      fat: 0.2,
      fiber: 2.5,
      sugar: 3.2,
      sodium: 2,
    },
    vitamins: {
      a: 1,
      c: 2.2,
      d: 0,
      e: 0.3,
      k: 2.9,
      b1: 0.08,
      b2: 0.02,
      b3: 0.6,
      b5: 0.3,
      b6: 0.08,
      b7: 0.1,
      b9: 14,
      b12: 0,
    },
    minerals: {
      calcium: 9,
      iron: 0.2,
      magnesium: 14,
      phosphorus: 15,
      potassium: 229,
      sodium: 2,
      zinc: 0.1,
      copper: 0.1,
      manganese: 0.2,
      selenium: 0.3,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 18,
      isoleucine: 32,
      leucine: 49,
      lysine: 41,
      methionine: 12,
      phenylalanine: 32,
      threonine: 32,
      tryptophan: 10,
      valine: 37,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "okra-cooked",
    name: "Okra (Cooked)",
    category: "Vegetables",
    description: "Cooked okra, a vegetable commonly used in Indian, Middle Eastern, and Southern US cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup sliced",
    },
    nutrients: {
      calories: 33,
      protein: 1.9,
      carbohydrates: 7.5,
      fat: 0.2,
      fiber: 3.2,
      sugar: 1.5,
      sodium: 7,
    },
    vitamins: {
      a: 375,
      c: 16.3,
      d: 0,
      e: 0.4,
      k: 31.3,
      b1: 0.2,
      b2: 0.06,
      b3: 1.0,
      b5: 0.2,
      b6: 0.22,
      b7: 0.2,
      b9: 46,
      b12: 0,
    },
    minerals: {
      calcium: 82,
      iron: 0.8,
      magnesium: 57,
      phosphorus: 61,
      potassium: 303,
      sodium: 7,
      zinc: 0.6,
      copper: 0.1,
      manganese: 1.0,
      selenium: 0.7,
      fluoride: 3.0,
    },
    aminoAcids: {
      histidine: 42,
      isoleucine: 76,
      leucine: 117,
      lysine: 98,
      methionine: 28,
      phenylalanine: 76,
      threonine: 76,
      tryptophan: 24,
      valine: 89,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "bitter-gourd-cooked",
    name: "Bitter Gourd (Cooked)",
    category: "Vegetables",
    description: "Cooked bitter gourd (karela), a vegetable commonly used in Asian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup sliced",
    },
    nutrients: {
      calories: 17,
      protein: 1.0,
      carbohydrates: 3.7,
      fat: 0.2,
      fiber: 2.0,
      sugar: 1.8,
      sodium: 5,
    },
    vitamins: {
      a: 471,
      c: 33.0,
      d: 0,
      e: 0.1,
      k: 4.8,
      b1: 0.05,
      b2: 0.04,
      b3: 0.4,
      b5: 0.2,
      b6: 0.04,
      b7: 0.1,
      b9: 72,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 0.4,
      magnesium: 16,
      phosphorus: 31,
      potassium: 296,
      sodium: 5,
      zinc: 0.8,
      copper: 0.0,
      manganese: 0.1,
      selenium: 0.2,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 22,
      isoleucine: 40,
      leucine: 61,
      lysine: 51,
      methionine: 15,
      phenylalanine: 40,
      threonine: 40,
      tryptophan: 13,
      valine: 46,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // DAIRY
  {
    id: "milk-cow-whole",
    name: "Whole Milk",
    category: "Dairy",
    description: "Whole cow's milk with approximately 3.25% fat content",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "ml",
      description: "1 small glass",
    },
    nutrients: {
      calories: 61,
      protein: 3.2,
      carbohydrates: 4.8,
      fat: 3.3,
      fiber: 0,
      sugar: 5.1,
      sodium: 43,
    },
    vitamins: {
      a: 162,
      c: 0,
      d: 51,
      e: 0.1,
      k: 0.3,
      b1: 0.05,
      b2: 0.18,
      b3: 0.1,
      b5: 0.3,
      b6: 0.04,
      b7: 2.0,
      b9: 5,
      b12: 0.4,
    },
    minerals: {
      calcium: 113,
      iron: 0.0,
      magnesium: 10,
      phosphorus: 84,
      potassium: 132,
      sodium: 43,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 89,
      isoleucine: 189,
      leucine: 322,
      lysine: 261,
      methionine: 83,
      phenylalanine: 159,
      threonine: 149,
      tryptophan: 46,
      valine: 220,
    },
    fattyAcids: {
      saturated: 1.9,
      monounsaturated: 0.8,
      polyunsaturated: 0.2,
      omega3: 0.08,
      omega6: 0.12,
      trans: 0.1,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "milk-cow-low-fat",
    name: "Low-Fat Milk (2%)",
    category: "Dairy",
    description: "Low-fat cow's milk with approximately 2% fat content",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "ml",
      description: "1 small glass",
    },
    nutrients: {
      calories: 50,
      protein: 3.3,
      carbohydrates: 4.8,
      fat: 2.0,
      fiber: 0,
      sugar: 5.1,
      sodium: 43,
    },
    vitamins: {
      a: 196,
      c: 0,
      d: 49,
      e: 0.1,
      k: 0.2,
      b1: 0.05,
      b2: 0.18,
      b3: 0.1,
      b5: 0.3,
      b6: 0.04,
      b7: 2.0,
      b9: 5,
      b12: 0.4,
    },
    minerals: {
      calcium: 122,
      iron: 0.0,
      magnesium: 11,
      phosphorus: 93,
      potassium: 143,
      sodium: 43,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 92,
      isoleucine: 196,
      leucine: 333,
      lysine: 270,
      methionine: 86,
      phenylalanine: 165,
      threonine: 154,
      tryptophan: 48,
      valine: 228,
    },
    fattyAcids: {
      saturated: 1.3,
      monounsaturated: 0.6,
      polyunsaturated: 0.1,
      omega3: 0.04,
      omega6: 0.06,
      trans: 0.1,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "milk-cow-skim",
    name: "Skim Milk",
    category: "Dairy",
    description: "Skim cow's milk with less than 0.5% fat content",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "ml",
      description: "1 small glass",
    },
    nutrients: {
      calories: 34,
      protein: 3.4,
      carbohydrates: 5.0,
      fat: 0.1,
      fiber: 0,
      sugar: 5.1,
      sodium: 42,
    },
    vitamins: {
      a: 149,
      c: 0,
      d: 46,
      e: 0.0,
      k: 0.0,
      b1: 0.04,
      b2: 0.18,
      b3: 0.1,
      b5: 0.3,
      b6: 0.04,
      b7: 2.0,
      b9: 5,
      b12: 0.4,
    },
    minerals: {
      calcium: 123,
      iron: 0.0,
      magnesium: 11,
      phosphorus: 95,
      potassium: 156,
      sodium: 42,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 95,
      isoleucine: 202,
      leucine: 343,
      lysine: 278,
      methionine: 89,
      phenylalanine: 170,
      threonine: 159,
      tryptophan: 49,
      valine: 235,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0.0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "yogurt-plain",
    name: "Plain Yogurt (Whole Milk)",
    category: "Dairy",
    description: "Plain yogurt made from whole milk",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 61,
      protein: 3.5,
      carbohydrates: 4.7,
      fat: 3.3,
      fiber: 0,
      sugar: 4.7,
      sodium: 46,
    },
    vitamins: {
      a: 99,
      c: 0.5,
      d: 2,
      e: 0.1,
      k: 0.2,
      b1: 0.03,
      b2: 0.14,
      b3: 0.1,
      b5: 0.4,
      b6: 0.03,
      b7: 2.4,
      b9: 7,
      b12: 0.4,
    },
    minerals: {
      calcium: 121,
      iron: 0.1,
      magnesium: 12,
      phosphorus: 95,
      potassium: 155,
      sodium: 46,
      zinc: 0.6,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.3,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 97,
      isoleucine: 207,
      leucine: 352,
      lysine: 285,
      methionine: 91,
      phenylalanine: 174,
      threonine: 163,
      tryptophan: 50,
      valine: 240,
    },
    fattyAcids: {
      saturated: 2.1,
      monounsaturated: 0.9,
      polyunsaturated: 0.1,
      omega3: 0.04,
      omega6: 0.06,
      trans: 0.1,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "yogurt-greek",
    name: "Greek Yogurt (Plain)",
    category: "Dairy",
    description: "Plain Greek yogurt, strained to remove whey, resulting in higher protein content",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 97,
      protein: 9.0,
      carbohydrates: 3.6,
      fat: 5.0,
      fiber: 0,
      sugar: 3.6,
      sodium: 36,
    },
    vitamins: {
      a: 149,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0.2,
      b1: 0.02,
      b2: 0.21,
      b3: 0.2,
      b5: 0.6,
      b6: 0.07,
      b7: 3.0,
      b9: 12,
      b12: 0.8,
    },
    minerals: {
      calcium: 115,
      iron: 0.1,
      magnesium: 11,
      phosphorus: 135,
      potassium: 141,
      sodium: 36,
      zinc: 0.7,
      copper: 0.0,
      manganese: 0.0,
      selenium: 9.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 250,
      isoleucine: 531,
      leucine: 903,
      lysine: 731,
      methionine: 234,
      phenylalanine: 446,
      threonine: 417,
      tryptophan: 129,
      valine: 617,
    },
    fattyAcids: {
      saturated: 3.3,
      monounsaturated: 1.3,
      polyunsaturated: 0.2,
      omega3: 0.08,
      omega6: 0.12,
      trans: 0.2,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "paneer",
    name: "Paneer (Indian Cottage Cheese)",
    category: "Dairy",
    description: "Fresh Indian cottage cheese made from curdled milk",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup cubed",
    },
    nutrients: {
      calories: 265,
      protein: 18.3,
      carbohydrates: 3.1,
      fat: 20.8,
      fiber: 0,
      sugar: 1.0,
      sodium: 34,
    },
    vitamins: {
      a: 274,
      c: 0,
      d: 16,
      e: 0.3,
      k: 1.0,
      b1: 0.03,
      b2: 0.21,
      b3: 0.1,
      b5: 0.5,
      b6: 0.08,
      b7: 1.5,
      b9: 14,
      b12: 1.1,
    },
    minerals: {
      calcium: 510,
      iron: 0.7,
      magnesium: 28,
      phosphorus: 490,
      potassium: 138,
      sodium: 34,
      zinc: 2.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 15.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 530,
      isoleucine: 1100,
      leucine: 1800,
      lysine: 1500,
      methionine: 480,
      phenylalanine: 950,
      threonine: 850,
      tryptophan: 260,
      valine: 1300,
    },
    fattyAcids: {
      saturated: 13.1,
      monounsaturated: 6.0,
      polyunsaturated: 0.8,
      omega3: 0.2,
      omega6: 0.6,
      trans: 0.5,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cheese-cheddar",
    name: "Cheddar Cheese",
    category: "Dairy",
    description: "Cheddar cheese, a firm, yellow cheese",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup shredded",
    },
    nutrients: {
      calories: 403,
      protein: 24.9,
      carbohydrates: 1.3,
      fat: 33.1,
      fiber: 0,
      sugar: 0.5,
      sodium: 621,
    },
    vitamins: {
      a: 1242,
      c: 0,
      d: 24,
      e: 0.7,
      k: 2.4,
      b1: 0.03,
      b2: 0.38,
      b3: 0.1,
      b5: 0.4,
      b6: 0.07,
      b7: 2.0,
      b9: 18,
      b12: 1.1,
    },
    minerals: {
      calcium: 721,
      iron: 0.7,
      magnesium: 28,
      phosphorus: 512,
      potassium: 98,
      sodium: 621,
      zinc: 3.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 28.5,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 690,
      isoleucine: 1470,
      leucine: 2390,
      lysine: 2000,
      methionine: 640,
      phenylalanine: 1270,
      threonine: 1130,
      tryptophan: 350,
      valine: 1730,
    },
    fattyAcids: {
      saturated: 21.1,
      monounsaturated: 9.4,
      polyunsaturated: 1.0,
      omega3: 0.4,
      omega6: 0.6,
      trans: 1.2,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "butter-unsalted",
    name: "Butter (Unsalted)",
    category: "Dairy",
    description: "Unsalted butter, a dairy product made from churning cream",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 717,
      protein: 0.9,
      carbohydrates: 0.1,
      fat: 81.1,
      fiber: 0,
      sugar: 0.1,
      sodium: 11,
    },
    vitamins: {
      a: 3069,
      c: 0,
      d: 56,
      e: 2.3,
      k: 7.0,
      b1: 0.01,
      b2: 0.03,
      b3: 0.0,
      b5: 0.1,
      b6: 0.0,
      b7: 0.1,
      b9: 3,
      b12: 0.2,
    },
    minerals: {
      calcium: 24,
      iron: 0.0,
      magnesium: 2,
      phosphorus: 24,
      potassium: 24,
      sodium: 11,
      zinc: 0.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 1.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 25,
      isoleucine: 53,
      leucine: 90,
      lysine: 73,
      methionine: 23,
      phenylalanine: 45,
      threonine: 41,
      tryptophan: 13,
      valine: 62,
    },
    fattyAcids: {
      saturated: 51.4,
      monounsaturated: 21.0,
      polyunsaturated: 3.0,
      omega3: 1.2,
      omega6: 1.8,
      trans: 3.3,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // FRUITS
  {
    id: "apple-raw",
    name: "Apple (Raw)",
    category: "Fruits",
    description: "Fresh raw apple with skin, a common fruit",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 small apple",
    },
    nutrients: {
      calories: 52,
      protein: 0.3,
      carbohydrates: 13.8,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10.4,
      sodium: 1,
    },
    vitamins: {
      a: 54,
      c: 4.6,
      d: 0,
      e: 0.2,
      k: 2.2,
      b1: 0.02,
      b2: 0.03,
      b3: 0.1,
      b5: 0.1,
      b6: 0.04,
      b7: 0.1,
      b9: 3,
      b12: 0,
    },
    minerals: {
      calcium: 6,
      iron: 0.1,
      magnesium: 5,
      phosphorus: 11,
      potassium: 107,
      sodium: 1,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 3.3,
    },
    aminoAcids: {
      histidine: 3,
      isoleucine: 6,
      leucine: 13,
      lysine: 12,
      methionine: 1,
      phenylalanine: 5,
      threonine: 6,
      tryptophan: 1,
      valine: 8,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.01,
      omega6: 0.09,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "banana-raw",
    name: "Banana (Raw)",
    category: "Fruits",
    description: "Fresh raw banana, a common tropical fruit",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium banana",
    },
    nutrients: {
      calories: 89,
      protein: 1.1,
      carbohydrates: 22.8,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12.2,
      sodium: 1,
    },
    vitamins: {
      a: 64,
      c: 8.7,
      d: 0,
      e: 0.1,
      k: 0.5,
      b1: 0.03,
      b2: 0.07,
      b3: 0.7,
      b5: 0.3,
      b6: 0.37,
      b7: 0.1,
      b9: 20,
      b12: 0,
    },
    minerals: {
      calcium: 5,
      iron: 0.3,
      magnesium: 27,
      phosphorus: 22,
      potassium: 358,
      sodium: 1,
      zinc: 0.2,
      copper: 0.1,
      manganese: 0.3,
      selenium: 1.0,
      fluoride: 2.2,
    },
    aminoAcids: {
      histidine: 28,
      isoleucine: 28,
      leucine: 65,
      lysine: 50,
      methionine: 10,
      phenylalanine: 39,
      threonine: 31,
      tryptophan: 12,
      valine: 40,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.03,
      omega6: 0.07,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "orange-raw",
    name: "Orange (Raw)",
    category: "Fruits",
    description: "Fresh raw orange, a citrus fruit rich in vitamin C",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 small orange",
    },
    nutrients: {
      calories: 47,
      protein: 0.9,
      carbohydrates: 11.8,
      fat: 0.1,
      fiber: 2.4,
      sugar: 9.4,
      sodium: 0,
    },
    vitamins: {
      a: 225,
      c: 53.2,
      d: 0,
      e: 0.2,
      k: 0.0,
      b1: 0.09,
      b2: 0.04,
      b3: 0.4,
      b5: 0.3,
      b6: 0.06,
      b7: 0.1,
      b9: 30,
      b12: 0,
    },
    minerals: {
      calcium: 40,
      iron: 0.1,
      magnesium: 10,
      phosphorus: 14,
      potassium: 181,
      sodium: 0,
      zinc: 0.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.5,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 20,
      isoleucine: 36,
      leucine: 58,
      lysine: 49,
      methionine: 14,
      phenylalanine: 38,
      threonine: 38,
      tryptophan: 12,
      valine: 44,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mango-raw",
    name: "Mango (Raw)",
    category: "Fruits",
    description: "Fresh raw mango, a tropical fruit popular in Indian cuisine",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup sliced",
    },
    nutrients: {
      calories: 60,
      protein: 0.8,
      carbohydrates: 15.0,
      fat: 0.4,
      fiber: 1.6,
      sugar: 13.7,
      sodium: 1,
    },
    vitamins: {
      a: 765,
      c: 36.4,
      d: 0,
      e: 0.9,
      k: 4.2,
      b1: 0.03,
      b2: 0.04,
      b3: 0.7,
      b5: 0.2,
      b6: 0.12,
      b7: 0.1,
      b9: 43,
      b12: 0,
    },
    minerals: {
      calcium: 11,
      iron: 0.2,
      magnesium: 10,
      phosphorus: 14,
      potassium: 168,
      sodium: 1,
      zinc: 0.1,
      copper: 0.1,
      manganese: 0.1,
      selenium: 0.6,
      fluoride: 1.5,
    },
    aminoAcids: {
      histidine: 18,
      isoleucine: 32,
      leucine: 52,
      lysine: 44,
      methionine: 13,
      phenylalanine: 34,
      threonine: 34,
      tryptophan: 11,
      valine: 39,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.03,
      omega6: 0.07,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "papaya-raw",
    name: "Papaya (Raw)",
    category: "Fruits",
    description: "Fresh raw papaya, a tropical fruit with orange flesh",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup cubed",
    },
    nutrients: {
      calories: 43,
      protein: 0.5,
      carbohydrates: 10.8,
      fat: 0.3,
      fiber: 1.7,
      sugar: 7.8,
      sodium: 3,
    },
    vitamins: {
      a: 1094,
      c: 60.9,
      d: 0,
      e: 0.5,
      k: 2.6,
      b1: 0.03,
      b2: 0.03,
      b3: 0.3,
      b5: 0.0,
      b6: 0.04,
      b7: 0.0,
      b9: 38,
      b12: 0,
    },
    minerals: {
      calcium: 20,
      iron: 0.3,
      magnesium: 10,
      phosphorus: 5,
      potassium: 182,
      sodium: 3,
      zinc: 0.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.6,
      fluoride: 6.0,
    },
    aminoAcids: {
      histidine: 10,
      isoleucine: 20,
      leucine: 30,
      lysine: 30,
      methionine: 10,
      phenylalanine: 20,
      threonine: 20,
      tryptophan: 10,
      valine: 20,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.1,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "guava-raw",
    name: "Guava (Raw)",
    category: "Fruits",
    description: "Fresh raw guava, a tropical fruit with high vitamin C content",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium guava",
    },
    nutrients: {
      calories: 68,
      protein: 2.6,
      carbohydrates: 14.3,
      fat: 1.0,
      fiber: 5.4,
      sugar: 9.0,
      sodium: 2,
    },
    vitamins: {
      a: 624,
      c: 228.3,
      d: 0,
      e: 0.7,
      k: 2.6,
      b1: 0.02,
      b2: 0.04,
      b3: 1.1,
      b5: 0.5,
      b6: 0.11,
      b7: 0.0,
      b9: 36,
      b12: 0,
    },
    minerals: {
      calcium: 18,
      iron: 0.3,
      magnesium: 22,
      phosphorus: 40,
      potassium: 417,
      sodium: 2,
      zinc: 0.2,
      copper: 0.2,
      manganese: 0.2,
      selenium: 0.6,
      fluoride: 0.8,
    },
    aminoAcids: {
      histidine: 40,
      isoleucine: 70,
      leucine: 120,
      lysine: 100,
      methionine: 20,
      phenylalanine: 70,
      threonine: 60,
      tryptophan: 20,
      valine: 80,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.2,
      polyunsaturated: 0.4,
      omega3: 0.1,
      omega6: 0.3,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // PROTEIN SOURCES
  {
    id: "chicken-breast-cooked",
    name: "Chicken Breast (Cooked)",
    category: "Protein",
    description: "Cooked boneless, skinless chicken breast",
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    source: "usda",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3.5 oz cooked",
    },
    nutrients: {
      calories: 165,
      protein: 31.0,
      carbohydrates: 0.0,
      fat: 3.6,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 74,
    },
    vitamins: {
      a: 21,
      c: 0,
      d: 3,
      e: 0.3,
      k: 0.3,
      b1: 0.06,
      b2: 0.12,
      b3: 13.7,
      b5: 0.9,
      b6: 0.6,
      b7: 0.3,
      b9: 4,
      b12: 0.3,
    },
    minerals: {
      calcium: 15,
      iron: 1.0,
      magnesium: 29,
      phosphorus: 228,
      potassium: 256,
      sodium: 74,
      zinc: 1.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 24.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 950,
      isoleucine: 1520,
      leucine: 2470,
      lysine: 2840,
      methionine: 830,
      phenylalanine: 1290,
      threonine: 1410,
      tryptophan: 380,
      valine: 1580,
    },
    fattyAcids: {
      saturated: 1.0,
      monounsaturated: 1.4,
      polyunsaturated: 0.8,
      omega3: 0.1,
      omega6: 0.7,
      trans: 0.0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "egg-boiled",
    name: "Egg (Boiled)",
    category: "Protein",
    description: "Hard-boiled chicken egg",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "usda",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 50,
      unit: "g",
      description: "1 large egg",
    },
    nutrients: {
      calories: 78,
      protein: 6.3,
      carbohydrates: 0.6,
      fat: 5.3,
      fiber: 0.0,
      sugar: 0.6,
      sodium: 62,
    },
    vitamins: {
      a: 260,
      c: 0,
      d: 44,
      e: 0.5,
      k: 0.1,
      b1: 0.03,
      b2: 0.26,
      b3: 0.1,
      b5: 0.7,
      b6: 0.06,
      b7: 10.0,
      b9: 22,
      b12: 0.6,
    },
    minerals: {
      calcium: 25,
      iron: 0.6,
      magnesium: 5,
      phosphorus: 86,
      potassium: 63,
      sodium: 62,
      zinc: 0.5,
      copper: 0.0,
      manganese: 0.0,
      selenium: 15.4,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 154,
      isoleucine: 331,
      leucine: 543,
      lysine: 436,
      methionine: 191,
      phenylalanine: 341,
      threonine: 292,
      tryptophan: 83,
      valine: 428,
    },
    fattyAcids: {
      saturated: 1.6,
      monounsaturated: 2.0,
      polyunsaturated: 0.7,
      omega3: 0.1,
      omega6: 0.6,
      trans: 0.0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tofu-firm",
    name: "Tofu (Firm)",
    category: "Protein",
    description: "Firm tofu made from soybeans",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "usda",
    region: "Asia",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 144,
      protein: 17.3,
      carbohydrates: 2.8,
      fat: 8.7,
      fiber: 2.3,
      sugar: 0.7,
      sodium: 7,
    },
    vitamins: {
      a: 0,
      c: 0.1,
      d: 0,
      e: 0.0,
      k: 2.4,
      b1: 0.16,
      b2: 0.09,
      b3: 0.2,
      b5: 0.1,
      b6: 0.09,
      b7: 2.1,
      b9: 19,
      b12: 0,
    },
    minerals: {
      calcium: 683,
      iron: 2.7,
      magnesium: 58,
      phosphorus: 190,
      potassium: 237,
      sodium: 7,
      zinc: 1.0,
      copper: 0.4,
      manganese: 1.5,
      selenium: 17.8,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 450,
      isoleucine: 850,
      leucine: 1400,
      lysine: 1100,
      methionine: 220,
      phenylalanine: 880,
      threonine: 680,
      tryptophan: 240,
      valine: 850,
    },
    fattyAcids: {
      saturated: 1.3,
      monounsaturated: 1.9,
      polyunsaturated: 5.0,
      omega3: 0.6,
      omega6: 4.4,
      trans: 0.0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "salmon-cooked",
    name: "Salmon (Cooked)",
    category: "Protein",
    description: "Cooked Atlantic salmon fillet",
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    source: "usda",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3.5 oz cooked",
    },
    nutrients: {
      calories: 206,
      protein: 22.1,
      carbohydrates: 0.0,
      fat: 13.4,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 59,
    },
    vitamins: {
      a: 149,
      c: 3.9,
      d: 526,
      e: 1.1,
      k: 0.5,
      b1: 0.23,
      b2: 0.38,
      b3: 8.0,
      b5: 1.5,
      b6: 0.8,
      b7: 4.0,
      b9: 26,
      b12: 2.8,
    },
    minerals: {
      calcium: 12,
      iron: 0.3,
      magnesium: 29,
      phosphorus: 252,
      potassium: 384,
      sodium: 59,
      zinc: 0.6,
      copper: 0.0,
      manganese: 0.0,
      selenium: 41.4,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 630,
      isoleucine: 970,
      leucine: 1620,
      lysine: 1920,
      methionine: 600,
      phenylalanine: 810,
      threonine: 890,
      tryptophan: 230,
      valine: 1050,
    },
    fattyAcids: {
      saturated: 3.1,
      monounsaturated: 5.7,
      polyunsaturated: 3.9,
      omega3: 2.2,
      omega6: 1.7,
      trans: 0.0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // INDIAN DISHES
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    category: "Indian Dishes",
    description: "Creamy black lentil and kidney bean curry with butter and cream",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "custom",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 150,
      unit: "g",
      description: "1 serving",
    },
    nutrients: {
      calories: 240,
      protein: 9.0,
      carbohydrates: 22.0,
      fat: 12.5,
      fiber: 7.0,
      sugar: 2.0,
      sodium: 350,
    },
    vitamins: {
      a: 120,
      c: 5.0,
      d: 0.2,
      e: 0.5,
      k: 2.0,
      b1: 0.2,
      b2: 0.1,
      b3: 1.0,
      b5: 0.5,
      b6: 0.2,
      b7: 2.0,
      b9: 120,
      b12: 0.2,
    },
    minerals: {
      calcium: 60,
      iron: 3.5,
      magnesium: 45,
      phosphorus: 150,
      potassium: 380,
      sodium: 350,
      zinc: 1.5,
      copper: 0.3,
      manganese: 0.6,
      selenium: 3.0,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 210,
      isoleucine: 380,
      leucine: 620,
      lysine: 590,
      methionine: 80,
      phenylalanine: 430,
      threonine: 310,
      tryptophan: 80,
      valine: 440,
    },
    fattyAcids: {
      saturated: 7.0,
      monounsaturated: 3.5,
      polyunsaturated: 0.8,
      omega3: 0.1,
      omega6: 0.7,
      trans: 0.3,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chana-masala",
    name: "Chana Masala",
    category: "Indian Dishes",
    description: "Spicy chickpea curry with tomatoes and spices",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "custom",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 150,
      unit: "g",
      description: "1 serving",
    },
    nutrients: {
      calories: 190,
      protein: 8.0,
      carbohydrates: 30.0,
      fat: 5.0,
      fiber: 8.0,
      sugar: 5.0,
      sodium: 320,
    },
    vitamins: {
      a: 150,
      c: 15.0,
      d: 0,
      e: 0.8,
      k: 5.0,
      b1: 0.15,
      b2: 0.08,
      b3: 0.8,
      b5: 0.4,
      b6: 0.2,
      b7: 1.5,
      b9: 120,
      b12: 0,
    },
    minerals: {
      calcium: 60,
      iron: 3.0,
      magnesium: 50,
      phosphorus: 160,
      potassium: 350,
      sodium: 320,
      zinc: 1.4,
      copper: 0.3,
      manganese: 0.8,
      selenium: 3.5,
      fluoride: 10.0,
    },
    aminoAcids: {
      histidine: 200,
      isoleucine: 350,
      leucine: 580,
      lysine: 500,
      methionine: 100,
      phenylalanine: 400,
      threonine: 300,
      tryptophan: 75,
      valine: 380,
    },
    fattyAcids: {
      saturated: 0.7,
      monounsaturated: 3.0,
      polyunsaturated: 1.0,
      omega3: 0.1,
      omega6: 0.9,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    category: "Indian Dishes",
    description: "Spinach curry with Indian cottage cheese cubes",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "custom",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 150,
      unit: "g",
      description: "1 serving",
    },
    nutrients: {
      calories: 220,
      protein: 11.0,
      carbohydrates: 10.0,
      fat: 15.0,
      fiber: 4.0,
      sugar: 3.0,
      sodium: 380,
    },
    vitamins: {
      a: 5000,
      c: 28.0,
      d: 0.2,
      e: 2.0,
      k: 250.0,
      b1: 0.1,
      b2: 0.2,
      b3: 0.8,
      b5: 0.4,
      b6: 0.2,
      b7: 1.5,
      b9: 100,
      b12: 0.5,
    },
    minerals: {
      calcium: 300,
      iron: 3.0,
      magnesium: 80,
      phosphorus: 200,
      potassium: 500,
      sodium: 380,
      zinc: 1.2,
      copper: 0.2,
      manganese: 0.8,
      selenium: 5.0,
      fluoride: 7.0,
    },
    aminoAcids: {
      histidine: 250,
      isoleucine: 450,
      leucine: 750,
      lysine: 650,
      methionine: 200,
      phenylalanine: 400,
      threonine: 350,
      tryptophan: 100,
      valine: 500,
    },
    fattyAcids: {
      saturated: 8.0,
      monounsaturated: 4.5,
      polyunsaturated: 1.0,
      omega3: 0.3,
      omega6: 0.7,
      trans: 0.2,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    category: "Indian Dishes",
    description: "Creamy tomato-based curry with chicken pieces",
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "custom",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 200,
      unit: "g",
      description: "1 serving",
    },
    nutrients: {
      calories: 320,
      protein: 25.0,
      carbohydrates: 10.0,
      fat: 20.0,
      fiber: 2.0,
      sugar: 6.0,
      sodium: 550,
    },
    vitamins: {
      a: 800,
      c: 15.0,
      d: 0.2,
      e: 1.0,
      k: 10.0,
      b1: 0.1,
      b2: 0.2,
      b3: 8.0,
      b5: 1.0,
      b6: 0.5,
      b7: 2.0,
      b9: 20,
      b12: 0.3,
    },
    minerals: {
      calcium: 80,
      iron: 2.0,
      magnesium: 30,
      phosphorus: 200,
      potassium: 400,
      sodium: 550,
      zinc: 1.5,
      copper: 0.1,
      manganese: 0.2,
      selenium: 15.0,
      fluoride: 5.0,
    },
    aminoAcids: {
      histidine: 750,
      isoleucine: 1200,
      leucine: 2000,
      lysine: 2200,
      methionine: 650,
      phenylalanine: 1000,
      threonine: 1100,
      tryptophan: 300,
      valine: 1300,
    },
    fattyAcids: {
      saturated: 10.0,
      monounsaturated: 6.5,
      polyunsaturated: 2.0,
      omega3: 0.3,
      omega6: 1.7,
      trans: 0.4,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "sambar",
    name: "Sambar",
    category: "Indian Dishes",
    description: "South Indian lentil and vegetable stew with tamarind",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "custom",
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      amount: 150,
      unit: "g",
      description: "1 serving",
    },
    nutrients: {
      calories: 130,
      protein: 6.0,
      carbohydrates: 22.0,
      fat: 2.5,
      fiber: 6.0,
      sugar: 4.0,
      sodium: 300,
    },
    vitamins: {
      a: 600,
      c: 20.0,
      d: 0,
      e: 0.8,
      k: 15.0,
      b1: 0.15,
      b2: 0.1,
      b3: 1.0,
      b5: 0.5,
      b6: 0.2,
      b7: 1.5,
      b9: 80,
      b12: 0,
    },
    minerals: {
      calcium: 50,
      iron: 2.5,
      magnesium: 40,
      phosphorus: 120,
      potassium: 350,
      sodium: 300,
      zinc: 1.0,
      copper: 0.2,
      manganese: 0.5,
      selenium: 2.0,
      fluoride: 6.0,
    },
    aminoAcids: {
      histidine: 150,
      isoleucine: 280,
      leucine: 450,
      lysine: 400,
      methionine: 80,
      phenylalanine: 300,
      threonine: 220,
      tryptophan: 60,
      valine: 320,
    },
    fattyAcids: {
      saturated: 0.4,
      monounsaturated: 1.5,
      polyunsaturated: 0.5,
      omega3: 0.1,
      omega6: 0.4,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Add keywords to each food item
expandedFoods.forEach((food) => {
  food.keywords = generateKeywords(food)
})

// Function to populate the database with food items
async function populateDatabase() {
  console.log(`Starting to populate database with ${expandedFoods.length} food items...`)

  const batch = db.batch()
  const foodsCollection = db.collection("foods")

  // Add each food item to the batch
  for (const food of expandedFoods) {
    const docRef = foodsCollection.doc(food.id)
    batch.set(docRef, food)
  }

  // Commit the batch
  try {
    await batch.commit()
    console.log(`Successfully added ${expandedFoods.length} food items to the database!`)
  } catch (error) {
    console.error("Error adding food items to database:", error)
  }
}

// Execute the database population
populateDatabase()
  .then(() => {
    console.log("Database population process completed.")
  })
  .catch((error) => {
    console.error("Error in database population process:", error)
  })
