import { saveMealTemplate, type MealTemplate } from "../lib/meal-templates-firestore"

// Easy Indian breakfast templates
const easyIndianBreakfastTemplates: MealTemplate[] = [
  {
    name: "Poha with Peanuts and Vegetables",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "weight-gain"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
    medicalConditionsUnsafe: ["nut-allergy"],
    allergens: ["peanuts"],
    calories: 250,
    protein: 8,
    carbs: 40,
    fat: 7,
    ingredients: [
      {
        name: "Flattened rice (poha)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 180,
          protein: 4,
          carbs: 36,
          fat: 1,
        },
      },
      {
        name: "Peanuts",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 35,
          protein: 2,
          carbs: 1,
          fat: 3,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Green peas",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 15,
          protein: 1,
          carbs: 3,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mustard seeds, curry leaves, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Rinse poha, drain, and set aside. Heat oil, add mustard seeds, curry leaves, and turmeric. Add onions, peas, and peanuts. Mix in poha, salt, and lemon juice. Cook for 5 minutes.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "Central India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Bread Upma with Vegetables",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "pcod"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 220,
    protein: 7,
    carbs: 35,
    fat: 6,
    ingredients: [
      {
        name: "Whole wheat bread slices",
        quantity: "4 slices",
        nutritionalInfo: {
          calories: 160,
          protein: 6,
          carbs: 30,
          fat: 2,
        },
      },
      {
        name: "Mixed vegetables (carrots, beans, peas)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 25,
          protein: 1,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mustard seeds, curry leaves, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Cut bread into small cubes. Heat oil, add mustard seeds, curry leaves, and turmeric. Add onions and vegetables, sauté until soft. Add bread cubes and salt, mix well. Cook for 5 minutes.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Besan Chilla with Mint Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 180,
    protein: 10,
    carbs: 20,
    fat: 7,
    ingredients: [
      {
        name: "Gram flour (besan)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 8,
          carbs: 18,
          fat: 2,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Tomato, finely chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Green chili, finely chopped",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mint chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0.5,
        },
      },
    ],
    preparation:
      "Mix besan with water to make a smooth batter. Add chopped vegetables, salt, and spices. Heat a non-stick pan, pour a ladleful of batter, spread it thin. Cook until golden brown on both sides. Serve with mint chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: true,
    isHighProtein: true,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Vermicelli Upma with Vegetables",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "pcod"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 230,
    protein: 6,
    carbs: 40,
    fat: 5,
    ingredients: [
      {
        name: "Vermicelli",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 160,
          protein: 5,
          carbs: 35,
          fat: 1,
        },
      },
      {
        name: "Mixed vegetables (carrots, beans, peas)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 25,
          protein: 1,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Mustard seeds, curry leaves, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Dry roast vermicelli until light brown. Heat oil, add mustard seeds, curry leaves, and turmeric. Add onions and vegetables, sauté until soft. Add roasted vermicelli, water, and salt. Cook until vermicelli is soft and water is absorbed.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Vegetable Sandwich with Mint Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "pcod"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 250,
    protein: 8,
    carbs: 40,
    fat: 6,
    ingredients: [
      {
        name: "Whole wheat bread slices",
        quantity: "4 slices",
        nutritionalInfo: {
          calories: 160,
          protein: 6,
          carbs: 30,
          fat: 2,
        },
      },
      {
        name: "Cucumber, sliced",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Tomato, sliced",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Onion, sliced",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Mint chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0.5,
        },
      },
      {
        name: "Butter",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 35,
          protein: 0,
          carbs: 0,
          fat: 4,
        },
      },
    ],
    preparation:
      "Apply butter on bread slices. Spread mint chutney on one slice. Layer with cucumber, tomato, and onion slices. Cover with another bread slice. Cut diagonally and serve.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Sprouts Salad with Lemon Dressing",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol", "pcod"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 150,
    protein: 9,
    carbs: 25,
    fat: 2,
    ingredients: [
      {
        name: "Mixed sprouts (moong, chana)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 8,
          carbs: 22,
          fat: 1,
        },
      },
      {
        name: "Cucumber, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Tomato, chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Lemon juice",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 3,
          protein: 0.1,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Chaat masala",
        quantity: "1/2 tsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.1,
          carbs: 0.4,
          fat: 0.1,
        },
      },
    ],
    preparation:
      "Mix all sprouts and vegetables in a bowl. Add lemon juice, chaat masala, and salt. Toss well and serve immediately.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 5,
  },
  {
    name: "Daliya (Broken Wheat) Porridge",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: ["gluten-allergy"],
    allergens: ["gluten"],
    calories: 200,
    protein: 7,
    carbs: 35,
    fat: 3,
    ingredients: [
      {
        name: "Broken wheat (daliya)",
        quantity: "1/3 cup",
        nutritionalInfo: {
          calories: 150,
          protein: 6,
          carbs: 32,
          fat: 1,
        },
      },
      {
        name: "Mixed vegetables (carrots, beans, peas)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 15,
          protein: 0.7,
          carbs: 3,
          fat: 0,
        },
      },
      {
        name: "Onion, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1/2 tsp",
        nutritionalInfo: {
          calories: 20,
          protein: 0,
          carbs: 0,
          fat: 2.2,
        },
      },
      {
        name: "Cumin seeds, turmeric",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0.1,
          carbs: 0.5,
          fat: 0.3,
        },
      },
    ],
    preparation:
      "Heat oil, add cumin seeds and turmeric. Add onions and vegetables, sauté until soft. Add broken wheat and water. Cook until soft and water is absorbed. Add salt to taste.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Moong Dal Cheela with Curd",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: ["lactose-intolerance"],
    allergens: ["dairy"],
    calories: 220,
    protein: 12,
    carbs: 30,
    fat: 5,
    ingredients: [
      {
        name: "Yellow moong dal (soaked for 4 hours)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 9,
          carbs: 22,
          fat: 1,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Green chili, finely chopped",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Curd",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 2.5,
          carbs: 2.5,
          fat: 1.5,
        },
      },
    ],
    preparation:
      "Grind soaked moong dal with water to make a smooth batter. Add chopped vegetables, salt, and spices. Heat a non-stick pan, pour a ladleful of batter, spread it thin. Cook until golden brown on both sides. Serve with curd.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 15,
  },
  // Additional Indian breakfast items
  {
    name: "Ragi Dosa with Coconut Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "high-cholesterol"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 200,
    protein: 6,
    carbs: 35,
    fat: 4,
    ingredients: [
      {
        name: "Ragi flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1.5,
        },
      },
      {
        name: "Rice flour",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 0.7,
          carbs: 9,
          fat: 0.1,
        },
      },
      {
        name: "Cumin seeds",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 8,
          protein: 0.4,
          carbs: 1,
          fat: 0.5,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Coconut chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 45,
          protein: 1,
          carbs: 2,
          fat: 4,
        },
      },
    ],
    preparation:
      "Mix ragi flour, rice flour, cumin seeds, and salt with water to make a thin batter. Heat a non-stick pan, pour a ladleful of batter, spread it thin. Cook until crisp. Serve with coconut chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "easy",
    prepTime: 15,
  },
  {
    name: "Paneer Paratha with Curd",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-gain", "muscle-building"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["lactose-intolerance", "high-cholesterol"],
    allergens: ["dairy", "gluten"],
    calories: 350,
    protein: 15,
    carbs: 40,
    fat: 15,
    ingredients: [
      {
        name: "Whole wheat flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 4,
          carbs: 25,
          fat: 1,
        },
      },
      {
        name: "Paneer (cottage cheese), grated",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 180,
          protein: 10,
          carbs: 3,
          fat: 14,
        },
      },
      {
        name: "Green chilies, finely chopped",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.2,
          fat: 0,
        },
      },
      {
        name: "Coriander leaves, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.2,
          carbs: 0.4,
          fat: 0,
        },
      },
      {
        name: "Ghee",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      },
      {
        name: "Curd",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 2.5,
          carbs: 2.5,
          fat: 1.5,
        },
      },
    ],
    preparation:
      "Mix grated paneer with chopped green chilies, coriander leaves, and salt. Make small balls of wheat dough, stuff with paneer mixture, roll into parathas. Cook on a hot griddle with ghee until golden brown on both sides. Serve with curd.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 25,
  },
  {
    name: "Masala Chai with Biscuits",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["maintenance"],
    medicalConditionsSafe: [],
    medicalConditionsUnsafe: ["diabetes", "hypertension"],
    allergens: ["dairy", "gluten"],
    calories: 180,
    protein: 4,
    carbs: 30,
    fat: 5,
    ingredients: [
      {
        name: "Milk",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 3.5,
          carbs: 12,
          fat: 4.5,
        },
      },
      {
        name: "Tea leaves",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.1,
          carbs: 0.4,
          fat: 0,
        },
      },
      {
        name: "Sugar",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 16,
          protein: 0,
          carbs: 4,
          fat: 0,
        },
      },
      {
        name: "Cardamom, cinnamon, ginger",
        quantity: "to taste",
        nutritionalInfo: {
          calories: 5,
          protein: 0.1,
          carbs: 1,
          fat: 0.1,
        },
      },
      {
        name: "Biscuits",
        quantity: "2 pieces",
        nutritionalInfo: {
          calories: 80,
          protein: 1,
          carbs: 14,
          fat: 3,
        },
      },
    ],
    preparation:
      "Boil water with tea leaves, add milk and bring to a boil. Add sugar and spices, simmer for 2-3 minutes. Strain and serve hot with biscuits.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: false,
    isLowSugar: false,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 10,
  },
  // Indian snack items
  {
    name: "Bhel Puri",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes"],
    allergens: ["gluten"],
    calories: 220,
    protein: 5,
    carbs: 40,
    fat: 6,
    ingredients: [
      {
        name: "Puffed rice (murmura)",
        quantity: "2 cups",
        nutritionalInfo: {
          calories: 140,
          protein: 3,
          carbs: 30,
          fat: 0.5,
        },
      },
      {
        name: "Sev (crispy noodles)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 1,
          carbs: 5,
          fat: 2.5,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Tomato, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Tamarind chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 30,
          protein: 0.2,
          carbs: 7,
          fat: 0.1,
        },
      },
      {
        name: "Mint chutney",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0.1,
        },
      },
    ],
    preparation:
      "Mix puffed rice, sev, chopped onions, tomatoes, and coriander leaves. Add tamarind and mint chutneys, chat masala, and salt. Toss well and serve immediately.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: false,
    isLowSugar: false,
    region: "West India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Dhokla",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 180,
    protein: 6,
    carbs: 30,
    fat: 4,
    ingredients: [
      {
        name: "Gram flour (besan)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 5,
          carbs: 22,
          fat: 2,
        },
      },
      {
        name: "Yogurt",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 1.5,
          carbs: 2,
          fat: 1.5,
        },
      },
      {
        name: "Green chili-ginger paste",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0.1,
        },
      },
      {
        name: "Mustard seeds, curry leaves for tempering",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.3,
          carbs: 0.5,
          fat: 0.2,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 0.2,
        },
      },
      {
        name: "Oil",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
    ],
    preparation:
      "Mix gram flour, yogurt, water, salt, and green chili-ginger paste. Add fruit salt and mix well. Steam for 15 minutes. Prepare tempering with mustard seeds and curry leaves. Pour over dhokla, cut into pieces and serve.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "West India",
    difficulty: "medium",
    prepTime: 30,
  },
  {
    name: "Roasted Makhana (Foxnuts)",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease", "high-cholesterol", "hypertension"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 150,
    protein: 4,
    carbs: 15,
    fat: 9,
    ingredients: [
      {
        name: "Makhana (foxnuts)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 100,
          protein: 4,
          carbs: 15,
          fat: 0.5,
        },
      },
      {
        name: "Ghee or olive oil",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      },
      {
        name: "Rock salt",
        quantity: "1/4 tsp",
        nutritionalInfo: {
          calories: 0,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
      },
      {
        name: "Black pepper",
        quantity: "1/4 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.3,
          fat: 0,
        },
      },
    ],
    preparation:
      "Heat ghee or oil in a pan. Add makhana and roast on low flame until crisp. Add rock salt and black pepper. Mix well and let it cool. Store in an airtight container.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: true,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 10,
  },
]

// Add these additional breakfast templates to the easyIndianBreakfastTemplates array:

const additionalBreakfastTemplates = [
  {
    name: "Aloo Paratha with Curd",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-maintenance", "weight-gain"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes", "high-cholesterol"],
    allergens: ["dairy", "gluten"],
    calories: 350,
    protein: 10,
    carbs: 50,
    fat: 12,
    ingredients: [
      {
        name: "Whole wheat flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 4,
          carbs: 25,
          fat: 1,
        },
      },
      {
        name: "Potato, boiled and mashed",
        quantity: "2 medium",
        nutritionalInfo: {
          calories: 160,
          protein: 4,
          carbs: 36,
          fat: 0,
        },
      },
      {
        name: "Green chilies, finely chopped",
        quantity: "1-2",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Coriander leaves, chopped",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0.2,
          carbs: 0.4,
          fat: 0,
        },
      },
      {
        name: "Ghee",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 180,
          protein: 0,
          carbs: 0,
          fat: 20,
        },
      },
      {
        name: "Curd",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 60,
          protein: 4,
          carbs: 4,
          fat: 3,
        },
      },
    ],
    preparation:
      "Mix mashed potatoes with chopped green chilies, coriander leaves, and salt. Make small balls of wheat dough, stuff with potato mixture, roll into parathas. Cook on a hot griddle with ghee until golden brown on both sides. Serve with curd.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 30,
  },
  {
    name: "Idli Sambar with Coconut Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease", "thyroid"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 300,
    protein: 10,
    carbs: 55,
    fat: 5,
    ingredients: [
      {
        name: "Rice (for idli batter)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 150,
          protein: 3,
          carbs: 33,
          fat: 0,
        },
      },
      {
        name: "Urad dal (for idli batter)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 80,
          protein: 5,
          carbs: 14,
          fat: 0,
        },
      },
      {
        name: "Toor dal (for sambar)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 80,
          protein: 5,
          carbs: 14,
          fat: 0,
        },
      },
      {
        name: "Mixed vegetables (for sambar)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 1,
          carbs: 6,
          fat: 0,
        },
      },
      {
        name: "Coconut (for chutney)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 100,
          protein: 1,
          carbs: 4,
          fat: 10,
        },
      },
      {
        name: "Spices and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 2,
          fat: 3,
        },
      },
    ],
    preparation:
      "Ferment rice and urad dal batter, steam in idli molds. Prepare sambar with toor dal and vegetables. Make coconut chutney by grinding coconut with green chilies and spices.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "hard",
    prepTime: 60,
  },
  {
    name: "Puri Bhaji",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-gain", "maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes", "high-cholesterol", "heart-disease"],
    allergens: ["gluten"],
    calories: 450,
    protein: 10,
    carbs: 60,
    fat: 20,
    ingredients: [
      {
        name: "Whole wheat flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 4,
          carbs: 25,
          fat: 1,
        },
      },
      {
        name: "Potato",
        quantity: "2 medium",
        nutritionalInfo: {
          calories: 160,
          protein: 4,
          carbs: 36,
          fat: 0,
        },
      },
      {
        name: "Tomato",
        quantity: "1 medium",
        nutritionalInfo: {
          calories: 20,
          protein: 1,
          carbs: 4,
          fat: 0,
        },
      },
      {
        name: "Onion",
        quantity: "1 medium",
        nutritionalInfo: {
          calories: 40,
          protein: 1,
          carbs: 9,
          fat: 0,
        },
      },
      {
        name: "Oil for deep frying",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 200,
          protein: 0,
          carbs: 0,
          fat: 22,
        },
      },
      {
        name: "Spices",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 10,
          protein: 0,
          carbs: 2,
          fat: 0,
        },
      },
    ],
    preparation:
      "Make dough with whole wheat flour, roll into small circles, deep fry until puffed. Prepare potato curry with onions, tomatoes, and spices.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 40,
  },
  {
    name: "Uttapam with Coconut Chutney",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease", "thyroid"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 320,
    protein: 10,
    carbs: 55,
    fat: 8,
    ingredients: [
      {
        name: "Rice (for batter)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 150,
          protein: 3,
          carbs: 33,
          fat: 0,
        },
      },
      {
        name: "Urad dal (for batter)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 80,
          protein: 5,
          carbs: 14,
          fat: 0,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 20,
          protein: 0.5,
          carbs: 4.5,
          fat: 0,
        },
      },
      {
        name: "Tomato, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Green chilies, finely chopped",
        quantity: "1-2",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Coconut (for chutney)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 100,
          protein: 1,
          carbs: 4,
          fat: 10,
        },
      },
      {
        name: "Oil",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
    ],
    preparation:
      "Ferment rice and urad dal batter. Pour a ladleful on a hot griddle, sprinkle chopped vegetables, drizzle oil, cook until golden brown. Serve with coconut chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "medium",
    prepTime: 30,
  },
  {
    name: "Methi Thepla with Curd and Pickle",
    mealType: "Breakfast",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "thyroid"],
    medicalConditionsUnsafe: ["lactose-intolerance"],
    allergens: ["dairy", "gluten"],
    calories: 300,
    protein: 10,
    carbs: 40,
    fat: 10,
    ingredients: [
      {
        name: "Whole wheat flour",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 4,
          carbs: 25,
          fat: 1,
        },
      },
      {
        name: "Fenugreek leaves (methi), chopped",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 20,
          protein: 1,
          carbs: 3,
          fat: 0,
        },
      },
      {
        name: "Yogurt",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 20,
          protein: 1,
          carbs: 2,
          fat: 1,
        },
      },
      {
        name: "Spices (turmeric, cumin, coriander)",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 10,
          protein: 0,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Curd (for serving)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 60,
          protein: 4,
          carbs: 4,
          fat: 3,
        },
      },
      {
        name: "Pickle (for serving)",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 20,
          protein: 0,
          carbs: 4,
          fat: 1,
        },
      },
    ],
    preparation:
      "Mix whole wheat flour with chopped fenugreek leaves, yogurt, spices, and salt. Make a soft dough, divide into small balls, roll into thin circles. Cook on a hot griddle with oil until golden brown on both sides. Serve with curd and pickle.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "West India",
    difficulty: "medium",
    prepTime: 30,
  },
]

// Add these templates to the easyIndianBreakfastTemplates array
easyIndianBreakfastTemplates.push(...additionalBreakfastTemplates)

// Update the populateIndianMealTemplates function to include lunch, dinner, and snack templates
async function populateIndianMealTemplates() {
  try {
    console.log(`Starting to populate ${easyIndianBreakfastTemplates.length} Indian breakfast templates...`)

    for (const template of easyIndianBreakfastTemplates) {
      // Add to Firestore
      const id = await saveMealTemplate(template)
      console.log(`Added template: ${template.name} with ID: ${id}`)
    }

    // Create arrays for lunch, dinner, and snack templates
    const indianLunchTemplates = [
      {
        name: "Roti, Dal, Rice, and Mixed Vegetable Sabzi",
        mealType: "Lunch",
        dietPreference: ["vegetarian", "indian-vegetarian"],
        dietGoal: ["weight-loss", "maintenance", "weight-gain"],
        medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
        medicalConditionsUnsafe: [],
        allergens: [],
        calories: 550,
        protein: 15,
        carbs: 80,
        fat: 12,
        ingredients: [
          {
            name: "Whole wheat flour (for roti)",
            quantity: "2 rotis",
            nutritionalInfo: {
              calories: 140,
              protein: 5,
              carbs: 30,
              fat: 1,
            },
          },
          {
            name: "Toor dal",
            quantity: "1/2 cup cooked",
            nutritionalInfo: {
              calories: 120,
              protein: 7,
              carbs: 20,
              fat: 1,
            },
          },
          {
            name: "Rice",
            quantity: "1/2 cup cooked",
            nutritionalInfo: {
              calories: 120,
              protein: 2,
              carbs: 25,
              fat: 0,
            },
          },
          {
            name: "Mixed vegetables (for sabzi)",
            quantity: "1/2 cup",
            nutritionalInfo: {
              calories: 50,
              protein: 2,
              carbs: 10,
              fat: 0,
            },
          },
          {
            name: "Spices and oil",
            quantity: "As needed",
            nutritionalInfo: {
              calories: 120,
              protein: 0,
              carbs: 0,
              fat: 10,
            },
          },
        ],
        preparation:
          "Make rotis from whole wheat dough. Cook dal with spices. Prepare mixed vegetable curry. Serve with steamed rice.",
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isLowCarb: false,
        isHighProtein: false,
        isLowFat: true,
        isLowSodium: true,
        isLowSugar: true,
        region: "North India",
        difficulty: "medium",
        prepTime: 30,
      },
      {
        name: "Rajma Chawal with Roti and Raita",
        mealType: "Lunch",
        dietPreference: ["vegetarian", "indian-vegetarian"],
        dietGoal: ["weight-loss", "maintenance", "weight-gain", "muscle-building"],
        medicalConditionsSafe: ["thyroid", "heart-disease"],
        medicalConditionsUnsafe: [],
        allergens: ["dairy"],
        calories: 600,
        protein: 18,
        carbs: 90,
        fat: 15,
        ingredients: [
          {
            name: "Kidney beans (rajma)",
            quantity: "1/2 cup cooked",
            nutritionalInfo: {
              calories: 110,
              protein: 8,
              carbs: 20,
              fat: 0,
            },
          },
          {
            name: "Rice",
            quantity: "1/2 cup cooked",
            nutritionalInfo: {
              calories: 120,
              protein: 2,
              carbs: 25,
              fat: 0,
            },
          },
          {
            name: "Whole wheat flour (for roti)",
            quantity: "2 rotis",
            nutritionalInfo: {
              calories: 140,
              protein: 5,
              carbs: 30,
              fat: 1,
            },
          },
          {
            name: "Yogurt (for raita)",
            quantity: "1/4 cup",
            nutritionalInfo: {
              calories: 30,
              protein: 2,
              carbs: 2,
              fat: 2,
            },
          },
          {
            name: "Cucumber (for raita)",
            quantity: "1/4 cup",
            nutritionalInfo: {
              calories: 10,
              protein: 0,
              carbs: 2,
              fat: 0,
            },
          },
          {
            name: "Onion, tomato, spices, and oil",
            quantity: "As needed",
            nutritionalInfo: {
              calories: 190,
              protein: 1,
              carbs: 11,
              fat: 12,
            },
          },
        ],
        preparation: "Cook rajma with onion, tomato, and spices. Serve with steamed rice, rotis, and cucumber raita.",
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isLowCarb: false,
        isHighProtein: true,
        isLowFat: false,
        isLowSodium: true,
        isLowSugar: true,
        region: "North India",
        difficulty: "medium",
        prepTime: 40,
      },
    ]

    const indianDinnerTemplates = [
      {
        name: "Roti, Dal, and Seasonal Vegetable Sabzi",
        mealType: "Dinner",
        dietPreference: ["vegetarian", "indian-vegetarian"],
        dietGoal: ["weight-loss", "maintenance"],
        medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
        medicalConditionsUnsafe: [],
        allergens: ["gluten"],
        calories: 450,
        protein: 12,
        carbs: 65,
        fat: 10,
        ingredients: [
          {
            name: "Whole wheat flour (for roti)",
            quantity: "2 rotis",
            nutritionalInfo: {
              calories: 140,
              protein: 5,
              carbs: 30,
              fat: 1,
            },
          },
          {
            name: "Moong dal",
            quantity: "1/2 cup cooked",
            nutritionalInfo: {
              calories: 120,
              protein: 7,
              carbs: 20,
              fat: 0,
            },
          },
          {
            name: "Seasonal vegetables",
            quantity: "1/2 cup",
            nutritionalInfo: {
              calories: 50,
              protein: 2,
              carbs: 10,
              fat: 0,
            },
          },
          {
            name: "Spices, ghee, and oil",
            quantity: "As needed",
            nutritionalInfo: {
              calories: 140,
              protein: 0,
              carbs: 0,
              fat: 15,
            },
          },
        ],
        preparation: "Make rotis from whole wheat dough. Cook dal with spices. Prepare seasonal vegetable curry.",
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isLowCarb: false,
        isHighProtein: false,
        isLowFat: true,
        isLowSodium: true,
        isLowSugar: true,
        region: "North India",
        difficulty: "easy",
        prepTime: 30,
      },
      {
        name: "Vegetable Pulao with Raita",
        mealType: "Dinner",
        dietPreference: ["vegetarian", "indian-vegetarian"],
        dietGoal: ["weight-loss", "maintenance"],
        medicalConditionsSafe: ["thyroid"],
        medicalConditionsUnsafe: ["diabetes", "lactose-intolerance"],
        allergens: ["dairy"],
        calories: 450,
        protein: 10,
        carbs: 70,
        fat: 12,
        ingredients: [
          {
            name: "Basmati rice",
            quantity: "1/2 cup",
            nutritionalInfo: {
              calories: 170,
              protein: 3,
              carbs: 35,
              fat: 0,
            },
          },
          {
            name: "Mixed vegetables",
            quantity: "1 cup",
            nutritionalInfo: {
              calories: 80,
              protein: 3,
              carbs: 15,
              fat: 0,
            },
          },
          {
            name: "Yogurt (for raita)",
            quantity: "1/2 cup",
            nutritionalInfo: {
              calories: 60,
              protein: 4,
              carbs: 4,
              fat: 3,
            },
          },
          {
            name: "Cucumber (for raita)",
            quantity: "1/4 cup",
            nutritionalInfo: {
              calories: 10,
              protein: 0,
              carbs: 2,
              fat: 0,
            },
          },
          {
            name: "Whole spices, ghee, and oil",
            quantity: "As needed",
            nutritionalInfo: {
              calories: 130,
              protein: 0,
              carbs: 0,
              fat: 14,
            },
          },
        ],
        preparation: "Sauté vegetables with spices, add rice and water, cook until done. Serve with cucumber raita.",
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isLowCarb: false,
        isHighProtein: false,
        isLowFat: true,
        isLowSodium: true,
        isLowSugar: true,
        region: "North India",
        difficulty: "easy",
        prepTime: 25,
      },
    ]

    const indianSnackTemplates = [
      {
        name: "Masala Chai with Rusk",
        mealType: "Snack",
        dietPreference: ["vegetarian", "indian-vegetarian"],
        dietGoal: ["maintenance"],
        medicalConditionsSafe: ["thyroid"],
        medicalConditionsUnsafe: ["diabetes", "lactose-intolerance"],
        allergens: ["dairy", "gluten"],
        calories: 150,
        protein: 4,
        carbs: 25,
        fat: 4,
        ingredients: [
          {
            name: "Tea leaves",
            quantity: "1 tsp",
            nutritionalInfo: {
              calories: 2,
              protein: 0,
              carbs: 0,
              fat: 0,
            },
          },
          {
            name: "Milk",
            quantity: "1 cup",
            nutritionalInfo: {
              calories: 80,
              protein: 4,
              carbs: 6,
              fat: 4,
            },
          },
          {
            name: "Ginger",
            quantity: "1 small piece",
            nutritionalInfo: {
              calories: 3,
              protein: 0,
              carbs: 1,
              fat: 0,
            },
          },
          {
            name: "Cardamom",
            quantity: "2 pods",
            nutritionalInfo: {
              calories: 5,
              protein: 0,
              carbs: 1,
              fat: 0,
            },
          },
          {
            name: "Sugar",
            quantity: "1 tsp",
            nutritionalInfo: {
              calories: 20,
              protein: 0,
              carbs: 5,
              fat: 0,
            },
          },
          {
            name: "Rusk",
            quantity: "2 pieces",
            nutritionalInfo: {
              calories: 80,
              protein: 1,
              carbs: 15,
              fat: 2,
            },
          },
        ],
        preparation: "Boil water with tea leaves and spices, add milk and sugar, simmer. Serve with rusk.",
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isLowCarb: false,
        isHighProtein: false,
        isLowFat: true,
        isLowSodium: true,
        isLowSugar: false,
        region: "Pan-India",
        difficulty: "easy",
        prepTime: 10,
      },
      {
        name: "Bhel Puri",
        mealType: "Snack",
        dietPreference: ["vegetarian", "indian-vegetarian"],
        dietGoal: ["weight-loss", "maintenance"],
        medicalConditionsSafe: ["thyroid"],
        medicalConditionsUnsafe: ["diabetes"],
        allergens: ["gluten"],
        calories: 220,
        protein: 5,
        carbs: 40,
        fat: 6,
        ingredients: [
          {
            name: "Puffed rice (murmura)",
            quantity: "2 cups",
            nutritionalInfo: {
              calories: 140,
              protein: 3,
              carbs: 30,
              fat: 0.5,
            },
          },
          {
            name: "Sev (crispy noodles)",
            quantity: "1/4 cup",
            nutritionalInfo: {
              calories: 40,
              protein: 1,
              carbs: 5,
              fat: 2.5,
            },
          },
          {
            name: "Onion, finely chopped",
            quantity: "1/4 cup",
            nutritionalInfo: {
              calories: 10,
              protein: 0.5,
              carbs: 2,
              fat: 0,
            },
          },
          {
            name: "Tomato, finely chopped",
            quantity: "1/4 cup",
            nutritionalInfo: {
              calories: 10,
              protein: 0.5,
              carbs: 2,
              fat: 0,
            },
          },
          {
            name: "Tamarind chutney",
            quantity: "2 tbsp",
            nutritionalInfo: {
              calories: 30,
              protein: 0.2,
              carbs: 7,
              fat: 0.1,
            },
          },
          {
            name: "Mint chutney",
            quantity: "1 tbsp",
            nutritionalInfo: {
              calories: 5,
              protein: 0.2,
              carbs: 1,
              fat: 0.1,
            },
          },
        ],
        preparation:
          "Mix puffed rice, sev, chopped onions, tomatoes, and coriander leaves. Add tamarind and mint chutneys, chat masala, and salt. Toss well and serve immediately.",
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: false,
        isLowCarb: false,
        isHighProtein: false,
        isLowFat: true,
        isLowSodium: false,
        isLowSugar: false,
        region: "West India",
        difficulty: "easy",
        prepTime: 10,
      },
    ]

    // Populate lunch templates
    console.log(`Starting to populate ${indianLunchTemplates.length} Indian lunch templates...`)
    for (const template of indianLunchTemplates) {
      const id = await saveMealTemplate(template)
      console.log(`Added lunch template: ${template.name} with ID: ${id}`)
    }

    // Populate dinner templates
    console.log(`Starting to populate ${indianDinnerTemplates.length} Indian dinner templates...`)
    for (const template of indianDinnerTemplates) {
      const id = await saveMealTemplate(template)
      console.log(`Added dinner template: ${template.name} with ID: ${id}`)
    }

    // Populate snack templates
    console.log(`Starting to populate ${indianSnackTemplates.length} Indian snack templates...`)
    for (const template of indianSnackTemplates) {
      const id = await saveMealTemplate(template)
      console.log(`Added snack template: ${template.name} with ID: ${id}`)
    }

    console.log("Successfully populated Indian meal templates!")
  } catch (error) {
    console.error("Error populating Indian meal templates:", error)
  }
}

// Run the function
populateIndianMealTemplates()
