import { initializeApp } from "firebase/app"
import { getFirestore, collection, writeBatch, doc } from "firebase/firestore"

// Firebase configuration
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
}

// Initialize Firebase
const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

// NCCDB Food Database with complete micronutrient data
const nccdbFoods = [
  {
    name: "Rice, raw, milled",
    category: "Cereals and Millets",
    description: "White rice, polished, commonly consumed in India",
    nutrients: {
      // Macronutrients (per 100g)
      calories: 345,
      protein: 6.8,
      fat: 0.5,
      carbohydrates: 78.2,
      fiber: 0.2,
      sugar: 0.1,

      // Minerals (mg per 100g)
      calcium: 10,
      phosphorus: 160,
      iron: 0.7,
      sodium: 5,
      potassium: 115,
      magnesium: 23,
      zinc: 1.4,
      copper: 0.2,
      manganese: 1.1,
      selenium: 15.1, // mcg

      // Vitamins
      vitaminA: 0, // mcg RAE
      vitaminB1: 0.07, // mg (Thiamine)
      vitaminB2: 0.06, // mg (Riboflavin)
      vitaminB3: 1.6, // mg (Niacin)
      vitaminB6: 0.16, // mg
      vitaminB12: 0, // mcg
      vitaminC: 0, // mg
      vitaminD: 0, // mcg
      vitaminE: 0.11, // mg
      vitaminK: 0.1, // mcg
      folate: 8, // mcg
      biotin: 2.1, // mcg
      pantothenicAcid: 1.0, // mg

      // Amino Acids (mg per 100g)
      histidine: 154,
      isoleucine: 273,
      leucine: 518,
      lysine: 231,
      methionine: 147,
      phenylalanine: 322,
      threonine: 231,
      tryptophan: 77,
      valine: 378,

      // Fatty Acids (g per 100g)
      saturatedFat: 0.13,
      monounsaturatedFat: 0.16,
      polyunsaturatedFat: 0.16,
      omega3: 0.01,
      omega6: 0.15,
    },
    keywords: ["rice", "chawal", "white rice", "polished rice", "milled rice"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup cooked",
      amount: 158,
    },
  },
  {
    name: "Wheat flour, whole",
    category: "Cereals and Millets",
    description: "Whole wheat flour, atta, commonly used for making rotis",
    nutrients: {
      calories: 341,
      protein: 12.1,
      fat: 1.7,
      carbohydrates: 69.4,
      fiber: 11.2,
      sugar: 0.4,

      calcium: 48,
      phosphorus: 315,
      iron: 4.9,
      sodium: 2,
      potassium: 284,
      magnesium: 110,
      zinc: 2.9,
      copper: 0.4,
      manganese: 4.0,
      selenium: 42.5,

      vitaminA: 0,
      vitaminB1: 0.49,
      vitaminB2: 0.16,
      vitaminB3: 5.5,
      vitaminB6: 0.34,
      vitaminB12: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 1.01,
      vitaminK: 1.9,
      folate: 44,
      biotin: 5.9,
      pantothenicAcid: 0.95,

      histidine: 318,
      isoleucine: 434,
      leucine: 848,
      lysine: 340,
      methionine: 203,
      phenylalanine: 589,
      threonine: 371,
      tryptophan: 152,
      valine: 543,

      saturatedFat: 0.3,
      monounsaturatedFat: 0.23,
      polyunsaturatedFat: 0.78,
      omega3: 0.07,
      omega6: 0.71,
    },
    keywords: ["wheat", "atta", "flour", "whole wheat", "gehun"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: true,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup",
      amount: 120,
    },
  },
  {
    name: "Dal, arhar (Pigeon pea)",
    category: "Pulses and Legumes",
    description: "Arhar dal, toor dal, commonly consumed pulse in India",
    nutrients: {
      calories: 335,
      protein: 22.3,
      fat: 1.7,
      carbohydrates: 57.6,
      fiber: 15.5,
      sugar: 5.9,

      calcium: 73,
      phosphorus: 304,
      iron: 2.8,
      sodium: 17,
      potassium: 1392,
      magnesium: 183,
      zinc: 2.8,
      copper: 1.1,
      manganese: 1.8,
      selenium: 8.2,

      vitaminA: 29,
      vitaminB1: 0.48,
      vitaminB2: 0.19,
      vitaminB3: 2.9,
      vitaminB6: 0.28,
      vitaminB12: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 0.84,
      vitaminK: 9.0,
      folate: 173,
      biotin: 18.8,
      pantothenicAcid: 1.3,

      histidine: 678,
      isoleucine: 1018,
      leucine: 1750,
      lysine: 1626,
      methionine: 254,
      phenylalanine: 1215,
      threonine: 906,
      tryptophan: 254,
      valine: 1102,

      saturatedFat: 0.47,
      monounsaturatedFat: 0.33,
      polyunsaturatedFat: 0.68,
      omega3: 0.18,
      omega6: 0.5,
    },
    keywords: ["arhar", "toor", "dal", "pigeon pea", "tuvar"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup cooked",
      amount: 200,
    },
  },
  {
    name: "Milk, buffalo, whole",
    category: "Milk and Milk Products",
    description: "Fresh buffalo milk, commonly consumed in North India",
    nutrients: {
      calories: 117,
      protein: 4.3,
      fat: 6.9,
      carbohydrates: 5.0,
      fiber: 0,
      sugar: 5.0,

      calcium: 210,
      phosphorus: 130,
      iron: 0.2,
      sodium: 52,
      potassium: 178,
      magnesium: 14,
      zinc: 0.6,
      copper: 0.05,
      manganese: 0.004,
      selenium: 2.3,

      vitaminA: 53,
      vitaminB1: 0.05,
      vitaminB2: 0.19,
      vitaminB3: 0.11,
      vitaminB6: 0.06,
      vitaminB12: 0.36,
      vitaminC: 2.3,
      vitaminD: 0.1,
      vitaminE: 0.09,
      vitaminK: 0.3,
      folate: 6,
      biotin: 3.5,
      pantothenicAcid: 0.36,

      histidine: 119,
      isoleucine: 272,
      leucine: 442,
      lysine: 343,
      methionine: 108,
      phenylalanine: 218,
      threonine: 200,
      tryptophan: 63,
      valine: 302,

      saturatedFat: 4.6,
      monounsaturatedFat: 1.7,
      polyunsaturatedFat: 0.2,
      omega3: 0.08,
      omega6: 0.12,
    },
    keywords: ["milk", "buffalo milk", "doodh", "bhains ka doodh"],
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup",
      amount: 240,
    },
  },
  {
    name: "Chicken, broiler, meat only",
    category: "Meat, Poultry and Fish",
    description: "Chicken meat without skin, commonly consumed poultry",
    nutrients: {
      calories: 200,
      protein: 18.2,
      fat: 13.6,
      carbohydrates: 0,
      fiber: 0,
      sugar: 0,

      calcium: 13,
      phosphorus: 147,
      iron: 1.3,
      sodium: 86,
      potassium: 229,
      magnesium: 25,
      zinc: 1.3,
      copper: 0.07,
      manganese: 0.02,
      selenium: 14.4,

      vitaminA: 49,
      vitaminB1: 0.07,
      vitaminB2: 0.12,
      vitaminB3: 8.5,
      vitaminB6: 0.35,
      vitaminB12: 0.34,
      vitaminC: 1.6,
      vitaminD: 0.2,
      vitaminE: 0.27,
      vitaminK: 2.6,
      folate: 4,
      biotin: 10.0,
      pantothenicAcid: 0.91,

      histidine: 621,
      isoleucine: 1049,
      leucine: 1506,
      lysine: 1687,
      methionine: 552,
      phenylalanine: 786,
      threonine: 834,
      tryptophan: 240,
      valine: 1020,

      saturatedFat: 3.8,
      monounsaturatedFat: 5.7,
      polyunsaturatedFat: 2.9,
      omega3: 0.08,
      omega6: 2.5,
    },
    keywords: ["chicken", "murgi", "broiler", "poultry", "meat"],
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "100g serving",
      amount: 100,
    },
  },
  {
    name: "Potato, common",
    category: "Vegetables",
    description: "Common potato, aloo, widely consumed vegetable",
    nutrients: {
      calories: 97,
      protein: 1.6,
      fat: 0.1,
      carbohydrates: 22.6,
      fiber: 2.1,
      sugar: 0.8,

      calcium: 10,
      phosphorus: 40,
      iron: 0.5,
      sodium: 6,
      potassium: 421,
      magnesium: 22,
      zinc: 0.3,
      copper: 0.1,
      manganese: 0.15,
      selenium: 0.3,

      vitaminA: 2,
      vitaminB1: 0.08,
      vitaminB2: 0.02,
      vitaminB3: 1.1,
      vitaminB6: 0.3,
      vitaminB12: 0,
      vitaminC: 17.0,
      vitaminD: 0,
      vitaminE: 0.01,
      vitaminK: 2.0,
      folate: 16,
      biotin: 0.4,
      pantothenicAcid: 0.3,

      histidine: 31,
      isoleucine: 65,
      leucine: 98,
      lysine: 107,
      methionine: 27,
      phenylalanine: 72,
      threonine: 58,
      tryptophan: 24,
      valine: 86,

      saturatedFat: 0.03,
      monounsaturatedFat: 0.0,
      polyunsaturatedFat: 0.04,
      omega3: 0.01,
      omega6: 0.03,
    },
    keywords: ["potato", "aloo", "batata", "urulaikizhangu"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 medium potato",
      amount: 150,
    },
  },
  {
    name: "Onion, big",
    category: "Vegetables",
    description: "Large onion, pyaz, commonly used in Indian cooking",
    nutrients: {
      calories: 50,
      protein: 1.2,
      fat: 0.1,
      carbohydrates: 11.1,
      fiber: 1.6,
      sugar: 4.7,

      calcium: 46,
      phosphorus: 50,
      iron: 0.6,
      sodium: 3,
      potassium: 157,
      magnesium: 10,
      zinc: 0.2,
      copper: 0.04,
      manganese: 0.13,
      selenium: 0.5,

      vitaminA: 2,
      vitaminB1: 0.05,
      vitaminB2: 0.02,
      vitaminB3: 0.2,
      vitaminB6: 0.16,
      vitaminB12: 0,
      vitaminC: 11.0,
      vitaminD: 0,
      vitaminE: 0.02,
      vitaminK: 0.4,
      folate: 19,
      biotin: 0.9,
      pantothenicAcid: 0.13,

      histidine: 11,
      isoleucine: 22,
      leucine: 33,
      lysine: 56,
      methionine: 7,
      phenylalanine: 22,
      threonine: 22,
      tryptophan: 11,
      valine: 22,

      saturatedFat: 0.04,
      monounsaturatedFat: 0.01,
      polyunsaturatedFat: 0.02,
      omega3: 0.0,
      omega6: 0.02,
    },
    keywords: ["onion", "pyaz", "kanda", "vengayam"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 medium onion",
      amount: 110,
    },
  },
  {
    name: "Tomato, ripe",
    category: "Vegetables",
    description: "Ripe tomato, tamatar, commonly used vegetable",
    nutrients: {
      calories: 20,
      protein: 0.9,
      fat: 0.2,
      carbohydrates: 4.0,
      fiber: 1.2,
      sugar: 2.6,

      calcium: 48,
      phosphorus: 20,
      iron: 0.6,
      sodium: 3,
      potassium: 204,
      magnesium: 8,
      zinc: 0.1,
      copper: 0.06,
      manganese: 0.08,
      selenium: 0.0,

      vitaminA: 351,
      vitaminB1: 0.04,
      vitaminB2: 0.04,
      vitaminB3: 0.5,
      vitaminB6: 0.06,
      vitaminB12: 0,
      vitaminC: 27.0,
      vitaminD: 0,
      vitaminE: 0.38,
      vitaminK: 7.9,
      folate: 15,
      biotin: 4.0,
      pantothenicAcid: 0.09,

      histidine: 14,
      isoleucine: 18,
      leucine: 25,
      lysine: 27,
      methionine: 4,
      phenylalanine: 27,
      threonine: 34,
      tryptophan: 6,
      valine: 18,

      saturatedFat: 0.03,
      monounsaturatedFat: 0.03,
      polyunsaturatedFat: 0.08,
      omega3: 0.0,
      omega6: 0.08,
    },
    keywords: ["tomato", "tamatar", "thakkali"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 medium tomato",
      amount: 123,
    },
  },
  {
    name: "Spinach, fresh",
    category: "Green Leafy Vegetables",
    description: "Fresh spinach leaves, palak, nutrient-rich green vegetable",
    nutrients: {
      calories: 26,
      protein: 2.0,
      fat: 0.7,
      carbohydrates: 2.9,
      fiber: 0.6,
      sugar: 0.4,

      calcium: 73,
      phosphorus: 21,
      iron: 1.1,
      sodium: 7,
      potassium: 466,
      magnesium: 1.9,
      zinc: 0.4,
      copper: 0.13,
      manganese: 0.9,
      selenium: 1.0,

      vitaminA: 469,
      vitaminB1: 0.08,
      vitaminB2: 0.18,
      vitaminB3: 0.6,
      vitaminB6: 0.19,
      vitaminB12: 0,
      vitaminC: 28.0,
      vitaminD: 0,
      vitaminE: 2.03,
      vitaminK: 483.0,
      folate: 194,
      biotin: 0.7,
      pantothenicAcid: 0.07,

      histidine: 31,
      isoleucine: 147,
      leucine: 224,
      lysine: 168,
      methionine: 53,
      phenylalanine: 129,
      threonine: 122,
      tryptophan: 39,
      valine: 161,

      saturatedFat: 0.13,
      monounsaturatedFat: 0.01,
      polyunsaturatedFat: 0.17,
      omega3: 0.14,
      omega6: 0.03,
    },
    keywords: ["spinach", "palak", "keerai"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup chopped",
      amount: 30,
    },
  },
  {
    name: "Banana, ripe",
    category: "Fruits",
    description: "Ripe banana, kela, commonly consumed fruit",
    nutrients: {
      calories: 116,
      protein: 1.2,
      fat: 0.3,
      carbohydrates: 27.2,
      fiber: 0.4,
      sugar: 12.2,

      calcium: 17,
      phosphorus: 28,
      iron: 1.0,
      sodium: 1,
      potassium: 334,
      magnesium: 37,
      zinc: 0.2,
      copper: 0.16,
      manganese: 0.27,
      selenium: 1.0,

      vitaminA: 18,
      vitaminB1: 0.04,
      vitaminB2: 0.05,
      vitaminB3: 0.6,
      vitaminB6: 0.36,
      vitaminB12: 0,
      vitaminC: 7.0,
      vitaminD: 0,
      vitaminE: 0.27,
      vitaminK: 0.5,
      folate: 14,
      biotin: 4.0,
      pantothenicAcid: 0.26,

      histidine: 77,
      isoleucine: 28,
      leucine: 68,
      lysine: 50,
      methionine: 8,
      phenylalanine: 49,
      threonine: 28,
      tryptophan: 9,
      valine: 47,

      saturatedFat: 0.11,
      monounsaturatedFat: 0.03,
      polyunsaturatedFat: 0.07,
      omega3: 0.03,
      omega6: 0.05,
    },
    keywords: ["banana", "kela", "vazhaipazham"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 medium banana",
      amount: 118,
    },
  },
  {
    name: "Mango, ripe",
    category: "Fruits",
    description: "Ripe mango, aam, king of fruits",
    nutrients: {
      calories: 74,
      protein: 0.6,
      fat: 0.4,
      carbohydrates: 17.0,
      fiber: 1.8,
      sugar: 13.7,

      calcium: 15,
      phosphorus: 13,
      iron: 0.7,
      sodium: 2,
      potassium: 156,
      magnesium: 9,
      zinc: 0.04,
      copper: 0.11,
      manganese: 0.06,
      selenium: 0.6,

      vitaminA: 765,
      vitaminB1: 0.06,
      vitaminB2: 0.05,
      vitaminB3: 0.6,
      vitaminB6: 0.13,
      vitaminB12: 0,
      vitaminC: 27.7,
      vitaminD: 0,
      vitaminE: 1.12,
      vitaminK: 4.2,
      folate: 14,
      biotin: 0.3,
      pantothenicAcid: 0.16,

      histidine: 12,
      isoleucine: 21,
      leucine: 41,
      lysine: 32,
      methionine: 4,
      phenylalanine: 17,
      threonine: 23,
      tryptophan: 6,
      valine: 29,

      saturatedFat: 0.09,
      monounsaturatedFat: 0.14,
      polyunsaturatedFat: 0.07,
      omega3: 0.05,
      omega6: 0.02,
    },
    keywords: ["mango", "aam", "maanga"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup sliced",
      amount: 165,
    },
  },
  {
    name: "Coconut, kernel, fresh",
    category: "Nuts and Oilseeds",
    description: "Fresh coconut kernel, nariyal, commonly used in South Indian cuisine",
    nutrients: {
      calories: 444,
      protein: 4.0,
      fat: 41.6,
      carbohydrates: 13.0,
      fiber: 13.6,
      sugar: 6.2,

      calcium: 18,
      phosphorus: 110,
      iron: 7.0,
      sodium: 37,
      potassium: 543,
      magnesium: 37,
      zinc: 1.1,
      copper: 0.22,
      manganese: 0.92,
      selenium: 10.1,

      vitaminA: 0,
      vitaminB1: 0.03,
      vitaminB2: 0.18,
      vitaminB3: 0.9,
      vitaminB6: 0.07,
      vitaminB12: 0,
      vitaminC: 4.0,
      vitaminD: 0,
      vitaminE: 0.24,
      vitaminK: 0.2,
      folate: 26,
      biotin: 20.0,
      pantothenicAcid: 0.3,

      histidine: 95,
      isoleucine: 131,
      leucine: 243,
      lysine: 147,
      methionine: 62,
      phenylalanine: 169,
      threonine: 142,
      tryptophan: 39,
      valine: 202,

      saturatedFat: 36.9,
      monounsaturatedFat: 1.7,
      polyunsaturatedFat: 0.4,
      omega3: 0.02,
      omega6: 0.37,
    },
    keywords: ["coconut", "nariyal", "thenga", "kobbari"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup shredded",
      amount: 80,
    },
  },
  {
    name: "Mustard oil",
    category: "Fats and Oils",
    description: "Mustard seed oil, sarson ka tel, commonly used cooking oil in North India",
    nutrients: {
      calories: 884,
      protein: 0,
      fat: 100.0,
      carbohydrates: 0,
      fiber: 0,
      sugar: 0,

      calcium: 0,
      phosphorus: 0,
      iron: 0,
      sodium: 0,
      potassium: 0,
      magnesium: 0,
      zinc: 0,
      copper: 0,
      manganese: 0,
      selenium: 0,

      vitaminA: 0,
      vitaminB1: 0,
      vitaminB2: 0,
      vitaminB3: 0,
      vitaminB6: 0,
      vitaminB12: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminE: 19.1,
      vitaminK: 5.4,
      folate: 0,
      biotin: 0,
      pantothenicAcid: 0,

      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,

      saturatedFat: 11.6,
      monounsaturatedFat: 59.2,
      polyunsaturatedFat: 21.2,
      omega3: 5.9,
      omega6: 15.3,
    },
    keywords: ["mustard oil", "sarson ka tel", "kadugu ennai"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 tablespoon",
      amount: 14,
    },
  },
  {
    name: "Jaggery",
    category: "Sugar and Jaggery",
    description: "Jaggery, gur, traditional unrefined sugar",
    nutrients: {
      calories: 383,
      protein: 0.4,
      fat: 0.1,
      carbohydrates: 95.0,
      fiber: 0,
      sugar: 95.0,

      calcium: 80,
      phosphorus: 40,
      iron: 10.0,
      sodium: 8,
      potassium: 56,
      magnesium: 76,
      zinc: 0.3,
      copper: 0.3,
      manganese: 0.2,
      selenium: 1.0,

      vitaminA: 3,
      vitaminB1: 0.01,
      vitaminB2: 0.06,
      vitaminB3: 2.0,
      vitaminB6: 0.01,
      vitaminB12: 0,
      vitaminC: 7.0,
      vitaminD: 0,
      vitaminE: 0,
      vitaminK: 0,
      folate: 0,
      biotin: 0,
      pantothenicAcid: 0,

      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,

      saturatedFat: 0,
      monounsaturatedFat: 0,
      polyunsaturatedFat: 0,
      omega3: 0,
      omega6: 0,
    },
    keywords: ["jaggery", "gur", "gud", "vellam"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 tablespoon",
      amount: 20,
    },
  },
  {
    name: "Curd, buffalo milk",
    category: "Milk and Milk Products",
    description: "Curd made from buffalo milk, dahi, commonly consumed fermented dairy",
    nutrients: {
      calories: 60,
      protein: 3.1,
      fat: 4.0,
      carbohydrates: 3.0,
      fiber: 0,
      sugar: 3.0,

      calcium: 149,
      phosphorus: 93,
      iron: 0.2,
      sodium: 364,
      potassium: 104,
      magnesium: 8,
      zinc: 0.9,
      copper: 0.03,
      manganese: 0.004,
      selenium: 2.2,

      vitaminA: 99,
      vitaminB1: 0.03,
      vitaminB2: 0.13,
      vitaminB3: 0.08,
      vitaminB6: 0.03,
      vitaminB12: 0.22,
      vitaminC: 1.0,
      vitaminD: 0.04,
      vitaminE: 0.06,
      vitaminK: 0.2,
      folate: 4,
      biotin: 2.9,
      pantothenicAcid: 0.23,

      histidine: 83,
      isoleucine: 189,
      leucine: 307,
      lysine: 238,
      methionine: 75,
      phenylalanine: 151,
      threonine: 139,
      tryptophan: 44,
      valine: 210,

      saturatedFat: 2.7,
      monounsaturatedFat: 1.0,
      polyunsaturatedFat: 0.1,
      omega3: 0.04,
      omega6: 0.06,
    },
    keywords: ["curd", "dahi", "yogurt", "thayir"],
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup",
      amount: 245,
    },
  },
  {
    name: "Fish, rohu",
    category: "Meat, Poultry and Fish",
    description: "Rohu fish, commonly consumed freshwater fish in India",
    nutrients: {
      calories: 97,
      protein: 16.6,
      fat: 2.2,
      carbohydrates: 0,
      fiber: 0,
      sugar: 0,

      calcium: 220,
      phosphorus: 203,
      iron: 0.4,
      sodium: 59,
      potassium: 263,
      magnesium: 37,
      zinc: 0.6,
      copper: 0.04,
      manganese: 0.04,
      selenium: 36.5,

      vitaminA: 15,
      vitaminB1: 0.06,
      vitaminB2: 0.05,
      vitaminB3: 2.0,
      vitaminB6: 0.2,
      vitaminB12: 2.6,
      vitaminC: 0,
      vitaminD: 5.9,
      vitaminE: 0.4,
      vitaminK: 0.1,
      folate: 5,
      biotin: 5.0,
      pantothenicAcid: 0.75,

      histidine: 489,
      isoleucine: 765,
      leucine: 1349,
      lysine: 1524,
      methionine: 491,
      phenylalanine: 649,
      threonine: 728,
      tryptophan: 186,
      valine: 855,

      saturatedFat: 0.6,
      monounsaturatedFat: 0.7,
      polyunsaturatedFat: 0.6,
      omega3: 0.3,
      omega6: 0.1,
    },
    keywords: ["fish", "rohu", "machli", "meen"],
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "100g fillet",
      amount: 100,
    },
  },
  {
    name: "Egg, hen, whole",
    category: "Eggs",
    description: "Whole hen egg, anda, commonly consumed protein source",
    nutrients: {
      calories: 173,
      protein: 13.3,
      fat: 13.3,
      carbohydrates: 0.7,
      fiber: 0,
      sugar: 0.4,

      calcium: 60,
      phosphorus: 220,
      iron: 2.1,
      sodium: 177,
      potassium: 149,
      magnesium: 12,
      zinc: 1.3,
      copper: 0.11,
      manganese: 0.03,
      selenium: 20.9,

      vitaminA: 140,
      vitaminB1: 0.09,
      vitaminB2: 0.3,
      vitaminB3: 0.1,
      vitaminB6: 0.13,
      vitaminB12: 1.1,
      vitaminC: 0,
      vitaminD: 0.9,
      vitaminE: 0.97,
      vitaminK: 0.3,
      folate: 44,
      biotin: 20.2,
      pantothenicAcid: 1.4,

      histidine: 416,
      isoleucine: 686,
      leucine: 1075,
      lysine: 912,
      methionine: 392,
      phenylalanine: 680,
      threonine: 556,
      tryptophan: 167,
      valine: 767,

      saturatedFat: 4.3,
      monounsaturatedFat: 5.7,
      polyunsaturatedFat: 1.9,
      omega3: 0.04,
      omega6: 1.6,
    },
    keywords: ["egg", "anda", "muttai"],
    isVegetarian: false,
    isVegan: false,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 large egg",
      amount: 50,
    },
  },
  {
    name: "Green gram, whole",
    category: "Pulses and Legumes",
    description: "Whole green gram, moong dal, nutritious pulse",
    nutrients: {
      calories: 334,
      protein: 24.5,
      fat: 1.2,
      carbohydrates: 59.9,
      fiber: 16.3,
      sugar: 6.6,

      calcium: 132,
      phosphorus: 367,
      iron: 6.7,
      sodium: 15,
      potassium: 1246,
      magnesium: 189,
      zinc: 2.7,
      copper: 0.9,
      manganese: 1.0,
      selenium: 8.2,

      vitaminA: 114,
      vitaminB1: 0.62,
      vitaminB2: 0.23,
      vitaminB3: 2.3,
      vitaminB6: 0.38,
      vitaminB12: 0,
      vitaminC: 4.8,
      vitaminD: 0,
      vitaminE: 0.51,
      vitaminK: 9.0,
      folate: 625,
      biotin: 19.0,
      pantothenicAcid: 1.9,

      histidine: 710,
      isoleucine: 1096,
      leucine: 1928,
      lysine: 1789,
      methionine: 274,
      phenylalanine: 1215,
      threonine: 1002,
      tryptophan: 274,
      valine: 1215,

      saturatedFat: 0.35,
      monounsaturatedFat: 0.19,
      polyunsaturatedFat: 0.38,
      omega3: 0.18,
      omega6: 0.2,
    },
    keywords: ["green gram", "moong", "mung bean", "pachai payaru"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup cooked",
      amount: 202,
    },
  },
  {
    name: "Black gram, whole",
    category: "Pulses and Legumes",
    description: "Whole black gram, urad dal, protein-rich pulse",
    nutrients: {
      calories: 347,
      protein: 25.2,
      fat: 1.6,
      carbohydrates: 58.5,
      fiber: 18.3,
      sugar: 2.8,

      calcium: 154,
      phosphorus: 385,
      iron: 7.6,
      sodium: 38,
      potassium: 983,
      magnesium: 267,
      zinc: 3.2,
      copper: 1.1,
      manganese: 1.4,
      selenium: 2.2,

      vitaminA: 38,
      vitaminB1: 0.42,
      vitaminB2: 0.25,
      vitaminB3: 1.8,
      vitaminB6: 0.28,
      vitaminB12: 0,
      vitaminC: 3.0,
      vitaminD: 0,
      vitaminE: 0.6,
      vitaminK: 5.0,
      folate: 216,
      biotin: 15.0,
      pantothenicAcid: 1.0,

      histidine: 680,
      isoleucine: 1134,
      leucine: 1764,
      lysine: 1638,
      methionine: 252,
      phenylalanine: 1260,
      threonine: 882,
      tryptophan: 252,
      valine: 1134,

      saturatedFat: 0.45,
      monounsaturatedFat: 0.24,
      polyunsaturatedFat: 0.51,
      omega3: 0.19,
      omega6: 0.32,
    },
    keywords: ["black gram", "urad", "black lentil", "ulundu"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup cooked",
      amount: 198,
    },
  },
  {
    name: "Cauliflower",
    category: "Vegetables",
    description: "Cauliflower, gobi, commonly consumed cruciferous vegetable",
    nutrients: {
      calories: 30,
      protein: 3.0,
      fat: 0.4,
      carbohydrates: 4.0,
      fiber: 2.0,
      sugar: 1.9,

      calcium: 33,
      phosphorus: 57,
      iron: 1.5,
      sodium: 36,
      potassium: 138,
      magnesium: 22,
      zinc: 0.3,
      copper: 0.04,
      manganese: 0.16,
      selenium: 0.6,

      vitaminA: 19,
      vitaminB1: 0.04,
      vitaminB2: 0.11,
      vitaminB3: 0.7,
      vitaminB6: 0.18,
      vitaminB12: 0,
      vitaminC: 56.0,
      vitaminD: 0,
      vitaminE: 0.08,
      vitaminK: 15.5,
      folate: 18,
      biotin: 1.5,
      pantothenicAcid: 0.65,

      histidine: 66,
      isoleucine: 156,
      leucine: 198,
      lysine: 195,
      methionine: 48,
      phenylalanine: 129,
      threonine: 129,
      tryptophan: 39,
      valine: 198,

      saturatedFat: 0.09,
      monounsaturatedFat: 0.03,
      polyunsaturatedFat: 0.2,
      omega3: 0.04,
      omega6: 0.16,
    },
    keywords: ["cauliflower", "gobi", "phool gobi"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 cup chopped",
      amount: 100,
    },
  },
  {
    name: "Carrot, orange",
    category: "Vegetables",
    description: "Orange carrot, gajar, vitamin A rich root vegetable",
    nutrients: {
      calories: 48,
      protein: 0.9,
      fat: 0.2,
      carbohydrates: 10.6,
      fiber: 2.8,
      sugar: 4.7,

      calcium: 80,
      phosphorus: 53,
      iron: 2.2,
      sodium: 35,
      potassium: 138,
      magnesium: 14,
      zinc: 0.4,
      copper: 0.04,
      manganese: 0.13,
      selenium: 0.1,

      vitaminA: 1890,
      vitaminB1: 0.04,
      vitaminB2: 0.05,
      vitaminB3: 0.6,
      vitaminB6: 0.13,
      vitaminB12: 0,
      vitaminC: 3.0,
      vitaminD: 0,
      vitaminE: 0.66,
      vitaminK: 13.2,
      folate: 19,
      biotin: 6.0,
      pantothenicAcid: 0.27,

      histidine: 25,
      isoleucine: 43,
      leucine: 64,
      lysine: 58,
      methionine: 12,
      phenylalanine: 37,
      threonine: 46,
      tryptophan: 9,
      valine: 46,

      saturatedFat: 0.04,
      monounsaturatedFat: 0.01,
      polyunsaturatedFat: 0.12,
      omega3: 0.0,
      omega6: 0.12,
    },
    keywords: ["carrot", "gajar", "carrot orange"],
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    region: "All India",
    cuisine: "Indian",
    standardPortion: {
      description: "1 medium carrot",
      amount: 61,
    },
  },
]

async function populateNCCDBFoods() {
  console.log("Starting NCCDB food database population...")

  try {
    // Use batch writes for better performance
    const batchSize = 500
    let batch = writeBatch(db)
    let operationCount = 0

    for (let i = 0; i < nccdbFoods.length; i++) {
      const food = nccdbFoods[i]

      // Create a document reference
      const docRef = doc(collection(db, "nccdb_foods"))

      // Add to batch
      batch.set(docRef, {
        ...food,
        createdAt: new Date(),
        updatedAt: new Date(),
        source: "nccdb",
        dataVersion: "2024",
      })

      operationCount++

      // Commit batch when it reaches the limit or at the end
      if (operationCount === batchSize || i === nccdbFoods.length - 1) {
        await batch.commit()
        console.log(`Committed batch of ${operationCount} foods`)

        // Create a new batch for the next set of operations
        batch = writeBatch(db)
        operationCount = 0
      }
    }

    console.log(`Successfully added ${nccdbFoods.length} NCCDB foods to Firestore!`)
  } catch (error) {
    console.error("Error populating NCCDB foods:", error)
  }
}

// Run the population script
populateNCCDBFoods()
  .then(() => {
    console.log("NCCDB food database population completed!")
    process.exit(0)
  })
  .catch((error) => {
    console.error("Failed to populate NCCDB foods:", error)
    process.exit(1)
  })
