import { saveMealTemplate, type MealTemplate } from "../lib/meal-templates-firestore"

// Indian vegetarian lunch templates
const indianVegetarianLunchTemplates: MealTemplate[] = [
  {
    name: "Roti, Dal, Rice, and Mixed Vegetable Sabzi",
    mealType: "Lunch",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "weight-gain"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 550,
    protein: 15,
    carbs: 80,
    fat: 12,
    ingredients: [
      {
        name: "Whole wheat flour (for roti)",
        quantity: "2 rotis",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1,
        },
      },
      {
        name: "Toor dal",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 7,
          carbs: 20,
          fat: 1,
        },
      },
      {
        name: "Rice",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 0,
        },
      },
      {
        name: "Mixed vegetables (for sabzi)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 50,
          protein: 2,
          carbs: 10,
          fat: 0,
        },
      },
      {
        name: "Spices and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 0,
          fat: 10,
        },
      },
    ],
    preparation:
      "Make rotis from whole wheat dough. Cook dal with spices. Prepare mixed vegetable curry. Serve with steamed rice.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 30,
  },
  {
    name: "Rajma Chawal with Roti and Raita",
    mealType: "Lunch",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "weight-gain", "muscle-building"],
    medicalConditionsSafe: ["thyroid", "heart-disease"],
    medicalConditionsUnsafe: [],
    allergens: ["dairy"],
    calories: 600,
    protein: 18,
    carbs: 90,
    fat: 15,
    ingredients: [
      {
        name: "Kidney beans (rajma)",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 110,
          protein: 8,
          carbs: 20,
          fat: 0,
        },
      },
      {
        name: "Rice",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 0,
        },
      },
      {
        name: "Whole wheat flour (for roti)",
        quantity: "2 rotis",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1,
        },
      },
      {
        name: "Yogurt (for raita)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 2,
          carbs: 2,
          fat: 2,
        },
      },
      {
        name: "Cucumber (for raita)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Onion, tomato, spices, and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 190,
          protein: 1,
          carbs: 11,
          fat: 12,
        },
      },
    ],
    preparation: "Cook rajma with onion, tomato, and spices. Serve with steamed rice, rotis, and cucumber raita.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 40,
  },
  {
    name: "Chole Bhature with Pickle and Onions",
    mealType: "Lunch",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-gain", "maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes", "high-cholesterol"],
    allergens: ["gluten"],
    calories: 700,
    protein: 20,
    carbs: 100,
    fat: 25,
    ingredients: [
      {
        name: "Chickpeas (chole)",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 7,
          carbs: 22,
          fat: 2,
        },
      },
      {
        name: "All-purpose flour (for bhature)",
        quantity: "2 bhature",
        nutritionalInfo: {
          calories: 300,
          protein: 8,
          carbs: 50,
          fat: 10,
        },
      },
      {
        name: "Onion and tomato",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 1,
          carbs: 7,
          fat: 0,
        },
      },
      {
        name: "Pickle",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 20,
          protein: 0,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Onion salad",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 20,
          protein: 0,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Spices and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 210,
          protein: 0,
          carbs: 0,
          fat: 23,
        },
      },
    ],
    preparation:
      "Cook chickpeas with onion, tomato, and spices. Make bhature dough, deep fry. Serve with pickle and onion salad.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: false,
    isLowSugar: true,
    region: "North India",
    difficulty: "hard",
    prepTime: 60,
  },
  {
    name: "Palak Paneer with Roti and Jeera Rice",
    mealType: "Lunch",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["thyroid", "heart-disease"],
    medicalConditionsUnsafe: ["lactose-intolerance"],
    allergens: ["dairy", "gluten"],
    calories: 550,
    protein: 20,
    carbs: 70,
    fat: 18,
    ingredients: [
      {
        name: "Spinach (palak)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 3,
          carbs: 7,
          fat: 0,
        },
      },
      {
        name: "Cottage cheese (paneer)",
        quantity: "50g",
        nutritionalInfo: {
          calories: 120,
          protein: 10,
          carbs: 2,
          fat: 8,
        },
      },
      {
        name: "Whole wheat flour (for roti)",
        quantity: "2 rotis",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1,
        },
      },
      {
        name: "Rice",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 0,
        },
      },
      {
        name: "Cumin seeds",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 10,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Spices, cream, and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 5,
          fat: 9,
        },
      },
    ],
    preparation:
      "Blanch spinach, blend, cook with spices. Add paneer cubes. Make rotis. Prepare jeera rice with cumin tempering.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 45,
  },
  {
    name: "Dal Khichdi with Kadhi and Papad",
    mealType: "Lunch",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "easy-digestion"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "ibs"],
    medicalConditionsUnsafe: ["lactose-intolerance"],
    allergens: ["dairy"],
    calories: 500,
    protein: 15,
    carbs: 80,
    fat: 10,
    ingredients: [
      {
        name: "Rice",
        quantity: "1/3 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 0,
        },
      },
      {
        name: "Moong dal",
        quantity: "1/3 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 9,
          carbs: 20,
          fat: 0,
        },
      },
      {
        name: "Yogurt (for kadhi)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 60,
          protein: 4,
          carbs: 4,
          fat: 3,
        },
      },
      {
        name: "Gram flour (besan)",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 60,
          protein: 3,
          carbs: 10,
          fat: 1,
        },
      },
      {
        name: "Papad",
        quantity: "1",
        nutritionalInfo: {
          calories: 40,
          protein: 1,
          carbs: 8,
          fat: 0,
        },
      },
      {
        name: "Spices, ghee, and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 100,
          protein: 0,
          carbs: 0,
          fat: 11,
        },
      },
    ],
    preparation:
      "Cook rice and dal together with spices. Prepare kadhi by cooking besan and yogurt mixture with spices. Roast papad.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 30,
  },
]

// Indian vegetarian dinner templates
const indianVegetarianDinnerTemplates: MealTemplate[] = [
  {
    name: "Roti, Dal, and Seasonal Vegetable Sabzi",
    mealType: "Dinner",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
    medicalConditionsUnsafe: [],
    allergens: ["gluten"],
    calories: 450,
    protein: 12,
    carbs: 65,
    fat: 10,
    ingredients: [
      {
        name: "Whole wheat flour (for roti)",
        quantity: "2 rotis",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1,
        },
      },
      {
        name: "Moong dal",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 7,
          carbs: 20,
          fat: 0,
        },
      },
      {
        name: "Seasonal vegetables",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 50,
          protein: 2,
          carbs: 10,
          fat: 0,
        },
      },
      {
        name: "Spices, ghee, and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 140,
          protein: 0,
          carbs: 0,
          fat: 15,
        },
      },
    ],
    preparation: "Make rotis from whole wheat dough. Cook dal with spices. Prepare seasonal vegetable curry.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 30,
  },
  {
    name: "Vegetable Pulao with Raita",
    mealType: "Dinner",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes", "lactose-intolerance"],
    allergens: ["dairy"],
    calories: 450,
    protein: 10,
    carbs: 70,
    fat: 12,
    ingredients: [
      {
        name: "Basmati rice",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 170,
          protein: 3,
          carbs: 35,
          fat: 0,
        },
      },
      {
        name: "Mixed vegetables",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 80,
          protein: 3,
          carbs: 15,
          fat: 0,
        },
      },
      {
        name: "Yogurt (for raita)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 60,
          protein: 4,
          carbs: 4,
          fat: 3,
        },
      },
      {
        name: "Cucumber (for raita)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Whole spices, ghee, and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 130,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      },
    ],
    preparation: "Sauté vegetables with spices, add rice and water, cook until done. Serve with cucumber raita.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 25,
  },
  {
    name: "Masala Dosa with Sambar and Coconut Chutney",
    mealType: "Dinner",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "heart-disease"],
    medicalConditionsUnsafe: ["diabetes"],
    allergens: [],
    calories: 500,
    protein: 12,
    carbs: 80,
    fat: 15,
    ingredients: [
      {
        name: "Rice (for dosa batter)",
        quantity: "1 dosa",
        nutritionalInfo: {
          calories: 150,
          protein: 3,
          carbs: 30,
          fat: 2,
        },
      },
      {
        name: "Urad dal (for dosa batter)",
        quantity: "Part of dosa",
        nutritionalInfo: {
          calories: 50,
          protein: 3,
          carbs: 9,
          fat: 0,
        },
      },
      {
        name: "Potato (for filling)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 80,
          protein: 2,
          carbs: 18,
          fat: 0,
        },
      },
      {
        name: "Toor dal (for sambar)",
        quantity: "1/4 cup cooked",
        nutritionalInfo: {
          calories: 60,
          protein: 4,
          carbs: 10,
          fat: 0,
        },
      },
      {
        name: "Vegetables (for sambar)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 1,
          carbs: 6,
          fat: 0,
        },
      },
      {
        name: "Coconut (for chutney)",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 70,
          protein: 1,
          carbs: 3,
          fat: 7,
        },
      },
      {
        name: "Spices and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 60,
          protein: 0,
          carbs: 0,
          fat: 6,
        },
      },
    ],
    preparation:
      "Ferment rice and dal batter, make thin crepes. Prepare potato filling with spices. Serve with sambar and coconut chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "South India",
    difficulty: "hard",
    prepTime: 60,
  },
  {
    name: "Paneer Butter Masala with Roti and Jeera Rice",
    mealType: "Dinner",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-gain", "maintenance", "muscle-building"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["high-cholesterol", "lactose-intolerance"],
    allergens: ["dairy", "gluten"],
    calories: 650,
    protein: 25,
    carbs: 70,
    fat: 30,
    ingredients: [
      {
        name: "Cottage cheese (paneer)",
        quantity: "100g",
        nutritionalInfo: {
          calories: 240,
          protein: 18,
          carbs: 4,
          fat: 16,
        },
      },
      {
        name: "Tomato",
        quantity: "1/2 cup puree",
        nutritionalInfo: {
          calories: 30,
          protein: 1,
          carbs: 6,
          fat: 0,
        },
      },
      {
        name: "Cream",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 60,
          protein: 0,
          carbs: 1,
          fat: 6,
        },
      },
      {
        name: "Butter",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 100,
          protein: 0,
          carbs: 0,
          fat: 11,
        },
      },
      {
        name: "Whole wheat flour (for roti)",
        quantity: "2 rotis",
        nutritionalInfo: {
          calories: 140,
          protein: 5,
          carbs: 30,
          fat: 1,
        },
      },
      {
        name: "Rice",
        quantity: "1/2 cup cooked",
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 0,
        },
      },
      {
        name: "Spices and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 60,
          protein: 0,
          carbs: 0,
          fat: 6,
        },
      },
    ],
    preparation:
      "Cook tomato gravy with spices, add paneer and cream. Make rotis. Prepare jeera rice with cumin tempering.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: true,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 40,
  },
  {
    name: "Vegetable Khichdi with Kadhi",
    mealType: "Dinner",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance", "easy-digestion"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease", "ibs"],
    medicalConditionsUnsafe: ["lactose-intolerance"],
    allergens: ["dairy"],
    calories: 450,
    protein: 12,
    carbs: 70,
    fat: 10,
    ingredients: [
      {
        name: "Rice",
        quantity: "1/3 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 0,
        },
      },
      {
        name: "Moong dal",
        quantity: "1/3 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 7,
          carbs: 20,
          fat: 0,
        },
      },
      {
        name: "Mixed vegetables",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 50,
          protein: 2,
          carbs: 10,
          fat: 0,
        },
      },
      {
        name: "Yogurt (for kadhi)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 60,
          protein: 4,
          carbs: 4,
          fat: 3,
        },
      },
      {
        name: "Gram flour (besan)",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 60,
          protein: 3,
          carbs: 10,
          fat: 1,
        },
      },
      {
        name: "Spices, ghee, and oil",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 60,
          protein: 0,
          carbs: 0,
          fat: 6,
        },
      },
    ],
    preparation:
      "Cook rice, dal, and vegetables together with spices. Prepare kadhi by cooking besan and yogurt mixture with spices.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 30,
  },
]

// Indian vegetarian snack templates
const indianVegetarianSnackTemplates: MealTemplate[] = [
  {
    name: "Masala Chai with Rusk",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes", "lactose-intolerance"],
    allergens: ["dairy", "gluten"],
    calories: 150,
    protein: 4,
    carbs: 25,
    fat: 4,
    ingredients: [
      {
        name: "Tea leaves",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 2,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
      },
      {
        name: "Milk",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 80,
          protein: 4,
          carbs: 6,
          fat: 4,
        },
      },
      {
        name: "Ginger",
        quantity: "1 small piece",
        nutritionalInfo: {
          calories: 3,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Cardamom",
        quantity: "2 pods",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Sugar",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 20,
          protein: 0,
          carbs: 5,
          fat: 0,
        },
      },
      {
        name: "Rusk",
        quantity: "2 pieces",
        nutritionalInfo: {
          calories: 80,
          protein: 1,
          carbs: 15,
          fat: 2,
        },
      },
    ],
    preparation: "Boil water with tea leaves and spices, add milk and sugar, simmer. Serve with rusk.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: false,
    region: "Pan-India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Dhokla with Green Chutney",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "thyroid", "heart-disease"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 180,
    protein: 6,
    carbs: 30,
    fat: 5,
    ingredients: [
      {
        name: "Gram flour (besan)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 120,
          protein: 6,
          carbs: 20,
          fat: 2,
        },
      },
      {
        name: "Yogurt",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 20,
          protein: 1,
          carbs: 2,
          fat: 1,
        },
      },
      {
        name: "Eno fruit salt",
        quantity: "1/2 tsp",
        nutritionalInfo: {
          calories: 0,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
      },
      {
        name: "Green chilies",
        quantity: "1-2",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
      {
        name: "Mustard seeds (for tempering)",
        quantity: "1 tsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
      },
      {
        name: "Oil",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 40,
          protein: 0,
          carbs: 0,
          fat: 4.5,
        },
      },
      {
        name: "Coriander leaves (for chutney)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation: "Mix besan with yogurt and water, ferment, add Eno, steam. Prepare tempering and green chutney.",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: true,
    isLowSugar: true,
    region: "West India",
    difficulty: "medium",
    prepTime: 30,
  },
  {
    name: "Bhel Puri",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid"],
    medicalConditionsUnsafe: ["diabetes"],
    allergens: ["gluten"],
    calories: 220,
    protein: 5,
    carbs: 40,
    fat: 6,
    ingredients: [
      {
        name: "Puffed rice (murmura)",
        quantity: "2 cups",
        nutritionalInfo: {
          calories: 140,
          protein: 3,
          carbs: 30,
          fat: 0.5,
        },
      },
      {
        name: "Sev (crispy noodles)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 1,
          carbs: 5,
          fat: 2.5,
        },
      },
      {
        name: "Onion, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Tomato, finely chopped",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 10,
          protein: 0.5,
          carbs: 2,
          fat: 0,
        },
      },
      {
        name: "Tamarind chutney",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 30,
          protein: 0.2,
          carbs: 7,
          fat: 0.1,
        },
      },
      {
        name: "Mint chutney",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 5,
          protein: 0.2,
          carbs: 1,
          fat: 0.1,
        },
      },
    ],
    preparation:
      "Mix puffed rice, sev, chopped onions, tomatoes, and coriander leaves. Add tamarind and mint chutneys, chat masala, and salt. Toss well and serve immediately.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: true,
    isLowSodium: false,
    isLowSugar: false,
    region: "West India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Roasted Makhana (Foxnuts)",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian", "vegan", "gluten-free"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["diabetes", "heart-disease", "high-cholesterol", "hypertension"],
    medicalConditionsUnsafe: [],
    allergens: [],
    calories: 150,
    protein: 4,
    carbs: 15,
    fat: 9,
    ingredients: [
      {
        name: "Makhana (foxnuts)",
        quantity: "1 cup",
        nutritionalInfo: {
          calories: 100,
          protein: 4,
          carbs: 15,
          fat: 0.5,
        },
      },
      {
        name: "Ghee or olive oil",
        quantity: "1 tbsp",
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      },
      {
        name: "Rock salt",
        quantity: "1/4 tsp",
        nutritionalInfo: {
          calories: 0,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
      },
      {
        name: "Black pepper",
        quantity: "1/4 tsp",
        nutritionalInfo: {
          calories: 1,
          protein: 0.1,
          carbs: 0.3,
          fat: 0,
        },
      },
    ],
    preparation:
      "Heat ghee or oil in a pan. Add makhana and roast on low flame until crisp. Add rock salt and black pepper. Mix well and let it cool. Store in an airtight container.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLowCarb: true,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "easy",
    prepTime: 10,
  },
  {
    name: "Vegetable Cutlet with Mint Chutney",
    mealType: "Snack",
    dietPreference: ["vegetarian", "indian-vegetarian"],
    dietGoal: ["weight-loss", "maintenance"],
    medicalConditionsSafe: ["thyroid", "heart-disease"],
    medicalConditionsUnsafe: ["diabetes"],
    allergens: ["gluten"],
    calories: 200,
    protein: 5,
    carbs: 30,
    fat: 8,
    ingredients: [
      {
        name: "Potato",
        quantity: "1 medium",
        nutritionalInfo: {
          calories: 100,
          protein: 2,
          carbs: 20,
          fat: 0,
        },
      },
      {
        name: "Mixed vegetables (carrot, peas, beans)",
        quantity: "1/2 cup",
        nutritionalInfo: {
          calories: 30,
          protein: 2,
          carbs: 6,
          fat: 0,
        },
      },
      {
        name: "Bread crumbs",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 40,
          protein: 1,
          carbs: 8,
          fat: 0.5,
        },
      },
      {
        name: "Spices (garam masala, cumin, coriander)",
        quantity: "As needed",
        nutritionalInfo: {
          calories: 10,
          protein: 0,
          carbs: 2,
          fat: 0.5,
        },
      },
      {
        name: "Oil for shallow frying",
        quantity: "2 tbsp",
        nutritionalInfo: {
          calories: 80,
          protein: 0,
          carbs: 0,
          fat: 9,
        },
      },
      {
        name: "Mint and coriander leaves (for chutney)",
        quantity: "1/4 cup",
        nutritionalInfo: {
          calories: 5,
          protein: 0.5,
          carbs: 1,
          fat: 0,
        },
      },
    ],
    preparation:
      "Mash boiled vegetables with spices, shape into patties, coat with bread crumbs, shallow fry. Serve with mint chutney.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLowCarb: false,
    isHighProtein: false,
    isLowFat: false,
    isLowSodium: true,
    isLowSugar: true,
    region: "North India",
    difficulty: "medium",
    prepTime: 25,
  },
]

// Function to populate meal templates
async function populateMoreIndianMealTemplates() {
  try {
    console.log(`Starting to populate ${indianVegetarianLunchTemplates.length} Indian lunch templates...`)

    for (const template of indianVegetarianLunchTemplates) {
      // Add to Firestore
      const id = await saveMealTemplate(template)
      console.log(`Added lunch template: ${template.name} with ID: ${id}`)
    }

    console.log(`Starting to populate ${indianVegetarianDinnerTemplates.length} Indian dinner templates...`)

    for (const template of indianVegetarianDinnerTemplates) {
      // Add to Firestore
      const id = await saveMealTemplate(template)
      console.log(`Added dinner template: ${template.name} with ID: ${id}`)
    }

    console.log(`Starting to populate ${indianVegetarianSnackTemplates.length} Indian snack templates...`)

    for (const template of indianVegetarianSnackTemplates) {
      // Add to Firestore
      const id = await saveMealTemplate(template)
      console.log(`Added snack template: ${template.name} with ID: ${id}`)
    }

    console.log("Successfully populated additional Indian meal templates!")
  } catch (error) {
    console.error("Error populating Indian meal templates:", error)
  }
}

// Run the function
populateMoreIndianMealTemplates()
