/**
 * Detailed Food Database Population Script
 *
 * This script populates the Firestore database with comprehensive nutritional data
 * for common food items, including macronutrients, vitamins, minerals, amino acids,
 * and fatty acids.
 *
 * Usage:
 * 1. Set up your Firebase credentials in your environment
 * 2. Run this script with: npx ts-node scripts/populate-detailed-food-database.ts
 */

import { initializeApp, cert } from "firebase-admin/app"
import { getFirestore } from "firebase-admin/firestore"

// Initialize Firebase Admin
const serviceAccount = process.env.FIREBASE_PRIVATE_KEY
  ? {
      projectId: process.env.FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, "\n"),
    }
  : require("../serviceAccountKey.json")

initializeApp({
  credential: cert(serviceAccount as any),
})

const db = getFirestore()

// Define the food item interface with detailed nutritional information
interface DetailedFoodItem {
  id: string
  name: string
  category: string
  description?: string
  isVegetarian: boolean
  isVegan: boolean
  containsGluten?: boolean
  containsOnionGarlic?: boolean
  containsRootVegetables?: boolean
  source: "ifct" | "usda" | "custom"
  region?: string
  cuisine?: string
  standardPortion: {
    amount: number
    unit: string
    description?: string
  }
  nutrients: {
    calories: number
    protein: number
    carbohydrates: number
    fat: number
    fiber: number
    sugar: number
    sodium: number
  }
  vitamins?: {
    a: number // IU
    c: number // mg
    d: number // IU
    e: number // mg
    k: number // mcg
    b1: number // mg (Thiamine)
    b2: number // mg (Riboflavin)
    b3: number // mg (Niacin)
    b5: number // mg (Pantothenic Acid)
    b6: number // mg (Pyridoxine)
    b7: number // mcg (Biotin)
    b9: number // mcg (Folate)
    b12: number // mcg (Cobalamin)
  }
  minerals?: {
    calcium: number // mg
    iron: number // mg
    magnesium: number // mg
    phosphorus: number // mg
    potassium: number // mg
    sodium: number // mg
    zinc: number // mg
    copper: number // mg
    manganese: number // mg
    selenium: number // mcg
    fluoride: number // mg
  }
  aminoAcids?: {
    histidine: number // mg
    isoleucine: number // mg
    leucine: number // mg
    lysine: number // mg
    methionine: number // mg
    phenylalanine: number // mg
    threonine: number // mg
    tryptophan: number // mg
    valine: number // mg
  }
  fattyAcids?: {
    saturated: number // g
    monounsaturated: number // g
    polyunsaturated: number // g
    omega3: number // g
    omega6: number // g
    trans: number // g
  }
  keywords: string[]
  createdAt: string
  updatedAt: string
}

// Generate keywords for better searching
function generateKeywords(food: DetailedFoodItem): string[] {
  const keywords = new Set<string>()

  // Add name words
  food.name
    .toLowerCase()
    .split(/\s+/)
    .forEach((word) => {
      if (word.length > 2) keywords.add(word)
    })

  // Add category
  keywords.add(food.category.toLowerCase())

  // Add region if available
  if (food.region) {
    keywords.add(food.region.toLowerCase())
  }

  // Add cuisine if available
  if (food.cuisine) {
    keywords.add(food.cuisine.toLowerCase())
  }

  // Add dietary keywords
  if (food.isVegetarian) keywords.add("vegetarian")
  if (food.isVegan) keywords.add("vegan")
  if (food.containsGluten === false) keywords.add("gluten-free")
  if (food.containsOnionGarlic === false) keywords.add("no-onion-garlic")

  return Array.from(keywords)
}

// Comprehensive food database with detailed nutritional information
const detailedFoods: DetailedFoodItem[] = [
  // GRAINS AND CEREALS
  {
    id: "rice-white-cooked",
    name: "White Rice (Cooked)",
    category: "Grains",
    description: "Plain cooked white rice, a staple in many cuisines",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 130,
      protein: 2.7,
      carbohydrates: 28.2,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0.1,
      sodium: 1,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0,
      b1: 0.02,
      b2: 0.01,
      b3: 0.4,
      b5: 0.4,
      b6: 0.05,
      b7: 0.6,
      b9: 2,
      b12: 0,
    },
    minerals: {
      calcium: 10,
      iron: 0.2,
      magnesium: 12,
      phosphorus: 43,
      potassium: 35,
      sodium: 1,
      zinc: 0.8,
      copper: 0.1,
      manganese: 0.5,
      selenium: 7.5,
      fluoride: 8.4,
    },
    aminoAcids: {
      histidine: 59,
      isoleucine: 111,
      leucine: 202,
      lysine: 92,
      methionine: 58,
      phenylalanine: 129,
      threonine: 89,
      tryptophan: 31,
      valine: 150,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.1,
      omega3: 0.01,
      omega6: 0.09,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rice-brown-cooked",
    name: "Brown Rice (Cooked)",
    category: "Grains",
    description: "Whole grain brown rice with bran layer intact, providing more fiber and nutrients",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 112,
      protein: 2.6,
      carbohydrates: 23.5,
      fat: 0.9,
      fiber: 1.8,
      sugar: 0.4,
      sodium: 5,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.5,
      k: 1.2,
      b1: 0.1,
      b2: 0.05,
      b3: 2.6,
      b5: 0.6,
      b6: 0.15,
      b7: 0.9,
      b9: 8,
      b12: 0,
    },
    minerals: {
      calcium: 10,
      iron: 0.5,
      magnesium: 44,
      phosphorus: 83,
      potassium: 79,
      sodium: 5,
      zinc: 0.6,
      copper: 0.1,
      manganese: 1.1,
      selenium: 9.8,
      fluoride: 8.4,
    },
    aminoAcids: {
      histidine: 63,
      isoleucine: 110,
      leucine: 216,
      lysine: 97,
      methionine: 55,
      phenylalanine: 134,
      threonine: 95,
      tryptophan: 33,
      valine: 159,
    },
    fattyAcids: {
      saturated: 0.2,
      monounsaturated: 0.3,
      polyunsaturated: 0.3,
      omega3: 0.03,
      omega6: 0.27,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wheat-chapati",
    name: "Whole Wheat Chapati",
    category: "Bread",
    description: "Traditional Indian flatbread made from whole wheat flour",
    isVegetarian: true,
    isVegan: true,
    containsGluten: true,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 30,
      unit: "g",
      description: "1 medium chapati",
    },
    nutrients: {
      calories: 85,
      protein: 3.1,
      carbohydrates: 17.2,
      fat: 0.4,
      fiber: 2.8,
      sugar: 0.2,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 0.9,
      b1: 0.08,
      b2: 0.06,
      b3: 0.9,
      b5: 0.2,
      b6: 0.09,
      b7: 1.5,
      b9: 14,
      b12: 0,
    },
    minerals: {
      calcium: 15,
      iron: 0.8,
      magnesium: 29,
      phosphorus: 82,
      potassium: 108,
      sodium: 2,
      zinc: 0.7,
      copper: 0.1,
      manganese: 0.8,
      selenium: 15.1,
      fluoride: 4.2,
    },
    aminoAcids: {
      histidine: 65,
      isoleucine: 126,
      leucine: 226,
      lysine: 86,
      methionine: 53,
      phenylalanine: 159,
      threonine: 94,
      tryptophan: 39,
      valine: 142,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.02,
      omega6: 0.18,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // LEGUMES
  {
    id: "lentils-red-cooked",
    name: "Red Lentils (Cooked)",
    category: "Legumes",
    description: "Cooked red lentils, commonly used in Indian dal preparations",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 116,
      protein: 9.0,
      carbohydrates: 20.1,
      fat: 0.4,
      fiber: 7.9,
      sugar: 1.8,
      sodium: 2,
    },
    vitamins: {
      a: 0,
      c: 1.5,
      d: 0,
      e: 0.1,
      k: 1.7,
      b1: 0.17,
      b2: 0.07,
      b3: 1.1,
      b5: 0.6,
      b6: 0.18,
      b7: 2.1,
      b9: 181,
      b12: 0,
    },
    minerals: {
      calcium: 19,
      iron: 3.3,
      magnesium: 36,
      phosphorus: 180,
      potassium: 369,
      sodium: 2,
      zinc: 1.3,
      copper: 0.3,
      manganese: 0.5,
      selenium: 2.8,
      fluoride: 9.0,
    },
    aminoAcids: {
      histidine: 207,
      isoleucine: 382,
      leucine: 621,
      lysine: 593,
      methionine: 77,
      phenylalanine: 427,
      threonine: 306,
      tryptophan: 77,
      valine: 437,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.1,
      polyunsaturated: 0.2,
      omega3: 0.03,
      omega6: 0.17,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chickpeas-cooked",
    name: "Chickpeas (Cooked)",
    category: "Legumes",
    description:
      "Cooked chickpeas (garbanzo beans), used in various cuisines including Indian, Middle Eastern, and Mediterranean",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 164,
      protein: 8.9,
      carbohydrates: 27.4,
      fat: 2.6,
      fiber: 7.6,
      sugar: 4.8,
      sodium: 7,
    },
    vitamins: {
      a: 27,
      c: 1.3,
      d: 0,
      e: 0.4,
      k: 4.0,
      b1: 0.12,
      b2: 0.06,
      b3: 0.5,
      b5: 0.3,
      b6: 0.14,
      b7: 1.5,
      b9: 172,
      b12: 0,
    },
    minerals: {
      calcium: 49,
      iron: 2.9,
      magnesium: 48,
      phosphorus: 168,
      potassium: 291,
      sodium: 7,
      zinc: 1.5,
      copper: 0.4,
      manganese: 1.0,
      selenium: 4.1,
      fluoride: 12.0,
    },
    aminoAcids: {
      histidine: 267,
      isoleucine: 422,
      leucine: 685,
      lysine: 593,
      methionine: 117,
      phenylalanine: 477,
      threonine: 346,
      tryptophan: 84,
      valine: 401,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 0.6,
      polyunsaturated: 1.2,
      omega3: 0.04,
      omega6: 1.16,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // VEGETABLES
  {
    id: "spinach-cooked",
    name: "Spinach (Cooked)",
    category: "Vegetables",
    description: "Cooked spinach, a nutrient-dense leafy green vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup cooked",
    },
    nutrients: {
      calories: 23,
      protein: 2.9,
      carbohydrates: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      sodium: 70,
    },
    vitamins: {
      a: 9377,
      c: 9.8,
      d: 0,
      e: 2.1,
      k: 494.8,
      b1: 0.09,
      b2: 0.24,
      b3: 0.7,
      b5: 0.1,
      b6: 0.24,
      b7: 0.8,
      b9: 146,
      b12: 0,
    },
    minerals: {
      calcium: 136,
      iron: 3.6,
      magnesium: 87,
      phosphorus: 56,
      potassium: 558,
      sodium: 70,
      zinc: 0.5,
      copper: 0.1,
      manganese: 0.9,
      selenium: 1.0,
      fluoride: 14.0,
    },
    aminoAcids: {
      histidine: 64,
      isoleucine: 117,
      leucine: 198,
      lysine: 140,
      methionine: 50,
      phenylalanine: 124,
      threonine: 108,
      tryptophan: 39,
      valine: 141,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.2,
      omega3: 0.14,
      omega6: 0.06,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tomato-raw",
    name: "Tomato (Raw)",
    category: "Vegetables",
    description: "Fresh raw tomato, commonly used in salads and various dishes",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium tomato",
    },
    nutrients: {
      calories: 18,
      protein: 0.9,
      carbohydrates: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
      sodium: 5,
    },
    vitamins: {
      a: 833,
      c: 13.7,
      d: 0,
      e: 0.5,
      k: 7.9,
      b1: 0.04,
      b2: 0.02,
      b3: 0.6,
      b5: 0.1,
      b6: 0.08,
      b7: 0.5,
      b9: 15,
      b12: 0,
    },
    minerals: {
      calcium: 10,
      iron: 0.3,
      magnesium: 11,
      phosphorus: 24,
      potassium: 237,
      sodium: 5,
      zinc: 0.2,
      copper: 0.1,
      manganese: 0.1,
      selenium: 0.0,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 18,
      isoleucine: 27,
      leucine: 42,
      lysine: 40,
      methionine: 11,
      phenylalanine: 30,
      threonine: 37,
      tryptophan: 7,
      valine: 30,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "potato-boiled",
    name: "Potato (Boiled)",
    category: "Vegetables",
    description: "Boiled potato without skin, a versatile starchy vegetable",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsRootVegetables: true,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium potato",
    },
    nutrients: {
      calories: 87,
      protein: 1.9,
      carbohydrates: 20.1,
      fat: 0.1,
      fiber: 1.8,
      sugar: 0.9,
      sodium: 6,
    },
    vitamins: {
      a: 0,
      c: 9.6,
      d: 0,
      e: 0.0,
      k: 1.6,
      b1: 0.08,
      b2: 0.03,
      b3: 1.1,
      b5: 0.3,
      b6: 0.3,
      b7: 0.7,
      b9: 9,
      b12: 0,
    },
    minerals: {
      calcium: 12,
      iron: 0.8,
      magnesium: 23,
      phosphorus: 57,
      potassium: 421,
      sodium: 6,
      zinc: 0.3,
      copper: 0.1,
      manganese: 0.2,
      selenium: 0.4,
      fluoride: 1.0,
    },
    aminoAcids: {
      histidine: 37,
      isoleucine: 74,
      leucine: 114,
      lysine: 108,
      methionine: 31,
      phenylalanine: 83,
      threonine: 73,
      tryptophan: 25,
      valine: 100,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.0,
      omega3: 0.0,
      omega6: 0.0,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // DAIRY
  {
    id: "milk-cow-whole",
    name: "Whole Milk",
    category: "Dairy",
    description: "Whole cow's milk with approximately 3.25% fat content",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "ml",
      description: "1 small glass",
    },
    nutrients: {
      calories: 61,
      protein: 3.2,
      carbohydrates: 4.8,
      fat: 3.3,
      fiber: 0,
      sugar: 5.1,
      sodium: 43,
    },
    vitamins: {
      a: 162,
      c: 0,
      d: 51,
      e: 0.1,
      k: 0.3,
      b1: 0.05,
      b2: 0.18,
      b3: 0.1,
      b5: 0.3,
      b6: 0.04,
      b7: 2.0,
      b9: 5,
      b12: 0.4,
    },
    minerals: {
      calcium: 113,
      iron: 0.0,
      magnesium: 10,
      phosphorus: 84,
      potassium: 132,
      sodium: 43,
      zinc: 0.4,
      copper: 0.0,
      manganese: 0.0,
      selenium: 3.7,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 89,
      isoleucine: 189,
      leucine: 322,
      lysine: 261,
      methionine: 83,
      phenylalanine: 159,
      threonine: 149,
      tryptophan: 46,
      valine: 220,
    },
    fattyAcids: {
      saturated: 1.9,
      monounsaturated: 0.8,
      polyunsaturated: 0.2,
      omega3: 0.08,
      omega6: 0.12,
      trans: 0.1,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "paneer",
    name: "Paneer (Indian Cottage Cheese)",
    category: "Dairy",
    description: "Fresh Indian cottage cheese made from curdled milk",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup cubed",
    },
    nutrients: {
      calories: 265,
      protein: 18.3,
      carbohydrates: 3.1,
      fat: 20.8,
      fiber: 0,
      sugar: 1.0,
      sodium: 34,
    },
    vitamins: {
      a: 274,
      c: 0,
      d: 16,
      e: 0.3,
      k: 1.0,
      b1: 0.03,
      b2: 0.21,
      b3: 0.1,
      b5: 0.5,
      b6: 0.08,
      b7: 1.5,
      b9: 14,
      b12: 1.1,
    },
    minerals: {
      calcium: 510,
      iron: 0.7,
      magnesium: 28,
      phosphorus: 490,
      potassium: 138,
      sodium: 34,
      zinc: 2.1,
      copper: 0.0,
      manganese: 0.0,
      selenium: 15.0,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 530,
      isoleucine: 1100,
      leucine: 1800,
      lysine: 1500,
      methionine: 480,
      phenylalanine: 950,
      threonine: 850,
      tryptophan: 260,
      valine: 1300,
    },
    fattyAcids: {
      saturated: 13.1,
      monounsaturated: 6.0,
      polyunsaturated: 0.8,
      omega3: 0.2,
      omega6: 0.6,
      trans: 0.5,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // FRUITS
  {
    id: "apple-raw",
    name: "Apple (Raw)",
    category: "Fruits",
    description: "Fresh raw apple with skin, a common fruit",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 small apple",
    },
    nutrients: {
      calories: 52,
      protein: 0.3,
      carbohydrates: 13.8,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10.4,
      sodium: 1,
    },
    vitamins: {
      a: 54,
      c: 4.6,
      d: 0,
      e: 0.2,
      k: 2.2,
      b1: 0.02,
      b2: 0.03,
      b3: 0.1,
      b5: 0.1,
      b6: 0.04,
      b7: 0.1,
      b9: 3,
      b12: 0,
    },
    minerals: {
      calcium: 6,
      iron: 0.1,
      magnesium: 5,
      phosphorus: 11,
      potassium: 107,
      sodium: 1,
      zinc: 0.0,
      copper: 0.0,
      manganese: 0.0,
      selenium: 0.0,
      fluoride: 3.3,
    },
    aminoAcids: {
      histidine: 3,
      isoleucine: 6,
      leucine: 13,
      lysine: 12,
      methionine: 1,
      phenylalanine: 5,
      threonine: 6,
      tryptophan: 1,
      valine: 8,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.01,
      omega6: 0.09,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "banana-raw",
    name: "Banana (Raw)",
    category: "Fruits",
    description: "Fresh raw banana, a common tropical fruit",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium banana",
    },
    nutrients: {
      calories: 89,
      protein: 1.1,
      carbohydrates: 22.8,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12.2,
      sodium: 1,
    },
    vitamins: {
      a: 64,
      c: 8.7,
      d: 0,
      e: 0.1,
      k: 0.5,
      b1: 0.03,
      b2: 0.07,
      b3: 0.7,
      b5: 0.3,
      b6: 0.37,
      b7: 0.1,
      b9: 20,
      b12: 0,
    },
    minerals: {
      calcium: 5,
      iron: 0.3,
      magnesium: 27,
      phosphorus: 22,
      potassium: 358,
      sodium: 1,
      zinc: 0.2,
      copper: 0.1,
      manganese: 0.3,
      selenium: 1.0,
      fluoride: 2.2,
    },
    aminoAcids: {
      histidine: 28,
      isoleucine: 28,
      leucine: 65,
      lysine: 50,
      methionine: 10,
      phenylalanine: 39,
      threonine: 31,
      tryptophan: 12,
      valine: 40,
    },
    fattyAcids: {
      saturated: 0.1,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.03,
      omega6: 0.07,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // NUTS AND SEEDS
  {
    id: "almonds-raw",
    name: "Almonds (Raw)",
    category: "Nuts and Seeds",
    description: "Raw whole almonds, a nutrient-dense tree nut",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3/4 cup",
    },
    nutrients: {
      calories: 579,
      protein: 21.2,
      carbohydrates: 21.7,
      fat: 49.9,
      fiber: 12.5,
      sugar: 4.4,
      sodium: 1,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 25.6,
      k: 0,
      b1: 0.21,
      b2: 1.14,
      b3: 3.6,
      b5: 0.5,
      b6: 0.14,
      b7: 0.1,
      b9: 44,
      b12: 0,
    },
    minerals: {
      calcium: 269,
      iron: 3.7,
      magnesium: 270,
      phosphorus: 481,
      potassium: 733,
      sodium: 1,
      zinc: 3.1,
      copper: 1.0,
      manganese: 2.3,
      selenium: 4.1,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 648,
      isoleucine: 875,
      leucine: 1778,
      lysine: 728,
      methionine: 195,
      phenylalanine: 1132,
      threonine: 709,
      tryptophan: 215,
      valine: 1221,
    },
    fattyAcids: {
      saturated: 3.8,
      monounsaturated: 31.6,
      polyunsaturated: 12.3,
      omega3: 0.0,
      omega6: 12.3,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // OILS
  {
    id: "oil-mustard",
    name: "Mustard Oil",
    category: "Oils",
    description: "Mustard oil, commonly used in Indian cooking",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "7 tablespoons",
    },
    nutrients: {
      calories: 884,
      protein: 0,
      carbohydrates: 0,
      fat: 100,
      fiber: 0,
      sugar: 0,
      sodium: 0,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 17.5,
      k: 5.4,
      b1: 0,
      b2: 0,
      b3: 0,
      b5: 0,
      b6: 0,
      b7: 0,
      b9: 0,
      b12: 0,
    },
    minerals: {
      calcium: 0,
      iron: 0,
      magnesium: 0,
      phosphorus: 0,
      potassium: 0,
      sodium: 0,
      zinc: 0,
      copper: 0,
      manganese: 0,
      selenium: 0,
      fluoride: 0,
    },
    aminoAcids: {
      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,
    },
    fattyAcids: {
      saturated: 11.6,
      monounsaturated: 59.2,
      polyunsaturated: 21.2,
      omega3: 5.9,
      omega6: 15.3,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ghee",
    name: "Ghee (Clarified Butter)",
    category: "Oils",
    description: "Clarified butter commonly used in Indian cooking",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "7 tablespoons",
    },
    nutrients: {
      calories: 900,
      protein: 0,
      carbohydrates: 0,
      fat: 100,
      fiber: 0,
      sugar: 0,
      sodium: 0,
    },
    vitamins: {
      a: 3069,
      c: 0,
      d: 41,
      e: 2.8,
      k: 8.6,
      b1: 0,
      b2: 0,
      b3: 0,
      b5: 0,
      b6: 0,
      b7: 0,
      b9: 0,
      b12: 0.1,
    },
    minerals: {
      calcium: 4,
      iron: 0,
      magnesium: 0,
      phosphorus: 0,
      potassium: 0,
      sodium: 0,
      zinc: 0,
      copper: 0,
      manganese: 0,
      selenium: 0,
      fluoride: 0,
    },
    aminoAcids: {
      histidine: 0,
      isoleucine: 0,
      leucine: 0,
      lysine: 0,
      methionine: 0,
      phenylalanine: 0,
      threonine: 0,
      tryptophan: 0,
      valine: 0,
    },
    fattyAcids: {
      saturated: 65.0,
      monounsaturated: 28.7,
      polyunsaturated: 3.7,
      omega3: 1.4,
      omega6: 2.3,
      trans: 4.0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // SPICES
  {
    id: "turmeric-ground",
    name: "Turmeric (Ground)",
    category: "Spices",
    description: "Ground turmeric powder, a common spice in Indian cooking with anti-inflammatory properties",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South Asia",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/3 cup",
    },
    nutrients: {
      calories: 312,
      protein: 9.7,
      carbohydrates: 67.1,
      fat: 3.3,
      fiber: 22.7,
      sugar: 3.2,
      sodium: 27,
    },
    vitamins: {
      a: 0,
      c: 0.7,
      d: 0,
      e: 4.4,
      k: 13.4,
      b1: 0.06,
      b2: 0.15,
      b3: 1.4,
      b5: 0.5,
      b6: 0.11,
      b7: 0.0,
      b9: 20,
      b12: 0,
    },
    minerals: {
      calcium: 168,
      iron: 55.0,
      magnesium: 208,
      phosphorus: 299,
      potassium: 2080,
      sodium: 27,
      zinc: 4.4,
      copper: 1.3,
      manganese: 19.8,
      selenium: 6.2,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 113,
      isoleucine: 182,
      leucine: 306,
      lysine: 199,
      methionine: 87,
      phenylalanine: 216,
      threonine: 151,
      tryptophan: 59,
      valine: 240,
    },
    fattyAcids: {
      saturated: 1.8,
      monounsaturated: 0.6,
      polyunsaturated: 0.8,
      omega3: 0.4,
      omega6: 0.4,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cumin-seeds",
    name: "Cumin Seeds",
    category: "Spices",
    description: "Whole cumin seeds, a common spice in Indian, Middle Eastern, and Mexican cooking",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "Global",
    cuisine: "Multiple",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 375,
      protein: 17.8,
      carbohydrates: 44.2,
      fat: 22.3,
      fiber: 10.5,
      sugar: 2.3,
      sodium: 168,
    },
    vitamins: {
      a: 64,
      c: 7.7,
      d: 0,
      e: 3.3,
      k: 5.4,
      b1: 0.63,
      b2: 0.33,
      b3: 4.6,
      b5: 0.5,
      b6: 0.44,
      b7: 0.0,
      b9: 10,
      b12: 0,
    },
    minerals: {
      calcium: 931,
      iron: 66.4,
      magnesium: 366,
      phosphorus: 499,
      potassium: 1788,
      sodium: 168,
      zinc: 4.8,
      copper: 0.9,
      manganese: 3.3,
      selenium: 5.2,
      fluoride: 0.0,
    },
    aminoAcids: {
      histidine: 398,
      isoleucine: 495,
      leucine: 1118,
      lysine: 638,
      methionine: 240,
      phenylalanine: 735,
      threonine: 518,
      tryptophan: 183,
      valine: 740,
    },
    fattyAcids: {
      saturated: 1.5,
      monounsaturated: 14.0,
      polyunsaturated: 3.8,
      omega3: 0.4,
      omega6: 3.4,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // INDIAN DISHES
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    category: "Indian Dishes",
    description: "Creamy black lentil and kidney bean curry with butter and cream",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 126,
      protein: 7.2,
      carbohydrates: 16.8,
      fat: 4.1,
      fiber: 5.2,
      sugar: 1.2,
      sodium: 302,
    },
    vitamins: {
      a: 98,
      c: 3.2,
      d: 0.2,
      e: 0.5,
      k: 3.1,
      b1: 0.12,
      b2: 0.08,
      b3: 0.9,
      b5: 0.4,
      b6: 0.14,
      b7: 1.2,
      b9: 72,
      b12: 0.1,
    },
    minerals: {
      calcium: 42,
      iron: 2.8,
      magnesium: 39,
      phosphorus: 142,
      potassium: 328,
      sodium: 302,
      zinc: 1.2,
      copper: 0.3,
      manganese: 0.6,
      selenium: 3.1,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 182,
      isoleucine: 312,
      leucine: 521,
      lysine: 482,
      methionine: 89,
      phenylalanine: 362,
      threonine: 258,
      tryptophan: 72,
      valine: 362,
    },
    fattyAcids: {
      saturated: 2.1,
      monounsaturated: 1.2,
      polyunsaturated: 0.4,
      omega3: 0.1,
      omega6: 0.3,
      trans: 0.1,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chana-masala",
    name: "Chana Masala",
    category: "Indian Dishes",
    description: "Spicy chickpea curry with tomatoes and spices",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 164,
      protein: 7.3,
      carbohydrates: 22.5,
      fat: 6.2,
      fiber: 6.0,
      sugar: 3.8,
      sodium: 298,
    },
    vitamins: {
      a: 112,
      c: 15.2,
      d: 0,
      e: 1.2,
      k: 9.8,
      b1: 0.11,
      b2: 0.07,
      b3: 0.8,
      b5: 0.3,
      b6: 0.12,
      b7: 1.2,
      b9: 65,
      b12: 0,
    },
    minerals: {
      calcium: 58,
      iron: 2.7,
      magnesium: 42,
      phosphorus: 138,
      potassium: 291,
      sodium: 298,
      zinc: 1.3,
      copper: 0.3,
      manganese: 0.8,
      selenium: 3.2,
      fluoride: 10.0,
    },
    aminoAcids: {
      histidine: 192,
      isoleucine: 302,
      leucine: 492,
      lysine: 425,
      methionine: 98,
      phenylalanine: 342,
      threonine: 248,
      tryptophan: 68,
      valine: 312,
    },
    fattyAcids: {
      saturated: 0.8,
      monounsaturated: 3.8,
      polyunsaturated: 1.2,
      omega3: 0.1,
      omega6: 1.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    category: "Indian Dishes",
    description: "Spinach curry with Indian cottage cheese cubes",
    isVegetarian: true,
    isVegan: false,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 169,
      protein: 8.9,
      carbohydrates: 6.2,
      fat: 13.1,
      fiber: 2.0,
      sugar: 1.8,
      sodium: 312,
    },
    vitamins: {
      a: 4125,
      c: 14.2,
      d: 0.2,
      e: 1.8,
      k: 234.2,
      b1: 0.08,
      b2: 0.18,
      b3: 0.6,
      b5: 0.3,
      b6: 0.18,
      b7: 1.0,
      b9: 105,
      b12: 0.4,
    },
    minerals: {
      calcium: 258,
      iron: 2.8,
      magnesium: 68,
      phosphorus: 198,
      potassium: 362,
      sodium: 312,
      zinc: 1.2,
      copper: 0.2,
      manganese: 0.7,
      selenium: 4.2,
      fluoride: 8.0,
    },
    aminoAcids: {
      histidine: 242,
      isoleucine: 382,
      leucine: 642,
      lysine: 512,
      methionine: 182,
      phenylalanine: 362,
      threonine: 312,
      tryptophan: 102,
      valine: 452,
    },
    fattyAcids: {
      saturated: 6.8,
      monounsaturated: 4.2,
      polyunsaturated: 1.2,
      omega3: 0.4,
      omega6: 0.8,
      trans: 0.2,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "aloo-gobi",
    name: "Aloo Gobi",
    category: "Indian Dishes",
    description: "Potato and cauliflower curry with spices",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    containsRootVegetables: true,
    source: "ifct",
    region: "North India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 112,
      protein: 3.2,
      carbohydrates: 16.8,
      fat: 4.5,
      fiber: 3.8,
      sugar: 2.2,
      sodium: 285,
    },
    vitamins: {
      a: 42,
      c: 32.5,
      d: 0,
      e: 0.8,
      k: 18.2,
      b1: 0.12,
      b2: 0.08,
      b3: 1.0,
      b5: 0.6,
      b6: 0.28,
      b7: 0.6,
      b9: 42,
      b12: 0,
    },
    minerals: {
      calcium: 32,
      iron: 1.2,
      magnesium: 28,
      phosphorus: 68,
      potassium: 478,
      sodium: 285,
      zinc: 0.4,
      copper: 0.1,
      manganese: 0.3,
      selenium: 0.8,
      fluoride: 2.0,
    },
    aminoAcids: {
      histidine: 72,
      isoleucine: 132,
      leucine: 192,
      lysine: 182,
      methionine: 52,
      phenylalanine: 142,
      threonine: 122,
      tryptophan: 42,
      valine: 172,
    },
    fattyAcids: {
      saturated: 0.6,
      monounsaturated: 2.8,
      polyunsaturated: 0.8,
      omega3: 0.1,
      omega6: 0.7,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "sambar",
    name: "Sambar",
    category: "Indian Dishes",
    description: "South Indian lentil and vegetable stew with tamarind",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1/2 cup",
    },
    nutrients: {
      calories: 98,
      protein: 3.8,
      carbohydrates: 16.2,
      fat: 2.1,
      fiber: 4.2,
      sugar: 2.8,
      sodium: 312,
    },
    vitamins: {
      a: 182,
      c: 12.8,
      d: 0,
      e: 0.6,
      k: 8.2,
      b1: 0.08,
      b2: 0.05,
      b3: 0.8,
      b5: 0.3,
      b6: 0.12,
      b7: 0.8,
      b9: 42,
      b12: 0,
    },
    minerals: {
      calcium: 42,
      iron: 1.8,
      magnesium: 32,
      phosphorus: 82,
      potassium: 248,
      sodium: 312,
      zinc: 0.6,
      copper: 0.2,
      manganese: 0.4,
      selenium: 1.8,
      fluoride: 6.0,
    },
    aminoAcids: {
      histidine: 92,
      isoleucine: 162,
      leucine: 262,
      lysine: 182,
      methionine: 42,
      phenylalanine: 182,
      threonine: 132,
      tryptophan: 38,
      valine: 182,
    },
    fattyAcids: {
      saturated: 0.3,
      monounsaturated: 1.2,
      polyunsaturated: 0.5,
      omega3: 0.1,
      omega6: 0.4,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "idli",
    name: "Idli",
    category: "Indian Dishes",
    description: "Steamed rice and fermented black lentil cakes, a South Indian breakfast item",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "3 medium idlis",
    },
    nutrients: {
      calories: 78,
      protein: 2.6,
      carbohydrates: 16.5,
      fat: 0.1,
      fiber: 0.9,
      sugar: 0.2,
      sodium: 185,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.1,
      k: 0.2,
      b1: 0.06,
      b2: 0.04,
      b3: 0.4,
      b5: 0.2,
      b6: 0.08,
      b7: 0.6,
      b9: 12,
      b12: 0,
    },
    minerals: {
      calcium: 12,
      iron: 0.6,
      magnesium: 18,
      phosphorus: 42,
      potassium: 62,
      sodium: 185,
      zinc: 0.4,
      copper: 0.1,
      manganese: 0.3,
      selenium: 1.2,
      fluoride: 4.0,
    },
    aminoAcids: {
      histidine: 62,
      isoleucine: 112,
      leucine: 182,
      lysine: 92,
      methionine: 42,
      phenylalanine: 122,
      threonine: 82,
      tryptophan: 28,
      valine: 132,
    },
    fattyAcids: {
      saturated: 0.0,
      monounsaturated: 0.0,
      polyunsaturated: 0.1,
      omega3: 0.0,
      omega6: 0.1,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dosa",
    name: "Dosa",
    category: "Indian Dishes",
    description: "Thin crispy fermented rice and black lentil crepe, a South Indian breakfast item",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    source: "ifct",
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 medium dosa",
    },
    nutrients: {
      calories: 168,
      protein: 3.4,
      carbohydrates: 29.2,
      fat: 4.3,
      fiber: 1.2,
      sugar: 0.4,
      sodium: 210,
    },
    vitamins: {
      a: 0,
      c: 0,
      d: 0,
      e: 0.2,
      k: 0.4,
      b1: 0.08,
      b2: 0.05,
      b3: 0.6,
      b5: 0.3,
      b6: 0.1,
      b7: 0.8,
      b9: 15,
      b12: 0,
    },
    minerals: {
      calcium: 18,
      iron: 0.8,
      magnesium: 24,
      phosphorus: 56,
      potassium: 82,
      sodium: 210,
      zinc: 0.5,
      copper: 0.1,
      manganese: 0.4,
      selenium: 1.5,
      fluoride: 5.0,
    },
    aminoAcids: {
      histidine: 78,
      isoleucine: 142,
      leucine: 232,
      lysine: 112,
      methionine: 52,
      phenylalanine: 152,
      threonine: 102,
      tryptophan: 35,
      valine: 162,
    },
    fattyAcids: {
      saturated: 0.6,
      monounsaturated: 2.8,
      polyunsaturated: 0.8,
      omega3: 0.1,
      omega6: 0.7,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // BREAKFAST ITEMS
  {
    id: "poha",
    name: "Poha",
    category: "Breakfast",
    description: "Flattened rice flakes cooked with spices, onions, and peanuts",
    isVegetarian: true,
    isVegan: true,
    containsGluten: false,
    containsOnionGarlic: true,
    source: "ifct",
    region: "Central India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup",
    },
    nutrients: {
      calories: 165,
      protein: 3.6,
      carbohydrates: 30.2,
      fat: 3.8,
      fiber: 1.6,
      sugar: 1.2,
      sodium: 245,
    },
    vitamins: {
      a: 42,
      c: 8.2,
      d: 0,
      e: 0.4,
      k: 2.8,
      b1: 0.12,
      b2: 0.06,
      b3: 1.2,
      b5: 0.4,
      b6: 0.12,
      b7: 0.8,
      b9: 12,
      b12: 0,
    },
    minerals: {
      calcium: 15,
      iron: 1.8,
      magnesium: 32,
      phosphorus: 68,
      potassium: 142,
      sodium: 245,
      zinc: 0.8,
      copper: 0.2,
      manganese: 0.6,
      selenium: 2.2,
      fluoride: 6.0,
    },
    aminoAcids: {
      histidine: 82,
      isoleucine: 152,
      leucine: 262,
      lysine: 122,
      methionine: 62,
      phenylalanine: 162,
      threonine: 112,
      tryptophan: 42,
      valine: 182,
    },
    fattyAcids: {
      saturated: 0.6,
      monounsaturated: 2.2,
      polyunsaturated: 0.8,
      omega3: 0.1,
      omega6: 0.7,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "upma",
    name: "Upma",
    category: "Breakfast",
    description: "Savory semolina porridge with vegetables and spices",
    isVegetarian: true,
    isVegan: true,
    containsGluten: true,
    containsOnionGarlic: true,
    source: "ifct",
    region: "South India",
    cuisine: "Indian",
    standardPortion: {
      amount: 100,
      unit: "g",
      description: "1 cup",
    },
    nutrients: {
      calories: 152,
      protein: 4.2,
      carbohydrates: 26.8,
      fat: 3.6,
      fiber: 1.8,
      sugar: 1.4,
      sodium: 265,
    },
    vitamins: {
      a: 38,
      c: 6.8,
      d: 0,
      e: 0.3,
      k: 2.4,
      b1: 0.14,
      b2: 0.08,
      b3: 1.4,
      b5: 0.5,
      b6: 0.14,
      b7: 1.0,
      b9: 15,
      b12: 0,
    },
    minerals: {
      calcium: 18,
      iron: 1.6,
      magnesium: 28,
      phosphorus: 72,
      potassium: 132,
      sodium: 265,
      zinc: 0.7,
      copper: 0.2,
      manganese: 0.5,
      selenium: 2.0,
      fluoride: 5.0,
    },
    aminoAcids: {
      histidine: 92,
      isoleucine: 172,
      leucine: 282,
      lysine: 132,
      methionine: 72,
      phenylalanine: 182,
      threonine: 122,
      tryptophan: 48,
      valine: 192,
    },
    fattyAcids: {
      saturated: 0.5,
      monounsaturated: 2.0,
      polyunsaturated: 0.9,
      omega3: 0.1,
      omega6: 0.8,
      trans: 0,
    },
    keywords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Add keywords to each food item
detailedFoods.forEach((food) => {
  food.keywords = generateKeywords(food)
})

// Function to populate the database with detailed food items
async function populateDetailedFoodDatabase() {
  console.log(`Starting to populate database with ${detailedFoods.length} detailed food items...`)

  const batchSize = 20 // Process in smaller batches to avoid rate limiting
  let successCount = 0
  let errorCount = 0

  for (let i = 0; i < detailedFoods.length; i += batchSize) {
    const batch = detailedFoods.slice(i, i + batchSize)
    const promises = batch.map(async (food) => {
      try {
        // Add to ifct_foods collection
        await db.collection("ifct_foods").doc(food.id).set(food)
        console.log(`✅ Added ${food.name} to database`)
        successCount++
        return true
      } catch (error) {
        console.error(`❌ Error adding ${food.name}:`, error)
        errorCount++
        return false
      }
    })

    await Promise.all(promises)
    console.log(`Processed batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(detailedFoods.length / batchSize)}`)
  }

  console.log(`Database population complete!`)
  console.log(`Successfully added: ${successCount} items`)
  console.log(`Failed to add: ${errorCount} items`)
}

// Execute the function
populateDetailedFoodDatabase()
  .then(() => {
    console.log("Script execution completed.")
    process.exit(0)
  })
  .catch((error) => {
    console.error("Script execution failed:", error)
    process.exit(1)
  })
